### ISSUE TITLE
Consider updating to Alfheim 1.4

### ISSUE THREAD

**Issue by lynxx131** [Nomi-CEu/Nomi-CEu#1009]
### Nomi CEu Version

1.7a

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added LazyAE2 and AE2 Fluid Crafting

### Environment

Dedicated server

### Mode

Normal Mode

### Your Solution

Update Alfheim Lighting Engine to version 1.4

I know previous update attempt to 1.3 caused some crashing weirdness with Ender IO tanks however I have been running 1.4 stable with no issues since it released nearly a month ago.

### How Will Your Solution Work

Update pack with Alfheim 1.4

**Comment by IntegerLimit** [comment]
The reason for not updating was high RAM usage, but we will take a look at this for 1.7.1.
