### ISSUE TITLE
Autoclave recipes for AE2 Pure crystals dont work

### ISSUE THREAD

**Issue by Ben-Bingham** [Nomi-CEu/Nomi-CEu#1010]
### Nomi CEu Version

1.7

### Launcher

Prisim Launcher

### Configurations or Mods Changed

Default pack download from curseforge through Prisim

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Placed a stack of fluix dust, a fluix seed and distilled water inside of an EV autoclave, powered it and nothing happened. I tried the same thing for both certus and regular quartz. I asked in the discord and someone said that this has been broken for a bit, and that I just needed to cheat in the non consumed seed, cheating in through JEI cheat mode did not work, however I was able to get the certus recipe working by cheating in the seed with the command: /give @p appliedenergistics2:crystal_seed, playing around with it more I tried setting the "progress" tag with the give command to get the other seds, but to no avail.

I was able to replicate the same behavior in creative

### Expected Behavior

I expected the recipes for pure crystals to create pure crystals

### Additional Information

I assume this is caused by some weird nbt data on the seeds

**Comment by IntegerLimit** [comment]
Fixed in nightly. Consider upgrading, although we plan to release 1.7.1 once some other fixes and enhancements are complete.
