### ISSUE TITLE
Remove, replace, or adjust Double Plate quests

### ISSUE THREAD

**Issue by python-nerd-3** [Nomi-CEu/Nomi-CEu#1011]
### Nomi CEu Version

1.7a

### Launcher

CurseForge

### Environment

Singleplayer (LAN on)

### Mode

Normal Mode

### Related Problem

The double plate quests, usually associated with Micro Miners are largely unnecessary. They can be easily acquired using just a hammer for the same rates as an MV bending machine. They are also quite unbalanced, with the Draconium Double Plates quest giving a quarter.

### Your Solution

There are 3 options to fix these quests:

- Simply remove them.
- Replace them with other, more relevant/less trivial quests. For example, the Double Steel Plates quest could be replaced with "Micro Miner Components", which would require a Basic Micro Miner Guidance System and Basic Mining Laser; or with "LV F
- Adjust them to require more Double Plates. The Titanium Double Playes quest, for example, could require 6 Double Plates as that's the amount used in the Tier Two Micro Miner.

### How Will Your Solution Work

N/A

**Comment by smallming675** [comment]
Implemented in #1007
