### ISSUE TITLE
Typo in First Foray Into The Microverse quest

### ISSUE THREAD

**Issue by python-nerd-3** [Nomi-CEu/Nomi-CEu#1012]
### Nomi CEu Version

1.7a

### Launcher

CurseForge

### Environment

Singeplayer (Open to LAN)

### Mode

Normal Mode

### What Happened

The "First Foray Into The Microverse" quest has a typo, where instead of saying Ilmenite Ore, it says Imenite Ore.

Unplayable.

### Expected Behavior

N/A

**Comment by smallming675** [comment]
![](https://github.com/user-attachments/assets/814715f8-067b-463c-b088-82c25124b4fc)
![](https://github.com/user-attachments/assets/65b0683e-cfa0-49b1-8099-930793ccc776)

Doesn't seem like it was incorrect, also didn't find any other cases for "Imenite".

**Comment by python-nerd-3** [comment]
I swear it was there ??? lol
