### ISSUE TITLE
Assembler can't run recipe for Fluix Logic Units from Lazy AE2

### ISSUE THREAD

**Issue by ChromaPIE** [Nomi-CEu/Nomi-CEu#1056]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

Porbably not related

### Environment

SP

### Mode

Normal Mode

### What Happened

![图片](https://github.com/user-attachments/assets/789de81a-ea14-4dff-851e-ffc805a7b72c)

and yes, i've checked everything. power supply, recipe voltage, everything. recipe coded from JEI to the pattern then sent to the machine, but it refuses to run.

scripts/AddonScripts/LazyAE2.zs:
```zenscript
// Fluix Logic
circuit_assembler.recipeBuilder()
    .inputs(<metaitem:frameTitanium>, <ore:circuitIv>, <appliedenergistics2:material:24> * 3, <threng:material> * 4, <appliedenergistics2:part:16> * 4)
    .fluidInputs(<liquid:soldering_alloy> * 144)
    .outputs(<threng:material:4>)
    .duration(400).EUt(1920).buildAndRegister();
circuit_assembler.recipeBuilder()
    .inputs(<metaitem:frameTitanium>, <ore:circuitIv>, <appliedenergistics2:material:24> * 3, <threng:material> * 4, <appliedenergistics2:part:16> * 4)
    .fluidInputs(<liquid:tin> * 288)
    .outputs(<threng:material:4>)
    .duration(400).EUt(1920).buildAndRegister();
```

### Expected Behavior

It gives me the Unit.

**Comment by IntegerLimit** [comment]
What was the issue?

**Comment by ChromaPIE** [comment]
<details> 
  <summary>don't</summary>
   that's a circuit assembler recipe
</details>

**Comment by IntegerLimit** [comment]
Oh....
