### ISSUE TITLE
Division by Zero error in Groovy upon starting a world

### ISSUE THREAD

**Issue by Mazlaci** [Nomi-CEu/Nomi-CEu#1075]
### Nomi CEu Version

1.7.2

### Launcher

Curseforge

### Configurations or Mods Changed

I added [StepUp](https://www.curseforge.com/minecraft/mc-mods/stepup) mod, and Quark but disabled almost everything only leaving minimal mostly clientside modifications. I attached [my config file](https://github.com/user-attachments/files/17381153/quark.txt) for it. Othervise did not change the original mods or configs.

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

After updating to the latest Nomifactory version, when runinng my world it throws a "Divison by zero" error in the chat.

![2024-10-15_17 29 57](https://github.com/user-attachments/assets/10059aa9-fe29-496b-b9ae-de594a6a8bdd)

### Expected Behavior

No "Divison by zero" error  occures, as in earlier versions.

### Logs

[latest.log](https://github.com/user-attachments/files/17381039/latest.log)
[groovy.log](https://github.com/user-attachments/files/17381040/groovy.log)

### Additional Information

I did a little digging, and the cause seems to be in the `tooltips.groovy` file expecially the following block:
```javascript
// Matter
for (MetadataLivingMatter matter : MetadataManager.livingMatterMetadataList) {
	// XP is as a Percent of One Level
	int xpPercent = (matter.xpValue / LabsConfig.advanced.otherModsLinearXp) * 100
	if (xpPercent == 100)
		addTooltip(matter.itemStack, translatable('nomiceu.tooltip.dme.matter.full_level'))
	else
		addTooltip(matter.itemStack, translatable('nomiceu.tooltip.dme.matter', xpPercent))
}
```

Looks like `LabsConfig.advanced.otherModsLinearXp` returns null in this context.

Testing with this block commented out makes it so no error appears.

**Comment by IntegerLimit** [comment]
It seems your Nomi Labs config was not replaced properly by your launcher. If you used the update button in the launcher, that would be why.

Please update by creating a new instance. (See [Wiki](https://github.com/Nomi-CEu/Nomi-CEu/wiki/Page-1:-Player-Information#27-updating) for more details)

Also, note that Nomi CEu 1.7+ has the step up behaviour in singleplayer worlds. The feature is implemented by Universal Tweaks. On Multiplayer, you can get this behaviour with dark steel boots and the relevant upgrade.
