### ISSUE TITLE
Wetware chain in HM not allowing GCYM's in Sterile Cleanrooms

### ISSUE THREAD

**Issue by MatPietrzyk** [Nomi-CEu/Nomi-CEu#1077]
### Nomi CEu Version

1.7.2

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Expert Mode

### Related Problem

The problem I encountered is that while it is possible to make every recipe in the game in GCYM's in HardMode, the wetware chain, specifically recipes requiring a brewery, heating machine and distillery are not possible to make in GCYM's because of the muffler in the multiblock. Sterile cleanroom is the only blockade in the process of changing Gregtech machines into GCYM's in the later stages (which is usually the progression of the pack) beacuse of inability of putting the Brewing Vat and Fractionating Distillery into them because of the muffler block. This might not be exactly a big problem, but not being able to do this thing is a bother because it's possible in every single other instance in the game.

### Your Solution

My solution would be changing the recipe in a multiblock for The Brewing Vat and Fractionating Distillery from requiring muffler to something else so that every process in the pack can be crafted in GCYM's and not requiring single block machines.

### How Will Your Solution Work

^

**Comment by IntegerLimit** [comment]
Interesting problem. Of course, you can use Processing Arrays...

**Comment by Folanlron** [comment]
It is Intended that they cannot be used in the Cleanroom/Sterile Cleanroom cause of the muffler hatch.

Use PAs instead.

**Comment by MatPietrzyk** [comment]
Alright, if that's indended as you say, then I have nothing to add then, I was just wondering if it "slipped through the cracks" and was not thought about because it's not a very important topic.
