### ISSUE TITLE
OreDict on Bounties

### ISSUE THREAD

**Issue by NarigudoBR** [Nomi-CEu/Nomi-CEu#1086]
### Nomi CEu Version

1.7.3

### Launcher

Curseforge

### Configurations or Mods Changed

None

### Environment

Singleplayer

### Mode

Normal Mode

### Your Solution

Add oredict to bounties

### How Will Your Solution Work

I can make the most efficient circuit and submit it

**Comment by IntegerLimit** [comment]
Bountiful does not support oredicts, and although we could mixin into bountiful to make it support oredicts, we do not intend to do so.

Bounties are meant for you to get a small surplus of coins in the early game, and we do not want to encourage them any further than we already have.
