### ISSUE TITLE
"Multi Fluid Hatches" quest is innacurate

### ISSUE THREAD

**Issue by toaster128** [Nomi-CEu/Nomi-CEu#1087]
### Nomi CEu Version

1.7a

### Launcher

ATLauncher

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

Multi Fluid Hatch quest states that Multi Fluid Hatches (EV Quadruple and Nonuple Fluid Hatches) cannot form multiblocks such as the Distillation Tower, when they can be used to.

### Expected Behavior

Either the Multi Fluid Hatch quest doesn't use the innacurate example of Distillation Towers, or the Distillation Tower can't form using these hatches.

### Reproduction Steps

1. Build a Distillation Tower with a Quadruple Input Hatch and at least 1 Quadruple Output Hatch
2. See it form.
3. Check Questbook
4. See the Questbook is inaccurate.

**Comment by Folanlron** [comment]
Quad/Nonuple Inputs yes, outputs they shouldn't be forming with them, 

also update to the newer beta.

**Comment by IntegerLimit** [comment]
Clarification: Newer Stable Release (No Betas Past 1.7 Yet)

**Comment by IntegerLimit** [comment]
QB: Add a note saying distillation tower cannot be formed with Quadruple/Nonuple Output Hatches.

**Comment by IntegerLimit** [comment]
Note already exists. Closing...
