### ISSUE TITLE
Mixer recipe overlap (Red Steel / Tungstencarbide)

### ISSUE THREAD

**Issue by subrezon** [Nomi-CEu/Nomi-CEu#1102]
### Nomi CEu Version

1.7.3

### Launcher

Prism Launcher

### Environment

Multiplayer

### Mode

Normal Mode

### What Happened

If you use a Mixer with Programmed Circuit (1) and put in ingredients for Red Steel Dust (1x Sterling Silver Dust, 1x Bismuth Bronze Dust, 4x Black Steel Dust, **2x Steel Dust**) and Tungstencarbide Dust (**1x Tungsten Dust**, 1x Carbon Dust), Tungstensteel Dust may get produced instead. This behavior forced using Blocking Mode on ME Interfaces / several Mixers / several inputs on a Large Mixer to avoid miscrafts.

### Expected Behavior

All 3 recipes should be distinct and shouldn't overlap in this way. Best change the Programmed Circuit number on one of them.

**Comment by IntegerLimit** [comment]
You are meant to use blocking mode regardless, otherwise this behaviour would occur everywhere.

**Comment by subrezon** [comment]
Isn't the whole point of Programming Circuits in Mixer recipes to prevent recipe overlaps? If not - why have them at all?

I understand that I'm meant to use blocking mode, but not using it allows me to fully overclock a single craft or fully parallelize multiple (by letting the system dump all ingredients into the input bus at once) using a single 1x pattern, assuming you have an input bus per Programming Circuit number. It's a very simple and fast system and has worked with everything so far, except this one overlap.

**Comment by IntegerLimit** [comment]
Programmed circuits are to prevent recipe overlaps, but to ensure that recipes can still be run. For example, a recipe with 2 of X and 3 of Y can be run without running the recipe for X instead.

I do understand the merits of not having blocking mode, but it is better to increase the parallel instead, and this will cause you problems in the future regardless, with other machines.

However, will consider changing the circuits of a recipe, although we generally try to avoid this when possible, as the change is hard to spot for players.

**Comment by subrezon** [comment]
In 1.8 perhaps? I understand why it absolutely shouldn't be changed in a minor release.

**Comment by IntegerLimit** [comment]
Yes, if this were to be fixed it would be in 1.8.
