### ISSUE TITLE
Jammed Server Initializtion Relateed to Lost Enderio Loot Table

### ISSUE THREAD

**Issue by MrJefferySmith** [Nomi-CEu/Nomi-CEu#1107]
### Nomi CEu Version

1.7.3

### Launcher

Forge Server

### Configurations or Mods Changed

AE2 Fluid Craftint Rework       2.6.6-r
GT TOP Addition                     1.0.0
Lazy AE2                                 1.1.26
LibNine                                   1.2.1

### Environment

Forge Server, zulu-jdk8.0.392

### Mode

Expert Mode

### What Happened

Server initialization was jammed, making no responce for minutes after showing information that loot table "enderio:infinityfluid/minecraft/bedrock" was lost, and re-launching made no difference

### Expected Behavior

Server launched normally

### Logs

https://mclo.gs/BwPNZqG

**Comment by IntegerLimit** [comment]
It seems like your world was previously saved with client mods. Does this issue occur when saving the world as backup and emptying the world folder?

**Comment by MrJefferySmith** [comment]
Actually, I tried to a server based on my old world. I launched the server without the world folder but the server was jammed (related log https://mclo.gs/e8aZYw7 and debug log https://mclo.gs/1EMjUZ1). Then I added my world, and it occurred again (debug log https://mclo.gs/UrjEmZN).  I just emptied that folder and of course it made no difference (log https://mclo.gs/OUxlbJK and debug log https://mclo.gs/O2UfRi8).

**Comment by IntegerLimit** [comment]
Have you tried reinstalling?

**Comment by MrJefferySmith** [comment]
Well, it's just a mistake. In fact it runs quiet well. The terminal was disabled and I failed to find some key logs so I thougt the server jammed.

**Comment by IntegerLimit** [comment]
Ah ok, good to know.
