### ISSUE TITLE
Chlorine Quest not showing up

### ISSUE THREAD

**Issue by MrLuxALot** [Nomi-CEu/Nomi-CEu#1129]
### Nomi CEu Version

1.7.3

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added
Fugue
Scalar
AnvilFix
OreExcevator

### Environment

Cleanroom 0.2.4 alpha
Server

### Mode

Normal Mode

### What Happened

I tried to access the PVC quest but it said the chlorine quest was a requirement. I tried to find it, but couldnt visually and with the search bar. I only found it as I looked up the requirements of the PVC quest with the edit command. I couldn't complete it either without using check_all

### Expected Behavior

See the chlorine quest and complete it

### Reproduction Steps

Look at the quest book and try to find the Chlorine quest

**Comment by MrLuxALot** [comment]
i fixed it by adding it to the group and place it somewhere, so easy fix ig

**Comment by IntegerLimit** [comment]
Already fixed in Nightly, in https://github.com/Nomi-CEu/Nomi-CEu/commit/cbd9b9f6a49748a894c78252d50733911820c051.
