### ISSUE TITLE
items disappeared from me system

### ISSUE THREAD

**Issue by imgshaver** [Nomi-CEu/Nomi-CEu#1148]
### Nomi CEu Version

1.7.3

### Launcher

Curseforge

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

I had a bunch of items disappear from my ME system. I had a large amount of aqua regia and platinum group metal in my me system. I set up a large centrifuge with an Me input hatch taking in aqua regia and the me input bus taking platinum group metal and an me output bus, all connected to the ME system.

### Expected Behavior

Expected to have the platinum group outputs. However, none the platinum group outputs were in the me system.

**Comment by D-Alessian** [comment]
This seems like user error more than an actual bug. Check the ME output bus, check your system thoroughly, check if the recipe actually even started. I really doubt this would happen. And if it did it would need way more info on how to reproduce it.
