### ISSUE TITLE
Energy hatches sometimes stop receiving power after teleporting into dimension

### ISSUE THREAD

**Issue by Jellonator** [Nomi-CEu/Nomi-CEu#1158]
### Nomi CEu Version

1.7.3

### Launcher

ATLauncher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

When loading into a dimension (e.g. /home or using a cake), some of my multiblocks sometimes stop receiving power.
Whether or not this happens seems to be random, as it does not always occur, but it's likely there's something else underlying the issue.

I recorded a video of this happening:

https://github.com/user-attachments/assets/24c36bfa-f60f-4eda-89e1-f29f63777427

In the video I run around a bunch, as a sort of 'rain dance' to try and get the bug to occur (though maybe I'm being superstitious). I had recorded four prior videos of it not occuring doing roughly the same thing, though I spend much less time in the overworld in those attempts.

I can 'fix' the issue by disconnecting and reconnecting the wire from the energy hatch.

### Expected Behavior

The hatch should receive power as normal when loading the world.

### Reproduction Steps

1. Have a multiblock that is receiving power
2. Teleport to a different dimension
3. Walk around a  bunch
4. Teleport back into original dimension

### Additional Information

4GB RAM allocated to Minecraft (out of 32GB available)
Running on (Arch) Linux, kernel version 6.12.4 (64-bit)

**Comment by IntegerLimit** [comment]
Are you chunks chunkloaded?

**Comment by Jellonator** [comment]
My chunks were not chunk-loaded. I moved most of my stuff to a void world, and I didn't think to set it up in the void world yet.
This will probably fix it, but I do wonder if it is possible for this bug to occur when first loading the world (though I don't think I have encountered the bug in this specific scenario yet).

**Comment by IntegerLimit** [comment]
I would assume its related to dimensions not loading tile entities in correct order or related. Chunkloading should prevent this issue.
