### ISSUE TITLE
Therman Expansion Energy cell(Creative) doesn't have a recipe

### ISSUE THREAD

**Issue by Ethanedc** [Nomi-CEu/Nomi-CEu#1159]
### Nomi CEu Version

1.7.3

### Launcher

CurseForge

### Environment

SinglePlayer

### Mode

Normal Mode

### What Happened

The item has no recipe and you cant craft it

### Expected Behavior

Craft the item

### Logs

[crafttweaker.log](https://github.com/user-attachments/files/18214690/crafttweaker.log)
[latest.log](https://github.com/user-attachments/files/18214694/latest.log)

**Comment by D-Alessian** [comment]
https://github.com/Nomi-CEu/Nomi-CEu/issues/1089
https://github.com/Nomi-CEu/Nomi-CEu/pull/1127

**Comment by IntegerLimit** [comment]
Closed as duplicate.
