### ISSUE TITLE
Can you add the zh_cn.lang file to your modpack

### ISSUE THREAD

**Issue by IAmNotGEM** [Nomi-CEu/Nomi-CEu#164]
https://github.com/IAmNotGEM/Nomifactory-GTCEu-Port---zh_CN/blob/master/zh_cn.lang

**Comment by tracer4b** [comment]
It is better to distribute these as resource packs, because then you can make edits to the translation file without going through me.  
If you make this into a resource pack, I will display it on the CF and Github page

**Comment by Folanlron** [comment]
Stale
