### ISSUE TITLE
Suggestion: Add "More Sound Config" Mod

### ISSUE THREAD

**Issue by Carterpersall** [Nomi-CEu/Nomi-CEu#216]
https://www.curseforge.com/minecraft/mc-mods/more-sound-config

This mod adds a setting that lets the player choose the sound device that Minecraft will use, which is extremely useful for people who change audio devices often and don't want to restart their game every time.

**Comment by Caedis** [comment]
Its a client side only mod, just add it to your instance.

**Comment by IntegerLimit** [comment]
I don't feel like this mod is needed in the public pack. However, as Caedis said, you can simply add it to your pack.

**Comment by IntegerLimit** [comment]
Implemented by https://github.com/Nomi-CEu/Nomi-CEu/pull/478.
