### ISSUE TITLE
Config switching .bat doesn't affect difficulty on server pack

### ISSUE THREAD

**Issue by Correlander** [Nomi-CEu/nomi-ceu#241]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.5

**Description:**
Hardmode in server pack is not locked peaceful. Can be manually changed, but for someone who is installing this without prior knowledge hardmode should be locked on peaceful, they would be oblivious.
I'm on Windows, so doing this with the ".bat". I am unsure if there is an issue with the linux counterpart.

**Expected Behavior:**
Server, once set to hardmode, would be peaceful.

**Steps To Reproduce:**
Download server pack. Use swap cfg .bat to change to hardmode. Launch and join server. Won't be on peaceful, because serverproperties.txt hasn't changed.

**Crash Log:**
N/A

**Screenshots:**
N/A

**Comment by 0xC4DE** [comment]
I think I've found the bug.

The (probably) answer: It's an issue with difficulty lock. In the source code, it hooks into onWorldLoad. But a server's server.properties also hooks into onWorldLoad, serving the difficulty to the client every time they load into a dimension. This is seen in the method `handleServerDifficulty` where `packetIn.getDifficulty()` is used which boils down to this call `nbt.getByte("Difficulty")`.

Well forge doesn't care about all that and overwrites the vanilla get difficulty behavior ONLY on dedicated servers.
`this.settings.getIntProperty("difficulty", EnumDifficulty.NORMAL.getDifficultyId())` (default is NORMAL difficulty)

**Comment by 0xC4DE** [comment]
After further review, I honestly cannot find a fix for this without directly modifying server.properties. Maybe simply setting difficulty to 0 and excluding difficulty lock should be a part of the pack-converter. I will make a merge for that since it's borderline trivial.
