### ISSUE TITLE
Ore Drilling Plant Controller being deleted

### ISSUE THREAD

**Issue by Correlander** [Nomi-CEu/Nomi-CEu#244]
Note: if you need general tech support for things like server configuration, Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

**Pack Version:**
1.5

**Description:**
Phantom Breaker + Placer swapping out the controller block of an ore drilling plant deletes it (occasionally). As in,  a phantom breaker  on pulse mode will break the controller on a redstone timer (2400 ticks but that shouldn't matter). Item conduits then immediately feed it back into an auto placer, on deactivation mode (always on, unless redstone signal, which there is none so just always on). I noticed my controller block disappeared one day, so I spawned a stack of controllers in, put them in the placer, and waited 48 hours. Upon checking again, this is far less than a stack, so it's definitely deleting them on occasion. The area is chunk loaded. If it matters it's on a space station biome.
![2023-02-07_22 52 11](https://user-images.githubusercontent.com/53982700/217437308-d5ceed47-3bd1-44c5-b6ab-e84947f84826.png)
![2023-02-07_22 52 20](https://user-images.githubusercontent.com/53982700/217437313-456ca77d-68d0-448b-b2b0-06de2f2e0f2f.png)
![2023-02-07_22 52 41](https://user-images.githubusercontent.com/53982700/217437321-ae0f054c-9b8a-4034-8cf6-9cafae853977.png)
![2023-02-07_22 52 49](https://user-images.githubusercontent.com/53982700/217437328-8184c492-2ae9-4f90-9248-4126b781a75c.png)

**Expected Behavior:**
For it to not delete the controller unit.

**Steps To Reproduce:**
Do the setup I described in description section, and wait (a long time, so sorry for whoever tries to reproduce this lol). Also, it does matter probably, it is placing the controller into what is otherwise a complete ore drilling plant. So it's forming and un-forming mutliblock every time it places/breaks. Also, auto placer always faces the controller with its textured face pointing north. So you would need to setup your drill to be oriented with that properly.

**Crash Log:**
N/A

**Screenshots:**
Sent above.

**Comment by IntegerLimit** [comment]
Um, probably a GTCEu issue. Try reporting to https://github.com/GregTechCEu/GregTech/issues. Also, why were you auto-placing and breaking the controller?

**Comment by Folanlron** [comment]
They are using the Drilling Rig to maximize ore production..

Every time the Rig is "done" the controller has to be picked up and placed back down to reset it's search parameters.

**Comment by Correlander** [comment]
Sent it to GTCEu. If they send it to AA, I will do so as well.

**Comment by IntegerLimit** [comment]
Thanks!

**Comment by trainvoi** [comment]
From my experience with this setup, the ore drilling plant isn't deleted, it's getting replaced the last GT block with id gregtech:machine placed. So if your last placed GT gregtech:machine block is placed (could be a MV macerator, or a steel drum), the autoplacer will put that block instead of drilling plant.

**Comment by Correlander** [comment]
> From my experience with this setup, the ore drilling plant isn't deleted, it's getting replaced the last GT block with id gregtech:machine placed. So if your last placed GT gregtech:machine block is placed (could be a MV macerator, or a steel drum), the autoplacer will put that block instead of drilling plant.

No I tested it actually is deleting them, though it has also done what you said where it makes duplicates of machines I've placed. Seems to function very oddly in general.

**Comment by IntegerLimit** [comment]
I have no idea, but this now seems more like an AA Issue.

**Comment by Folanlron** [comment]
You will be able to "reset" Mining Logic on Drilling Rigs with a rubber hammer in the next GTCEu..

No more needing to break/replace blocks

**Comment by Folanlron** [comment]
Fixed via, https://github.com/Nomi-CEu/Nomi-CEu/pull/452

You can now simply hit the Miner Controller with a Soft mallet to reset the logic
