### ISSUE TITLE
Scrolling while hovering over a GT hammer has the cursor pick it up rather than transferring it to an inventory

### ISSUE THREAD

**Issue by Dr-Turtle** [Nomi-CEu/Nomi-CEu#251]
**Pack Version:**
1.5
Added mods: optifine

Changed configs: [rubber crafting recipe fix](https://github.com/tracer4b/nomi-ceu/issues/201#issuecomment-1401475665)

**Description:**
GT hammer gets picked up by cursor when scrolling on the item

**Expected Behavior:**
GT hammer should be moved into the open inventory/crafting bench like how all other tools (at least those i've tested) and items do (This issue only bothers me in crafting tables where shift-clicking cannot be used in place of scrolling).

**Steps To Reproduce:**
1. craft a GT hammer (I used steel, but I don't think that matters), using JEI to spawn a hammer does not cause this issue
2. open a chest (all the inventories I've tested have the same behavior, including crafting tables and player inventory crafting grid)
3. scroll down while hovering over GT hammer (might need to scroll up if your scrolling direction is different than mine)

**Comment by IntegerLimit** [comment]
Test again in 1.5.1 once that's released.

**Comment by IntegerLimit** [comment]
Does this happen in 1.5.1? Can you transfer this issue to GTCEu?

**Comment by Dr-Turtle** [comment]
> Does this happen in 1.5.1? Can you transfer this issue to GTCEu?

This still happens in 1.5.1, I did some additional testing, and when only GTCEu, Mouse Tweaks, and CodeChickenLib (using the same versions as Nomifactory 1.5.1) are loaded, the case I described in the "Steps to Reproduce" works fine, but using scroll wheel to take a hammer out of a crafting table immediately after it was used in a recipe still has this behavior. So I imagine this issue is caused by a mod or config in Nomifactory.

**Comment by IntegerLimit** [comment]
Huh, thanks for the insight. I'll have a look at it. Is it just the hammer, or also other GT Tools, or many other items?

**Comment by Dr-Turtle** [comment]
> Huh, thanks for the insight. I'll have a look at it. Is it just the hammer, or also other GT Tools, or many other items?

I just tested every tool, the crowbar has this issue, and the electric tools are inconsistent (e.g. an HV drill has this issue when at full durability, but works fine after losing some durability)

Spawning tools with JEI appears to never have this problem

**Comment by a-a-GiTHuB-a-a** [comment]
It's probably an NBT problem, as always.

**Comment by v3ect0rgames** [comment]
I checked the nbt data, and the jei and crafted ones have the same nbt

**Comment by IntegerLimit** [comment]
Can't reproduce in current dev.
