### ISSUE TITLE
Terminal cannot be closed due to app popup from App Store

### ISSUE THREAD

**Issue by JuiceyBeans** [Nomi-CEu/Nomi-CEu#274]
**Pack Version:**
1.5.1

**Launcher:**
PrismLauncher 6.3

**Mode:**
Normal Mode

**Environment:**
Singleplayer, Simple World Timer only added

**Description:**
Terminal cannot be closed due to app popup in the App Store not closing (Teleporter pop up in this case)

**Expected Behavior:**
Pressing ESC should close the app popup, pressing ESC again should close the terminal as well.

**Steps To Reproduce:**

1. Open Terminal
2. Go to App Store
3. Click Install for Teleporter app
4. Not sure if this is relevant, but hover over the requirement to install app (UV Field Generator, ZPM Battery)
5. Press ESC/Click the red close button in top right

**Crash Log:**
None

**Note:**
Does not happen always, could not be reproduced after reopening the game after the first time this happened, but it occurred again about two hours later on opening Terminal again

**Comment by Folanlron** [comment]
You can force close the Terminal with ctrl-e 

Might wanna add that to the Terminal info quest..

**Comment by IntegerLimit** [comment]
Please report this to GTCEu. I will add the way to force-close the terminal with ctrl-e to the qb, thank you.

**Comment by IntegerLimit** [comment]
I've mentioned the way to force-exit terminal in the qb. Again, please move this issue to the GTCEu github, so that it can get fixed.

**Comment by Folanlron** [comment]
Stale but is completed *shrug*
