### ISSUE TITLE
Hydrogen and Oxygen bucket turn into Advanced Rocketry Tanks

### ISSUE THREAD

**Issue by An12854** [Nomi-CEu/Nomi-CEu#276]
**Pack Version:**
v1.5.1

**Launcher:**
Prism Launcher

**Mode:**
Normal Mode

**Environment:**
Singleplayer

**Description:**
Hydrogen and Oxygen buckets turn into Advanced Rocketry Tanks, when the fluid is placed it turns into an Advanced Rocketry fluid and turns the bucket into a tank when collected.

**Expected Behavior:**
Probably just evaporate, I don't know the expected behavior.

**Steps To Reproduce:**
Get a bucket of hydrogen or oxygen, place the fluid and collect it again, ends up turning into a tank

**Crash Log:**
(None)

**Screenshots:**
https://imgur.com/32AxDZU

**Comment by IntegerLimit** [comment]
I'm sorry, we can't do anything to fix this, just don't place your hydrogen?
