### ISSUE TITLE
Compatibility script for Fluid Drawers

### ISSUE THREAD

**Issue by supasem** [Nomi-CEu/Nomi-CEu#277]
I always found it frustrating that nomifactory had no way of easily managing fluids without copious amounts of super tanks and fluid storage busses

Over the last month or so, I have been playing with the [fluid drawers mod](https://www.curseforge.com/minecraft/mc-mods/fluid-drawers)
it has greatly improved organization for processing chains and has made fluid storage and interfacing with AE2 a breeze
This mod fits seamlessly with the already existing [storage drawers mod](https://www.curseforge.com/minecraft/mc-mods/storage-drawers), and drawer networks can operate with both types of drawers on the same network. (It even contains framed variants)

Simply add the [fluid drawers mod](https://www.curseforge.com/minecraft/mc-mods/fluid-drawers), and tweak some base stats to balance them with other fluid storage solutions that already exist. Tweak the recipes if needed.

![2023-01-22_22 28 33](https://user-images.githubusercontent.com/122709287/223774805-6edf390b-f24b-489c-8e97-7ca4145be100.png)

![2023-03-07_01 12 24](https://user-images.githubusercontent.com/122709287/223774870-4733f2f1-ab97-4b59-bfc4-fe85c844ee48.png)

**Comment by IntegerLimit** [comment]
I'll have a think of it, and discuss with Exa and tracer.

**Comment by IntegerLimit** [comment]
Okay, this will end up being a compatibility script, similar to Flux Networks, Ae2fc, and Project Red: illumination.

**Comment by IntegerLimit** [comment]
Um, mostly make the recipes harder, and remove any useless items. Honestly, make the PR, and we'll request any recipe or item changes as needed.

**Comment by IntegerLimit** [comment]
It has been decided that if a PR is not made by someone else, this will be done in the attached PR. The reason being, if it was implemented before this PR by me, I would just have to do it again in the PR, which just creates a waste of time.

**Comment by Folanlron** [comment]
This will be super seceded by https://github.com/GregTechCEu/GregTech/pull/1963

As GTCEu is working on it's own Controller for Super Tanks/Chest..
