### ISSUE TITLE
LV robot arm with item filter not properly filtering items 

### ISSUE THREAD

**Issue by 105000907** [Nomi-CEu/Nomi-CEu#278]
Thanks for taking the time to fill out this report! 

Note: if you need general tech support for things like server configuration, or general game support (how to I make this?), Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

Check if the bug is fixed on the latest version before submitting. The latest version is v1.5.1.

**Pack Version:**
v1.5.1

**Launcher:**
Curse Forge

**Mode:**
Hard mode

**Environment:**
Multiplayer dedicated server, deleted the file required to disable forced peaceful.

**Description:**
LV robot arm with an item filter inserted, set to keep exact mode, placed on an item pipe facing an inventory, with an item specified in the whitelist, does not prevent non-whitelisted items from passing through the cover. 

Specifically: I have a conveyor in import mode pulling two different items from a chest into a pipe system. That pipe system has a specific destination for each item (two different chests in my test screenshots). One of those destinations has only a filter to specify the desired item, the other destination has an LV robot arm with an item filter inserted, and the settings mentioned above. When both inventories have space the system works as I would expect, however if the first chest (the one with only the item filter as a cover) has inventory space, then that chest's item type will be forced past he robot arm and into the second inventory.

**Expected Behavior:**
I would expect the robot arm to act as a filter (especially when it has an item filter inserted) and prevent a conveyor from overriding it's whitelist.

**Steps To Reproduce:**
Replace this text with steps to reproduce the behavior, if applicable. We need to know how to encounter this bug ourselves so we can diagnose it.

**Crash Log:**
no crash

**Screenshots:**
1.  ![image](https://user-images.githubusercontent.com/41244286/223786035-49b33885-e641-4ada-af27-9a8a0a50e753.png)
General screenshot. Left chest has a conveyor with the settings seen in #2. Top chest has a filter with settings seen in #3. Right chest has a robot arm with settings seen in #4. When the top chest is empty the system works as expected. When full, cobblestone enters the right chest. In both cases stone in the right chest is still limited to only 64, and when the right chest is full of other items, no stone enters the top chest through it's filter.
2.  ![image](https://user-images.githubusercontent.com/41244286/223786112-00d1ae4c-0c06-4ca0-8698-dae4e8ffae16.png)
3.  ![image](https://user-images.githubusercontent.com/41244286/223790214-f670582b-9f00-41e6-b6e9-e0fd9fa31073.png)
4.  ![image](https://user-images.githubusercontent.com/41244286/223789404-0a485864-4e4b-446d-88b9-e2b4802f74fb.png)

**Comment by 105000907** [comment]
Apologies I did not realize writing #.1/2/3/4 would link to other threads :p. I was just meaning to refer to my other screenshots.

**Comment by IntegerLimit** [comment]
Oops, accidentally closed this.

**Comment by Folanlron** [comment]
Fixed via update to CEu 2.7.4
