### ISSUE TITLE
server crash 1.5.2

### ISSUE THREAD

**Issue by GlitxhSenpai** [Nomi-CEu/nomi-ceu#289]
Thanks for taking the time to fill out this report! 

Note: if you need general tech support for things like server configuration, or general game support (how to I make this?), Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

Check if the bug is fixed on the latest version before submitting. The latest version is v1.5.2.

**Pack Version:**
1.5.2

**Launcher:**
Replace this text with your launcher. If you are using the CurseForge Launcher, please try to see if the issue applies on a different launcher. 

**Mode:**
Replace this text with your mode (Normal Mode, Hard Mode or Both Modes).

**Environment:**
multiplayer, linux server

**Description:**
server crashes on initial startup server is freshly created tried twice from a fresh zip, crashes due to advanced rocketry, no clue how to fix it

**Expected Behavior:**
Replace this text with a clear and concise description of what the correct behavior would be.

**Steps To Reproduce:**
Replace this text with steps to reproduce the behavior, if applicable. We need to know how to encounter this bug ourselves so we can diagnose it.

**Crash Log:**
https://textbin.net/fqybainqar

**Screenshots:**

**Comment by IntegerLimit** [comment]
Launcher?

**Comment by IntegerLimit** [comment]
Um... it seems that Armor Plus is causing this issue. Does this happen before 1.5.2, like 1.5?

**Comment by 0xC4DE** [comment]
+1 to Integer, Armor Plus is definitely causing the issue. We would appreciate some more context, does this crash happen on a fresh world?

**Comment by IntegerLimit** [comment]
Stale, and can't reproduce.
