### ISSUE TITLE
No Fluid Ruridit in 1.5.2

### ISSUE THREAD

**Issue by Grobes** [Nomi-CEu/nomi-ceu#295]
**Pack Version:**
v1.5.2

**Launcher:**
Curseforge

**Mode:**
Normal Mode

**Environment:**
Singleplayer

**Description:**
At some point in the past 1-2 patches I seem to no longer have Ruridit as a fluid. I'm in the post Creative Tank period.
I know I must have had Ruridit as a fluid at some point as I have large amounts of passively made Sheets and Long-Rods, but my ingots and wire have now run out.

**Expected Behavior:**
I'm not sure if removing Fluid Ruridit was intended as I couldn't find any mention in the changelog.
I can work around it by pulverising, mixing and blast furnacing its precursors but that is a lot of extra steps for post Creative Tank.

**Steps To Reproduce:**
Look for Fluid Ruridit in 1.5.2

**Crash Log:**
N/A

**Screenshots:**
N/A

**Comment by IntegerLimit** [comment]
Looking at it.

**Comment by IntegerLimit** [comment]
Try another launcher. CurseForge Launcher is weird, you could use Prism Launcher instead. If the fluid still doesn't show up, please comment again.

**Comment by IntegerLimit** [comment]
Its a GTCEu problem. Will be fixed next update.

**Comment by IntegerLimit** [comment]
fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/e50d68415b3352ff5bf10bcbcd6a9d230019a8ed.
