### ISSUE TITLE
[1.5.x] Item deletions related to GTC machines, export buses, and interfaces.

### ISSUE THREAD

**Issue by 0xC4DE** [Nomi-CEu/Nomi-CEu#296]
I host a private Expert mode server on 1.5.2. I have a system that uses a fuzzy export bus into an actually additions crate for ore processing. This bug has also occurred while exporting hot ingots into an input bus. IT is unclear if this is related to importing using an interface or exporting using the bus

They *seem* to work properly while logged in, for the most part (it can export rather slowly with fuzzy, it doesn't read AA crates properly I think), while logged out (and chunk loaded), they seem to void items. It is notable that this could be the interface or the export bus, but I have not figure out which just yet.

To replicate, have a simple ME system on a server, make that system export into any container that cannot fit all of the items, log out with it chunk loaded and wait, when you log in you will notice many of the items are gone.

If that does not work, replicate the setup but exporting into a machine that processes the items and goes back into the system using an interface (cobble -> hammer -> interface) you will notice the results not going into the system (probably)

There is possibility my storage bus on a bunch of locked storage drawers is causing this to some extent. but unsure. I have no trashcans on my AE2 network, especially not with a storage bus.

**Comment by 0xC4DE** [comment]
I'm a silly goose, this is a problem with AE2 

See: https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/213

**Comment by IntegerLimit** [comment]
Great. Thank you for moving it there.

**Comment by Folanlron** [comment]
Just doing some clean-up don't mind me..
