### ISSUE TITLE
Missing gas recipies in JEI

### ISSUE THREAD

**Issue by Caerglad** [Nomi-CEu/nomi-ceu#307]
**Pack Version:**
1.5.2

**Launcher:**
CurseForge

**Mode:**
Normal Mode

**Environment:**
SSP

**Description:**
Hydrogen, Oxygen, Nitrogen are missing when typed in JEI search, only plasma and condensed versions of them show up. There is "bucket" item, but no "square" one.

**Expected Behavior:**
All regular gases show up in JEI when searched

**Steps To Reproduce:**
Just type name of one of those three gases (I haven't encounter this issue on other gases yet) in JEI

**Crash Log:**
N/A

**Screenshots:**
![image](https://user-images.githubusercontent.com/1807505/229901771-653d1908-b42f-4424-bb21-c7e69fa757da.png)

**Comment by Caerglad** [comment]
Missing texture on the screenshot is Nitrogen from Advanced Rocketry, it has uses but no recipe to craft it

**Comment by IntegerLimit** [comment]
Hmm... I believe this cannot be fixed, but I will have a look at it.

**Comment by Folanlron** [comment]
This is because AR thinks its a special child, somehow it overwrites all instance of O/N/H in the game, with its own version.

You have to use the "bucket" version for setting interfaces.. Its been this way for awhile and nobody wants to fix it sense AR is well AR.

**Comment by IntegerLimit** [comment]
Cannot be fixed.
