### ISSUE TITLE
ULV Hulls take Red Alloy cables in Assembler instead of Lead cables they take normally

### ISSUE THREAD

**Issue by mateskr692** [Nomi-CEu/nomi-ceu#308]
**Pack Version:**
1.5.2

**Launcher:**
Prism launcher

**Mode:**
Hard Mode

**Environment:**
Singleplayer

**Description:**
Every machine Hull can be made either in a crafting table recipe or in Assembler recipe, in both cases they take the same cable. Except for the ULV Hull which takes Lead cables in normal recipe but red alloy cables in Assembler recipe

**Screenshots:**
Crafting table recipe:
![image](https://user-images.githubusercontent.com/32541962/230286725-7a25205e-50ff-45dc-bae6-8f00333e0bc7.png)
 Assembler recipe:
![image](https://user-images.githubusercontent.com/32541962/230286824-d13ad119-6736-4c16-8eb2-42121dd05f46.png)

**Comment by IntegerLimit** [comment]
This a GTCEu problem. Please report to https://github.com/GregTechCEu/GregTech/issues.

**Comment by IntegerLimit** [comment]
I was mistaken, this in fact is an issue on our end. Fixing soon.
