### ISSUE TITLE
Server Crash when using Silk Touch on Assembling Line block

### ISSUE THREAD

**Issue by Fewshin** [Nomi-CEu/nomi-ceu#309]
Server crashed when I tried to collect the assembling line block using a silk touch diamond pickaxe. I'm using version 1.5.2.
[crash-2023-04-07_19.29.06-server.txt](https://github.com/Nomi-CEu/nomi-ceu/files/11182305/crash-2023-04-07_19.29.06-server.txt)

**Comment by Folanlron** [comment]
Well be fixed with next CEu release, which released, if you want to get around the error for now, break the Assembly Line Controller block in Creative mode and the game will not crash..

**Comment by IntegerLimit** [comment]
fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/e50d68415b3352ff5bf10bcbcd6a9d230019a8ed.
