### ISSUE TITLE
1.6 crash on startup with existing world

### ISSUE THREAD

**Issue by Dabvexx** [Nomi-CEu/nomi-ceu#311]
**Pack Version:**
1.6

**Launcher:**
ATLauncher

**Mode:**
normal

**Environment:**
singleplayer

**Description:**
Minecraft crashes and freezes immediately when starting an existing world 

**Expected Behavior:**
loading into the world without a crash

**Crash Log:**
[crash-2023-04-08_12.40.26-server.txt](https://github.com/Nomi-CEu/nomi-ceu/files/11183702/crash-2023-04-08_12.40.26-server.txt)

**Comment by IntegerLimit** [comment]
fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/704515e5a8a73b3e2dbea4fc31944002e505ba27
