### ISSUE TITLE
1.6 issues, so far

### ISSUE THREAD

**Issue by Folanlron** [Nomi-CEu/nomi-ceu#312]
**Pack Version:**
1.6

**Launcher:**
MMC - Custom

**Mode:**
Hard Mode

**Environment:**
Single Player

**Description:**

Canola Oil can no longer be made, "canola" only turns into Seed Oil now, the recipe for Cyrstalized/Empowered is still available but not being able to make basic Canola Oil makes them useless.
Black Steel, NBT Strikes again..
Wiremill changes, with the ability to Circuit the Wiremill now the Wiremill Factory needs distinct bus mode available from GCYM in order to work properly.

https://github.com/Nomi-CEu/nomi-ceu/issues/311
This issue is due to having EnderIO conduits near a maintenance hatch front side, probably has something to do with recent changes to the maintenance hatch, as even in my world TOP reports that the block is "default" see attached SS(I do not have EnderIO Conduits anywhere on my world) the hatch its self still works though, just don't place a Conduit near it.

![2023-04-08_11 36 20](https://user-images.githubusercontent.com/1880741/230739997-8839879b-7008-41d0-a026-e75aa87df00a.png)

**Comment by IntegerLimit** [comment]
This is great. Thanks! (Black Steel Strikes Again!)

**Comment by IntegerLimit** [comment]
Canola oil seems fine...

**Comment by Folanlron** [comment]
Couldn't get canola to work at all, course I only had about 10mins of time to play before I had work meetings I'll look into more tonight when i get time...

**Comment by IntegerLimit** [comment]
Ok, thank you.

**Comment by Folanlron** [comment]
So after tech made a point that there are actually several problem in GTCEu right now, recipes not loading correctly, machine animation/sounds not loading correctly etc etc, He did say he has a pull request in to hopefully fix the issues.

**Comment by mateskr692** [comment]
On hardmode, distillation tower requires Iridium quest
![image](https://user-images.githubusercontent.com/32541962/230758291-46f7b51d-240e-4e62-b1bb-8a487c4669ac.png)
