### ISSUE TITLE
Make it clearer why Tier 2 micro miner quest requires boron

### ISSUE THREAD

**Issue by haydedanny** [Nomi-CEu/nomi-ceu#313]
**Pack Version:**
1.6

**Launcher:**
Curseforge

**Mode:**
Normal Mode

**Environment:**
Both

**Description:**
The Tier 2 Micro Miner quest found in the Mid Game section requires obtaining boron, even though you do not need to use boron for the micro miner.

**Expected Behavior:**
It should not require the boron quest.

**Steps To Reproduce:**
Open up a new world, and check the Mid Game quest page and hover over the quest.
![boron](https://user-images.githubusercontent.com/99454127/230744157-541e29e8-80f5-4820-8e02-a2e03c72844b.png)

**Comment by IntegerLimit** [comment]
This is working as intended, as the field generators of the tier two micro miner requires the mv superconductor, which requires boron. However, I will make it clearer in the quest what boron is used for.

**Comment by haydedanny** [comment]
The MV field generator is for the tier 3 micro miner though, but the tier 2 only needs the LV field generator

**Comment by IntegerLimit** [comment]
Yeah, the LV Field needs boron I believe. I wrote it wrong in my previous comment. Can you check if the LV Field needs boron?

**Comment by haydedanny** [comment]
It only requires manganese phosphide wire, so no boron is required.

**Comment by IntegerLimit** [comment]
You are correct.
