### ISSUE TITLE
Main Menu screenshots not loading on case sensitive filesystems

### ISSUE THREAD

**Issue by DavidDieLandGurke** [Nomi-CEu/nomi-ceu#314]
**Pack Version:**
1.6

**Launcher:**
Prism Launcher

**Mode:**
Tested on Normal mode, most likely still an issue on Expert though

**Environment:**
Linux Mint 21.1 Singleplayer

**Description:**
The Main Menu background gets replaced by the 'missing texture' pattern like shown in the screenshot.
This happens because the game looks for the files in all lowercase for some reason and on a case sensitive file system like I have on Linux that leads to the file not being found since the Screenshots do have uppercase letters in their names.
To fix all that needs to be done is renaming the screenshot files to be all lowercase.

**Expected Behavior:**
The Main Menu should show the new screenshots in the slideshow instead of the missing texture

**Steps To Reproduce:**
Run the 1.6 version of the Pack on a case sensitive Filesystem (e.g. ext4)

**Screenshots:**
![image](https://user-images.githubusercontent.com/61883039/230745220-7fbc547e-46d7-43e8-99df-4d5beb0192a2.png)

**Comment by IntegerLimit** [comment]
[nomi-ceu-client.zip](https://github.com/Nomi-CEu/nomi-ceu/files/11184552/nomi-ceu-client.zip)
Can you see if this fixes the problem @DavidDieLandGurke ?

**Comment by DavidDieLandGurke** [comment]
> [nomi-ceu-client.zip](https://github.com/Nomi-CEu/nomi-ceu/files/11184552/nomi-ceu-client.zip) Can you see if this fixes the problem @DavidDieLandGurke ?

That did fix it indeed. Thanks for the swift fix, even though i had already fixed it on my own instance haha
