### ISSUE TITLE
1.6 conflicting mod files in folder

### ISSUE THREAD

**Issue by Dabvexx** [Nomi-CEu/nomi-ceu#315]
**Pack Version:**
1.6

**Launcher:**
ATLauncher

**Description:**
gregtech-1-12-2-2.5.4-beta-patched.jar and gregtech-1.12.2-2.6.0-beta.jar are in the mods folder at the same time, making it so you have to delete gregtech-1-12-2-2.5.4-beta-patched.jar for the game to actually start.

**Expected Behavior:**
having just gregtech-1.12.2-2.6.0-beta.jar in the mods folder.

**Steps To Reproduce:**
- Update / install Nomifactory from ATLauncher(? Could be other launchers as well)
- try to open minecraft

**Screenshots:**
![image_2023-04-08_210531153](https://user-images.githubusercontent.com/62082196/230749034-3f7aa54b-e9c2-4eff-bd65-358e506a3a18.png)
![image_2023-04-08_210558301](https://user-images.githubusercontent.com/62082196/230749048-aa9b06f3-f5f9-4744-908c-89fd20ff28ad.png)

**Comment by IntegerLimit** [comment]
You are updating your instance. If you create a new instance and copy over relevant files (you can use https://github.com/IntegerLimit/nomifactory-migrator to do so), then this issue will not happen.
