### ISSUE TITLE
Packaging machines no longer compact nuclearcraft tiny clumps

### ISSUE THREAD

**Issue by BlakeTech** [Nomi-CEu/nomi-ceu#317]
**Pack Version:**
1.6

**Launcher:**
Curseforge

**Mode:**
Normal

**Environment:**
Multiplayer, + crayfish furniture + supported extra mods with the custom recipes given

**Description:**
Compacting machines does not compact tiny nuclearcraft materials despite recipes in HEI + circuit given.

**Expected Behavior:**
Compacting machines compacts tiny nuclearcraft materials as shown by recipes in HEI + circuit given.

**Steps To Reproduce:**
Put tiny nuclearcraft dust itmes in, ex: Plutonium 242. Watch it not compact, regardless of it being the multiblock or the single block.

**Crash Log:**
If your client crashed as a result of this bug, please upload the generated crash log. This is found in your launcher's Nomifactory CEu profile (aka instance) in a folder called `crash-reports`. If there was no crash, but instead an error screen, please upload your `latest.log` instead.

**Screenshots:**

![2023-04-08_19 13 06](https://user-images.githubusercontent.com/16453726/230750693-1eb52e49-3be8-4a31-b27a-73d04c541088.png)

**Comment by Folanlron** [comment]
This is part of a bigger problem currently in the CEu branch.. and be fixed by

https://github.com/GregTechCEu/GregTech/pull/1690

**Comment by IntegerLimit** [comment]
No need to transfer to GTCEu.

**Comment by BlakeTech** [comment]
> No need to transfer to GTCEu.

What do you mean by this? I was under the impressioin that GTCEu was a standalone mod, whereas Nomi was a modpack that used/is based around GTCEu.

On an unrelated note, might I also ask what happened to the aeadditions branch? I noticed it got deleted.

**Comment by Folanlron** [comment]
> > No need to transfer to GTCEu.
> 
> What do you mean by this? I was under the impressioin that GTCEu was a standalone mod, whereas Nomi was a modpack that used/is based around GTCEu.


Because CEu already knows about the problems, as the devs are in the discord..

**Comment by BlakeTech** [comment]
> > > No need to transfer to GTCEu.
> > 
> > What do you mean by this? I was under the impressioin that GTCEu was a standalone mod, whereas Nomi was a modpack that used/is based around GTCEu.
> 
> 
> Because CEu already knows about the problems, as the devs are in the discord..
> 
> 

Ah, no need to transfer the report over to GTCEu, got it.

Another aside, does the patch above that got merged fix tanks taking in other fluids despite being locked, as well as not showing the locked fluid when empty? 

I understand it should be best submitted under a different bug report, but given that the patch was in discussion I thought it best to confirm with you to see if it was also a known bug and if not, I can go submit another issue over there instead.

**Comment by IntegerLimit** [comment]
> > No need to transfer to GTCEu.
> 
> What do you mean by this? I was under the impressioin that GTCEu was a standalone mod, whereas Nomi was a modpack that used/is based around GTCEu.
> 
> On an unrelated note, might I also ask what happened to the aeadditions branch? I noticed it got deleted.

The ae additions addon script will be implemented in https://github.com/Nomi-CEu/nomi-ceu/pull/291.

**Comment by IntegerLimit** [comment]
fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/704515e5a8a73b3e2dbea4fc31944002e505ba27

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/6ed7e2528a1f662fde084a457690165f77602f97.
