### ISSUE TITLE
Significant FPS drop since the update

### ISSUE THREAD

**Issue by felix-schneider** [Nomi-CEu/nomi-ceu#319]
**Pack Version:**
1.6

**Launcher:**
MCLauncher

**Mode:**
Hard Mode

**Environment:**
Singleplayer, added LazyAE2

**Description:**
After the update, I am getting significantly lower FPS. Possibly because of the new Quantum chests? There are about 30 in the base, although they are on the other end from where the screenshot was taken.

**Screenshots:**

1.5.2:
![2023-04-09_20 38 40](https://user-images.githubusercontent.com/208336/230790931-8d0dd966-53cd-41e4-b315-29eef86dcda1.png)

1.6.0
![2023-04-09_20 17 56](https://user-images.githubusercontent.com/208336/230790939-47496e0f-ed4f-4f33-9999-90085b06c444.png)

**Comment by Folanlron** [comment]
It's not the chests its a combination of several problems that are in CEu..

I would strongly recommend downgrading to 1.5.2 till 1.6.1 is ready..

**Comment by IntegerLimit** [comment]
I would recommend not playing on 1.6 for the time being.

**Comment by IntegerLimit** [comment]
Closed with the GTCEu update commit.
