### ISSUE TITLE
Rebalance Wiremill Recipe Durations

### ISSUE THREAD

**Issue by EpicPuppy613** [Nomi-CEu/Nomi-CEu#320]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently, (for a 3s base material) the wiremill would take 3 seconds to make 2 1x wires, but 6 seconds to make a 2x wire. Recipe durations should be rebalanced to either take 6 seconds to make 2 1x wires, or 3 seconds to make 1 2x wire.

**Describe how the solution will work**
For all wiremill recipes, the durations would be changed to either make 2x (and above) wires quicker to make, or 1x wires to take longer to make.

**Describe alternatives you've considered**
To just make 1x wires instead of 2x wires, but for consistency, it would be better if the wiremill durations scaled based on material amount, instead of wire thickness.

**Comment by IntegerLimit** [comment]
This would be changed in GTCEu. Please report there instead.

**Comment by Folanlron** [comment]
Closing this as this would be a CEu problem.
