### ISSUE TITLE
Crash after placing circuit assembler in cleanroom

### ISSUE THREAD

**Issue by arhimmel** [Nomi-CEu/nomi-ceu#322]
**Pack Version:**
1.6

**Launcher:**
Prism Launcher

**Mode:**
Normal

**Environment:**
Multiplayer

**Description:**
Placed a HV circuit assembler in a clean room.  Pressed on auto output items and the server crashed and does not restart.

**Expected Behavior:**
It should not crash

**Steps To Reproduce:**
Cannot open the world

**Crash Log:**
[crash-2023-04-10_04.06.51-server.txt](https://github.com/Nomi-CEu/nomi-ceu/files/11187562/crash-2023-04-10_04.06.51-server.txt)

**Screenshots:**

**Comment by IntegerLimit** [comment]
Um, GTCEu problem.

**Comment by IntegerLimit** [comment]
Um... it doesn't look like your game is crashing because of the circuit assembler. What do you have at block position -241,72,266?

**Comment by IntegerLimit** [comment]
Might be fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/704515e5a8a73b3e2dbea4fc31944002e505ba27, not sure though. Please check to see if the bug still occurs on 1.6.1, when that comes out.
