### ISSUE TITLE
Crash when loading save game from 1.5.2

### ISSUE THREAD

**Issue by dustinpedlar** [Nomi-CEu/nomi-ceu#325]
**Pack Version:**
1.6

**Launcher:**
PolyMC 5.1

**Mode:**
Both Modes

**Environment:**
Singleplayer

**Description:**
Gregtech CEU version 2.6.0 has a bug where the maintenance hatch has a null itemInventory in the maintenance hatch and any enderIO item conduit that is running past one or was connected to one causes a item tick crash with a null reference when loading the world.

Upgrading to Gregtech CEU 2.6.1 resolved the issue

**Comment by TheKoci** [comment]
This is known and closed as a GTCEu problem, in #311 and #312.
