### ISSUE TITLE
launch.sh uses CRLF (\r\n) on Curseforge

### ISSUE THREAD

**Issue by kanadaj** [Nomi-CEu/nomi-ceu#326]
**Pack Version:**
v1.6

**Launcher:**
itzg/docker-minecraft-server:java8

**Mode:**
Normal

**Environment:**
Server

**Description:**
It appears that the launch.sh from the build uses Windows style line endings (CRLF), so it's not handled correctly on Linux

**Expected Behavior:**
launch.sh should use LF only

**Steps To Reproduce:**
1. Download server files from https://www.curseforge.com/minecraft/modpacks/nomi-ceu/download/4480754
2. Extract to a folder
3. Open launch.sh in a text editor, eg VS Code and check line endings
4. Try using this file to launch a server on Linux

**Crash Log:**
```
/data/FeedTheBeast/launch.sh: line 2: $'\r': command not found
/data/FeedTheBeast/launch.sh: line 10: $'\r': command not found
/data/FeedTheBeast/launch.sh: line 14: $'\r': command not found
/data/FeedTheBeast/launch.sh: line 18: $'\r': command not found
/data/FeedTheBeast/launch.sh: line 21: $'\r': command not found
Checking java version...
/data/FeedTheBeast/launch.sh: line 23: $'echo\r': command not found
Unrecognized option: -version
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
/data/FeedTheBeast/launch.sh: line 25: $'echo\r': command not found
The expected java version is 1.8. Not higher, not lower.
/data/FeedTheBeast/launch.sh: line 27: $'echo\r': command not found
/data/FeedTheBeast/launch.sh: line 28: $'\r': command not found
Launching the server...
/data/FeedTheBeast/launch.sh: line 30: $'echo\r': command not found
> java -server -Xms2048M -Xmx2048M -Dlog4j.configurationFile=log4j2_112-116.xml -Dfml.queryResult=confirm -jar forge-1.12.2-14.23.5.2860.jar nogui
/data/FeedTheBeast/launch.sh: line 32: $'\r': command not found
Invalid initial heap size: -Xms2048M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
/data/FeedTheBeast/launch.sh: line 34: $'\r': command not found
/data/FeedTheBeast/launch.sh: line 35: $'echo\r': command not found
- The server has stopped. If it's a crash, please read the output above.
/data/FeedTheBeast/launch.sh: line 37: $'echo\r': command not found
/data/FeedTheBeast/launch.sh: line 38: read: `_': not a valid identifier
2023-04-13T11:40:59.543Z WARN mc-server-runner Minecraft server failed. Inspect logs above for errors that indicate cause. DO NOT report this line as an error. {"exitCode": 1}
2023-04-13T11:40:59.543Z INFO mc-server-runner Done
```

**Comment by 0xC4DE** [comment]
For the time being check out the `dos2unix` utility, I will fix this whenever I get the chance. 

The reason this happened is because the entire repo is CRLF so it ends up being real bad and I end up rewriting the repo on commit (sometimes)

**Comment by 0xC4DE** [comment]
Actually, after reviewing the file, seems like it pulls as \LF

the tutorial does say:
```
Run curl -O https://raw.githubusercontent.com/Nomi-CEu/nomi-ceu/main/pack-mode-switcher.sh to download the file.
```

It's possible that @tracer4b packages/builds everything on windows, making it so that line endings get converted. I think the best course of action as of now would be removing the files from the packaging, requiring users to pull it instead. Feedback welcome.

**Comment by 0xC4DE** [comment]
Actually, after reviewing the file, seems like it pulls as \LF

the tutorial does say:
```
Run curl -O https://raw.githubusercontent.com/Nomi-CEu/nomi-ceu/main/pack-mode-switcher.sh to download the file.
```

It's possible that @tracer4b packages/builds everything on windows, making it so that line endings get converted. I think the best course of action as of now would be removing the files from the packaging, requiring users to pull it instead. Feedback welcome.

**Comment by IntegerLimit** [comment]
Does this get packaged into the server zip? I actually packaged it, at least for 1.6, and I did use Windows. Will attempt to remove from server-zip now.

**Comment by IntegerLimit** [comment]
This is infact not the pack-mode-switcher file, which doesn't go into the server zip, but the launch.sh file.

**Comment by IntegerLimit** [comment]
Should be closed by using GHA to build in the future.
