### ISSUE TITLE
Putting an item conduit on a maintenance hatch crashes the game and corrupts world

### ISSUE THREAD

**Issue by JaneStateDog** [Nomi-CEu/nomi-ceu#328]
**Pack Version:**
1.6

**Launcher:**
Prism Launcher

**Mode:**
Normal Mode

**Environment:**
I am on singleplayer and have not changed any configurations, at least not any that would affect this.

**Description:**
I had a maintenance hatch on the top of my EBF and I was routing some item conduits up there. I shift-right clicked on the maintenance hatch to place down a conduit on top and it crashed my game. I can no longer load into the world.

**Expected Behavior:**
It should've placed the item conduit on top without crashing the game and corrupting my world.

**Steps To Reproduce:**
I believe everything there is to say is in the description section.

**Crash Log:**
[crash-2023-04-13_14.55.51-server.txt](https://github.com/Nomi-CEu/nomi-ceu/files/11225682/crash-2023-04-13_14.55.51-server.txt)

**Comment by IntegerLimit** [comment]
Fixed in GitHub, with the CEu Update Commit.
