### ISSUE TITLE
Fusion Reactor Mk2 Quest requires wetware circuits (Hard Mode)

### ISSUE THREAD

**Issue by felix-schneider** [Nomi-CEu/nomi-ceu#330]
**Pack Version:**
1.6

**Launcher:**
N/A

**Mode:**
Hard Mode

**Environment:**
N/A

**Description:**
As the title says. It seems like the quest depends on the wrong quest entirely, it depends on "The Fourth and Final Tier Six Circuits", but the reactor needs Tier 8 circuits. It can be made with crystal mainframes and Wetware cannot be made before getting the reactor.

**Expected Behavior:**
The Quest should depend on "The First Tier 8 Circuits"

**Steps To Reproduce:**
N/A

**Crash Log:**
N/A

**Comment by IntegerLimit** [comment]
What... I fixed this... try `/bq_admin default load` and see if that fixes the problem.

**Comment by felix-schneider** [comment]
No, still the same

**Comment by IntegerLimit** [comment]
huh

**Comment by IntegerLimit** [comment]
Closed with https://github.com/Nomi-CEu/nomi-ceu/commit/5b2269dc2eb3fa6bc9e92ec713bd5b8e58ca12a3.
