### ISSUE TITLE
Liquid Fuel Tank recipe uses thermalexpansion tank that doesn't link to a recipe.

### ISSUE THREAD

**Issue by CollinJ** [Nomi-CEu/nomi-ceu#332]
Repro: Look up recipe for "Liquid Fuel Tank" in JEI -> click thermal expansion tank for recipe
Expectation: opens the recipe for a basic thermal expansion tank
Reality: doesn't open a recipe, adds a 'no-recipe' tank item to recent recipes

I ran /ct hand on the different items and got:
Working recipe: `<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Creative: 0 as byte, Level: 0 as byte})`
Not working recipe: `<thermalexpansion:tank>.withTag({RSControl: 0 as byte, Level: 0 as byte})`

[The recipe uses](https://github.com/Nomi-CEu/nomi-ceu/blob/c46d39b7018aedddfeaf634d11529ff4f63b169f/overrides/scripts/AdvRocketry.zs#L426) `<thermalexpansion:tank>`

**Comment by IntegerLimit** [comment]
The recipe works. It just doesn't show correctly in JEI I believe.

**Comment by IntegerLimit** [comment]
Can you check if the above is true? Also, next time, please use the provided bug-report template.

**Comment by CollinJ** [comment]
Yes the recipe does work. It's just a one line fix though and I didn't want to PR just for that. All other references to thermalexpansion:tank in the repo use the one with the extra tag data.

**Comment by IntegerLimit** [comment]
Ok, I'll fix it.
