### ISSUE TITLE
Super tank issue with locking and voiding.

### ISSUE THREAD

**Issue by CactusCool** [Nomi-CEu/Nomi-CEu#334]
In GTCEU 2.6 there is an issue preventing tanks from locking correctly. There is also no option for voiding only overflow void.

**Comment by IntegerLimit** [comment]
Yes, it is a GTCEu issue, known, and hopefully fixed next update. Also, for future reference, please use the provided bug report template.

**Comment by IntegerLimit** [comment]
Also, there is an option to void overflow liquid. There is just no option to void at, say, 95%.

**Comment by IntegerLimit** [comment]
Fixed in GT 2.7.3

**Comment by Folanlron** [comment]
Fixed via https://github.com/Nomi-CEu/Nomi-CEu/pull/452
