### ISSUE TITLE
Caesium is balanced poorly

### ISSUE THREAD

**Issue by NotMyWing** [Nomi-CEu/nomi-ceu#336]
**Pack Version:**
1.5.2

**Mode:**
HM

**Description:**
Mid-to-late sources of Caesium are limited to Lepidolite and Pollucite. In regards to the T5 mission, even with proper ore multiplication using Ore Drills, the amount of Caesium one gets is insufficient to keep both the Neocryolite line and Omnium going.

**Comment by IntegerLimit** [comment]
This was addressed in 1.5.2, with the adding of Pollucite to the t5 Snowchestite mission, but I guess it wasn't enough....

**Comment by IntegerLimit** [comment]
Another way is to balance the naquadah line, meaning no caesium is lost there. What do you think of that idea? And if that were to happen, would the amount of pollucite in the snowchestite mission need to decrease?

**Comment by NotMyWing** [comment]
It's already being partially recovered by cycling Neocryolite back and forth.

**Comment by IntegerLimit** [comment]
I mean if it was completely balanced, meaning absolutely no caesium is spent there. Would that be a good way to solve the problem? And if that were to happen, would the amount of pollucite in the snowchestite mission need to decrease?
