### ISSUE TITLE
Crash while making epichlorohydrin in a Large chemical reactor

### ISSUE THREAD

**Issue by cultistofdrakness** [Nomi-CEu/nomi-ceu#337]
Thanks for taking the time to fill out this report! 

Note: if you need general tech support for things like server configuration, or general game support (how to I make this?), Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

Check if the bug is fixed on the latest version before submitting. The latest version is v1.6, and the latest beta is v1.6.1-beta-1.

1.6

Curseforge

Normal

Multiplayer

Making epichlorohydrin in a large chemical reactor, sharing blocks or being on chunk border doesnt fix it, this applies to both recpies available too. Upon finishing the craft the game freezes and chrashes to desktop.

The game doesnt crash.

Try to make epichlorohydrin in a large chemical reactor

**Crash Log:**

[crash-2023-04-21_17.05.06-server.txt](https://github.com/Nomi-CEu/nomi-ceu/files/11297193/crash-2023-04-21_17.05.06-server.txt)

**Comment by cultistofdrakness** [comment]
oh i should specify,  cuse i didnt think of this before, this happens when a  4x output hatch is used, it did just work when i again tried with 1x output hatches

**Comment by IntegerLimit** [comment]
Um, can you check if this happens on 1.6.1 alpha, and then if it does, report it to GTCEu?

**Comment by IntegerLimit** [comment]
Nevermind, this was fixed with gt 2.6.1. I recommend updating to 1.6.1-alpha, as it is more stable than 1.6, and fixes this above issue.
