### ISSUE TITLE
PRs to watch out for

### ISSUE THREAD

**Issue by IntegerLimit** [Nomi-CEu/Nomi-CEu#338]
These are eventual PRs to GT that change important parts of the game. When a GT update comes out including these PRs, further thought should be put into the affect of these PRs, and the quest book edited with the changes of these PRs.

This does not mean these PRs are bad, on the contrary, they are beneficial.

- [ ] https://github.com/GregTechCEu/GregTech/pull/1831
- [ ] https://github.com/GregTechCEu/GregTech/pull/1720

**Comment by Folanlron** [comment]
Add a Note that when updating to next version of GTCEu Multi-blocks might need to be re-formed cause of changes to Energy Hatch logic within Gregtech its self..

See 

- [ ]  https://github.com/GregTechCEu/GregTech/pull/1741

**Comment by IntegerLimit** [comment]
Oh, is that PR coming in 2.6.2?

**Comment by DStrand1** [comment]
With https://github.com/GregTechCEu/GregTech/pull/1741, the PA/APA can still accept more hatches (in fact, its limit was uncapped completely beyond casing minimums). Though standard multiblocks from GT are only 2. GCYM not yet determined

**Comment by IntegerLimit** [comment]
Oh, thanks for the heads up! Looks like some changes will have to be made to the qb.

**Comment by IntegerLimit** [comment]
Do we want to enable this in some way https://github.com/GregTechCEu/GregTech/pull/1830#event-9511159042 (especially relating to HM)?

**Comment by Folanlron** [comment]
For HM I'd say the research at min.

I would add that HM should have ordered inputs also, but with so many people not liking AE2FC. Wouldn't be good to force it.

**Comment by IntegerLimit** [comment]
Yeah, I agree, maybe some research. but not too much.

I'll have to play around with it, and see how it works / how annoying it is before the decision is finalised though.

**Comment by IntegerLimit** [comment]
So everything was merged in GT 2.7. Moving this to 1.7 milestone.
