### ISSUE TITLE
Nuclearcraft freezes game on world close (when on a lan world, cheats enabled)

### ISSUE THREAD

**Issue by showierdata9978** [Nomi-CEu/nomi-ceu#344]
Thanks for taking the time to fill out this report! 

Note: if you need general tech support for things like server configuration, or general game support (how to I make this?), Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

Check if the bug is fixed on the latest version before submitting. The latest version is v1.6, and the latest beta is v1.6.1-beta-1.

**Pack Version:**
1.6.1

**Launcher:**
Prism launcher

**Mode:**
Normal Mode

**Environment:**
Singleplayer with lan enabled for op

**Description:**
When closing a world on Nuclearcraft, the game freezes with little to no CPU usage, and no GPU useage

**Expected Behavior:**
The world closes, without having to kill the game

**Steps To Reproduce:**
- Load a world on lost city's (no idea if this does anything)
- Enable LAN with cheats enabled and survival mode
- (possible step) Try to disable /home cooldowns
- try to exit the game

**Crash Log:**
If your client crashed as a result of this bug, please upload the generated crash log. This is found in your launcher's Nomifactory CEu profile (aka instance) in a folder called `crash-reports`. If there was no crash, but instead an error screen, please upload your `latest.log` instead.
https://mclo.gs/FD78Btn

**Screenshots:**
![image](https://user-images.githubusercontent.com/68120127/235281397-c01586f3-b1d5-416c-9bf2-2b866f8ab270.png)

![image](https://user-images.githubusercontent.com/68120127/235281302-d62d9b42-6788-475f-8b0a-ca6d9e9fad15.png)

Device info:

Processor    Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz   3.30 GHz
Installed RAM    8.00 GB
Device ID    2325B0D6-3582-47B4-BC28-9D829AA6A201
Product ID    00325-84915-31985-AAOEM
System type    64-bit operating system, x64-based processor
Pen and touch    No pen or touch input is available for this display

**Comment by showierdata9978** [comment]
(note, the reason i posted this here, is because NC has a warning on there issue tracker about the version that is being used by default)

**Comment by IntegerLimit** [comment]
LAN.... that kind of breaks mods, and causes janky behaviour. I'm honestly not too surprised by this freeze. Try to avoid using Open To LAN, that's kind of really the only solution here.

Note: you can use [NBTExplorer] (https://github.com/jaquadro/NBTExplorer/releases) to allow cheats on your world permanently. Once you've installed it, open it, open your saves folder, open the world you want to modify, open level.dat, open data, select `allowCommands`, click the pencil on the toolbar up top, and change the value from 1 to 0.

**Comment by longme179** [comment]
same issues here 
LAN seems to break things
