### ISSUE TITLE
TheOneProbe can't show framed drawer controller correctly

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [Nomi-CEu/nomi-ceu#347]
Thanks for taking the time to fill out this report! 

Note: if you need general tech support for things like server configuration, or general game support (how to I make this?), Discord is a better venue. Please open an issue only if there is a clear bug with the pack or if you have been asked to by one of the Discord staff.

Check if the bug is fixed on the latest version before submitting. The latest version is v1.6, and the latest beta is v1.6.1-beta-1.

**Pack Version:**
v.1.6.1-beta-1

**Launcher:**
CurseForge Launcher

**Mode:**
Expert Mode (i didn't test normal mode)

**Environment:**
SIngleplayer 

**Description:**
TOP show the framed drawer controller like this:
![2023-05-01_23 17 24](https://user-images.githubusercontent.com/111768452/235486052-22e22d97-4355-4d80-b358-e1b80688444f.png)

**Expected Behavior:**
TOP should show framed drawer controller info like the normal controller:
![2023-05-01_22 55 06](https://user-images.githubusercontent.com/111768452/235486105-6b396ae0-6e34-4248-818d-04d0bc9e99dc.png)

Edit: The framed controller slave has this bug, too

**Comment by IntegerLimit** [comment]
Um... let me have a look at this...
