### ISSUE TITLE
Weird crash bug

### ISSUE THREAD

**Issue by a1Kamyk** [Nomi-CEu/nomi-ceu#349]
### Nomi CEu Version

1.6

### Launcher

Curseforge, ATlauncher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

![image](https://user-images.githubusercontent.com/132384053/235732413-c942e3f2-6c3b-48b4-8208-f3c0a1146135.png)
The game crashes right after the building terrain part of loading

### Expected Behavior

Loading the save

### Reproduction Steps

1. Download the modpack from curseforge
2. Launch it either from curseforge or ATlaucnher
3. Launch a save
4. Get a crash while loading the save

### Logs

Chrash report https://mclo.gs/nptff2C

### Additional Information

I have no idea what this is caused by i didnt do anything out of ordinary it only happens on one save i can create a new one and play normally i tried switching launchers but the issue persists

**Comment by Folanlron** [comment]
You lost power while playing the game?

You need to go into the save directory and delete the enderstorage directory which is located at:
 NomifactoryGTCEuPort\saves\2nd attempt\EnderStorage.

You will lose any items/fluid you have in any ender chests/tanks..

Or restore from a back-up Up to you how you want too handle this.

**Comment by a1Kamyk** [comment]
It did work thank you for the help
