### ISSUE TITLE
my nomifactory world crashes when i launch

### ISSUE THREAD

**Issue by hdks1111** [Nomi-CEu/nomi-ceu#350]
crash log:https://mclo.gs/NqXF9e2

**Comment by IntegerLimit** [comment]
Please use the provided bug report template.

**Comment by IntegerLimit** [comment]
Fixed in 1.6.1 alpha https://www.curseforge.com/minecraft/modpacks/nomi-ceu/files/4494694. Duplicate of https://github.com/Nomi-CEu/nomi-ceu/issues/311.

Next time, use the provided templates.
