### ISSUE TITLE
All blocks are black but endervours

### ISSUE THREAD

**Issue by hdks1111** [Nomi-CEu/nomi-ceu#351]
### Nomi CEu Version

1.6.1-alpha-1

### Launcher

FTB launcher

### Configurations or Mods Changed

I added random things and ultimine

### Environment

single player

### Mode

Normal Mode

### What Happened

![2023-05-04_15 10 07](https://user-images.githubusercontent.com/125722677/236188294-9855fe13-5765-49be-9c03-d2f34fb2c1ae.png)

### Expected Behavior

I should be able to see the blocks

### Reproduction Steps

I dont know

**Comment by hdks1111** [comment]
it still looks the same

**Comment by IntegerLimit** [comment]
Hmm... does this happen on a new world? Can you confirm you are using a fresh instance?

**Comment by hdks1111** [comment]
Here's the log:
[latest.log](https://github.com/Nomi-CEu/nomi-ceu/files/11402954/latest.log)
It does happpen in a new world

**Comment by hdks1111** [comment]
Yes it does.
Heres The Log:
[latest.log](https://github.com/Nomi-CEu/nomi-ceu/files/11402965/latest.log)

**Comment by Folanlron** [comment]
You are giving Minecraft full access to all the RAM in the laptop you own..

Memory: 524414880 bytes (500 MB) / 1073741824 bytes (1024 MB) up to 10334765056 bytes (9856 MB)

Drop it down to 6gb..

**Comment by hdks1111** [comment]
i did and everything is still dark.

**Comment by hdks1111** [comment]
It is a new installation btw

**Comment by IntegerLimit** [comment]
No idea.... what is your OS?

**Comment by hdks1111** [comment]
windows

**Comment by hdks1111** [comment]
I fixed it. Turned out that i had to reinstall the mods and it fixed itself.
