### ISSUE TITLE
Thermal Expansion Satchels not picking anything up automatically

### ISSUE THREAD

**Issue by dhasial** [Nomi-CEu/nomi-ceu#353]
### Nomi CEu Version

1.6.1-alpha-1

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

None of the satchels pick anything up automatically.

### Expected Behavior

Expect satchels to pick up whitelisted filter items automatically.

Tested on the basic and void satchel variants.

### Reproduction Steps

I set an item in the filter, toggled it to whitelist and items that are meant to be filtered are put in the inventory instead of the satchel, even when the inventory is full.

I've tried toggling the other switches too even though they shouldn't make a difference for something like cobblestone, but they make no difference.

I googled it and on [another modpack's repo issue](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/issues/514), apparently there used to be a keybind set to `V` that would toggle satchel autocollection, but that doesn't exist here. Unsure if that is related.

**Comment by Folanlron** [comment]
You have to hit v on each satchel in order for auto-collect to be activated ...

**Comment by dhasial** [comment]
It still doesn't work, there's no animation when pressing v, it still doesn't autocollect, and there is no way to know that since satchels aren't listed anywhere in the keybinds. Also my version is actually 1.5.2, updated to reflect that.

Looking at the tooltip, it says "Press `(NONE)` to enable autocollect", but there is no way to set this in keybinds. Searching "satchel" or "thermal expansion" in category doesn't display anything.
