### ISSUE TITLE
Black-steel cant be crafted

### ISSUE THREAD

**Issue by qianbing233** [Nomi-CEu/nomi-ceu#355]
### Nomi CEu Version

1.6

### Launcher

Hello minecraft launcher

### Configurations or Mods Changed

Add ae2fc version:2.4.12-r
       Fluxnetworks version 4.1.134

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

The blacksteel dont craft

### Expected Behavior

![IMG_20230503_135458](https://user-images.githubusercontent.com/59565986/236628075-9120654f-ac84-4404-9ace-10557a25f0bf.jpg)

### Reproduction Steps

![IMG_20230503_135455](https://user-images.githubusercontent.com/59565986/236628084-7b637edd-9f17-4232-b5ea-4b292ab66aa7.jpg)

**Comment by Folanlron** [comment]
Already fixed, update to 1.6.1 will also fix some other issues that can occur in 1.6..

**Comment by IntegerLimit** [comment]
Also, use f2.
