### ISSUE TITLE
Bulk blast chiller maceration and arc furnace recipe giving neutronium

### ISSUE THREAD

**Issue by altmines** [Nomi-CEu/nomi-ceu#357]
### Nomi CEu Version

1.6.1-alpha-1

### Launcher

Prism Launcher

### Environment

Single Player

### Mode

Normal Mode

### What Happened

Crafting the bulk blast chiller uses naq instead of neutronium now in 1.6.1, but when u macerate the controller or arc furnace it you get neutronium instead of naquadah.

### Expected Behavior

Expect to get nequadah as endproducts instead of neutronium when macerating/arc furnace the bulk blast chiller.

### Reproduction Steps

NIL, this is a recipe problem

**Comment by IntegerLimit** [comment]
This is fixed in the github, and will be fixed in 1.6.1-beta, which will hopefully come out sometime tomorrow.

**Comment by altmines** [comment]
nice
