### ISSUE TITLE
Crash when scrolling over an item in the package recipe encoder

### ISSUE THREAD

**Issue by whizvox** [Nomi-CEu/nomi-ceu#358]
### Nomi CEu Version

1.5.2

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

When viewing a recipe in the Package Recipe Encoder, if you scroll your mouse while hovering over an item stack, the game crashes. I initially had this happen in my survival world, and the game managed to catch the crash, auto-uploading the log to mclo.gs and allowing me to go back to the title screen. When I went to replicate it, the game instead froze, and I needed to kill the process.

![nomifactory crash](https://user-images.githubusercontent.com/8813286/236775214-51fdcf42-218a-49f2-8073-c9daa9c93f42.png)

### Expected Behavior

Nothing should happen when scrolling over one of these ingredient items, since they're not real.

### Reproduction Steps

1. Interact with a Package Recipe Encoder
2. Put a Package Holder in the expected top-left slot
3. Select the "Advanced Crafting" option
4. Use JEI to add a recipe
5. Scroll over one of the input ingredient item stacks

### Logs

https://mclo.gs/2vB8IG3

**Comment by IntegerLimit** [comment]
Um... not sure... I think it might have been fixed in 1.6.1, can you try reproducing it there?

**Comment by whizvox** [comment]
> Um... not sure... I think it might have been fixed in 1.6.1, can you try reproducing it there?

Also occurs on 1.6.1-alpha-1

https://mclo.gs/TQZLngi

**Comment by IntegerLimit** [comment]
We are updating to dan's mouse tweaks for 1.6.1-beta-2, please test if the issue occurs on that when that comes out.

**Comment by IntegerLimit** [comment]
Can you see if this issue occurs on 1.6.1-beta-2 : https://www.curseforge.com/minecraft/modpacks/nomi-ceu/files/4543311

**Comment by TotalPotato** [comment]
https://mclo.gs/gxT3r4W
Just tested in 1.6.1 beta 2
Still an instant crash

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/Nomi-CEu/nomi-ceu/commit/9a80436940aa3a207acabe1024b08cf7c673ae98 .
