### ISSUE TITLE
Quest about dark/electrical steel is wrong

### ISSUE THREAD

**Issue by be1rad** [Nomi-CEu/nomi-ceu#360]
### Nomi CEu Version

1.6.1-alpha-1

### Launcher

Official Launcher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Quest Says That Electrical Steel Is Made In A Alloy Smelter With Silicon Dust & Steel, Another Quest Also Says That, But This Time For Dark Steel, Neither Of Which Work.

### Expected Behavior

Expected for Dark / Electrical Steel To Be Made.

### Reproduction Steps

1. Try Obtaining Dark / Electrical Steel.
2. Done!

### Additional Information

Some Other Alloy Have This Bug Too.

**Comment by IntegerLimit** [comment]
You are using the CF launcher (I assume). Please try to see if this issue happens with a different launcher, like Prism Launcher.

P.S. CurseForge breaks stuff, and... I guess it can be called the *official* launcher, but the *unofficial*, or *third-party*, launchers are much better.

**Comment by be1rad** [comment]
well.... what can a launcher do to the game?

**Comment by be1rad** [comment]
also, i did some hackery and made it run on the mojang launcher.

**Comment by Folanlron** [comment]
> well.... what can a launcher do to the game?

You would be amazed just how bad the launchers are...

**Comment by IntegerLimit** [comment]
Both the mojang and CF launcher can MASSIVELY break the pack. Believe me, I know from experience.

Prism Launcher is the alternative I recommend.

**Comment by be1rad** [comment]
why and how?

**Comment by IntegerLimit** [comment]
It can break many different aspects of the modpack, and many issues that have been submitted were actually caused by the CF Launcher. Please use a different launcher, like Prism Launcher, and see if your above issue still occurs.

**Comment by be1rad** [comment]
Thx, prism launcher works
