### ISSUE TITLE
Auto-Breaker and Phantom Placer seem to generate random Items.

### ISSUE THREAD

**Issue by TheKoci** [Nomi-CEu/nomi-ceu#362]
### Nomi CEu Version

1.6.1-alpha-1

### Launcher

Curseforge

### Configurations or Mods Changed

Added every support-scripted mod apart from ProjectRedIllumination

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

During setting up our ore processing, namely Ore Drilling Plant for more crushed dust, there is a semi-automated circuit that breaks and places the Ore Drilling Plant block every 20 seconds (matches annihilation planes speed-not important). Over the course of some hours, it sometimes places completely random items there. After putting a stack of OreDrilling Plants there to see what it places, you can see on the image it somehow managed to "create" these random items. There is no access to ME or anything, it's a closed circuit.

![nomibug1](https://github.com/Nomi-CEu/nomi-ceu/assets/18722279/fd4381f5-b609-4884-84b5-5ce610daa68c)

The setup is as follows:

![nomibug2](https://github.com/Nomi-CEu/nomi-ceu/assets/18722279/233f5d05-bb55-4966-b38a-01824ecc4d06)
1: Phantom Placer bound to 3.
2: Auto-Breaker facing 3.
3: Ore Dilling Plant base block
4: Timer with 20 seconds
5: EIO conduits from Auto-Breaker to Phantom Placer

### Expected Behavior

It shouldn't generate random items

### Reproduction Steps

1. Replicate the circuit from the image
2. After some time it should/would place random items instead of Ore Drilling Plant.

### Additional Information

I am not sure if it is a server bug, modpack bug or specific mod bug, but maybe someone can tell, if it does this for more people.

**Comment by Folanlron** [comment]
See, https://github.com/Nomi-CEu/nomi-ceu/issues/244

This is a problem on AA side of things, the AA machines don't like how GT in general has it's machines setup, They are all under 1 ID but are all separated my Meta data. Unfortunately it is a AA problem and something we can't fix..

**Comment by IntegerLimit** [comment]
Closed as duplicate.
