### ISSUE TITLE
Inconsistent recipes with doors and trapdoors in HM/NM

### ISSUE THREAD

**Issue by MorphRed** [Nomi-CEu/Nomi-CEu#365]
### Nomi CEu Version

1.6.1-beta-2

### Launcher

GD Launcher

### Environment

Singleplayer

### Mode

Both Modes

### What Happened

Iron (and different metallic) doors and trapdoors recipes are different in their assembler and crafting table recipes
NM should not require plates, while HM should require plates

https://github.com/Nomi-CEu/nomi-ceu/assets/111656218/bad6508d-d9d9-4bef-8351-9587c6fcd48f

Also hardmode dark iron door
![Capture d'écran 2023-05-23 135923](https://github.com/Nomi-CEu/nomi-ceu/assets/111656218/e09cfea3-df24-4abd-a832-ee3aa7421113)

### Expected Behavior

Iron (and different metallic) doors and trapdoors are supposed to be consistent with its different crafting counterparts along with its assembler recipe

### Reproduction Steps

check jei

### Additional Information

Literally unplayable (sarcasm)

**Comment by IntegerLimit** [comment]
As mentioned https://github.com/Nomi-CEu/nomi-ceu/issues/391#issuecomment-1647656459, this is a GTCEu issue, and hopefully will be fixed in 2.7.3. If you have time before Emiuna makes an issue at GTCEu, you can make an issue there, mentioning the dupe in #391.

**Comment by Folanlron** [comment]
Fixed via, https://github.com/Nomi-CEu/Nomi-CEu/pull/452
