### ISSUE TITLE
Nomi CEu HM Changes [Add to this with HM QB Issues!]

### ISSUE THREAD

**Issue by GGabrielDev** [Nomi-CEu/Nomi-CEu#367]
### Nomi CEu Version

1.6.1-beta-2

### Related Problem

I'm intending to open this issue to remark observations on Hard/Expert mode playthrough that can be seen as oversights or just not enough elaboration on the difference from Normal mode.

### Your Solution

Elaborate over the observations and seek for possible fixes if necessary for them. Each comment will present a different observation with most likely a possible fix for it.

### How Will Your Solution Work

----------

### Alternatives You've Considered

----------

**Comment by GGabrielDev** [comment]
# Issue
A note on the Genesis Book: could you change it so it doesn't seem like is mandatory to go with RF generation and converters to EU? GregTech has LV Steam Turbines so actually RF to EU conversion is not mandatory.

Maybe is more obvious in HM 'cuz you go through the Steam Age and you actually have chance to NOT go the RF route, but is kinda annoying that I'm making the turbine and the converter because is mandatory to progress (even though I already set up High Pressure boilers, which the questbook does mention and LV Steam Turbines for generation), not because I'm actually using them.

# Solution
Like my suggestion would be that you could have two routes to unlock the remaining part of the quests. One using the TF Steam Boiler, EnderIO conduits and converters, and the other one with GT Boilers and Steam Turbines.

## Additional Information
![image](https://github.com/Nomi-CEu/nomi-ceu/assets/69987026/161ed748-0e0c-454b-a939-c68b8867eef4)

**Comment by IntegerLimit** [comment]
I'll fix the genesis thing in 1.6.1. Further issues, if their small, 1.6.1, else, 1.7.

**Comment by GGabrielDev** [comment]
> I'll fix the genesis thing in 1.6.1. Further issues, if their small, 1.6.1, else, 1.7.

Noted. I'll keep my observations along the playthrough regarding the Quest Book and gameplay here.

**Comment by GGabrielDev** [comment]
## Sugguestion
Not really related to HM, but because I have this issue already open, I guess I can just mention this here but: Is there a chance to get the Hand Framing Tool from DJ2 ported into Nomi? Is funny because they ported it from NomiCEu in the first place, but... Their implementation is more comftable and convenient (No, is not funny to load the actual one with sticks to use it)

**Comment by GGabrielDev** [comment]
# Issue
It seems kind of odd than even if we have the LV Converters quest accept all kinds of converters, the LV Batteries one enforces it to be a x4 Battery Bank.

# Solution
Make the quest so it accepts any type of LV Battery Bank. I think the quest that relates for the batteries is still fine if it requires 4 empty batteries, because that would be the minimum amount that you can get inside any bank regardless.

**Comment by IntegerLimit** [comment]
> ## Sugguestion
> Not really related to HM, but because I have this issue already open, I guess I can just mention this here but: Is there a chance to get the Hand Framing Tool from DJ2 ported into Nomi? Is funny because they ported it from NomiCEu in the first place, but... Their implementation is more comftable and convenient (No, is not funny to load the actual one with sticks to use it)

Oh, so like remove the stick requirement, and just allow turning drawers into framed for free? Sure!

**Comment by GGabrielDev** [comment]
The quest *#76 - The First Tier Two Circuits* needs its description changed to match HM.

**Comment by GGabrielDev** [comment]
Also, I just noticed that in HM, the quest for the Creative Chest is still called *Creative Vending Upgrade*, lmao.

**Comment by IntegerLimit** [comment]
Ah, thanks, I replaced all the mentions of that in NM, but I must have forgot to do it in HM.

**Comment by GGabrielDev** [comment]
The quest *#94 - Sulfuric Acid* doesn't count Glass Vials, so even thought gh I'm holding the sulfuric acid inside of them, I can't complete the quest.

You can still use a bucket to complete it, but I presume it should work with Vials as well...

**Comment by IntegerLimit** [comment]
Thank you for your testing.

**Comment by GGabrielDev** [comment]
Not exclusive to HM, but the quest *#789 - Filters* doesn't explain the Ore Dict Filter at all. There's the quest *#788 - Smart Item Filters* that explains the previously mention type of filter, but the Ore Dict Filter is left out of the loop, and considering that Ore Dict Filtering is relevant in the pack in multiple instances (Being the Ore Processing Line the most noticeable one), I think it should have a mention somewhere.

**Comment by IntegerLimit** [comment]
> Not exclusive to HM, but the quest _#789 - Filters_ doesn't explain the Ore Dict Filter at all. There's the quest _#788 - Smart Item Filters_ that explains the previously mention type of filter, but the Ore Dict Filter is left out of the loop, and considering that Ore Dict Filtering is relevant in the pack in multiple instances (Being the Ore Processing Line the most noticeable one), I think it should have a mention somewhere.

Hmm... which one of these two do you think is better?
A: combine quests into one massive filter quest
B: quest for each filter
C: seperate quest for ore-dict filter, similar to smart filter quest
D: further mention ore-dict filter in smart filter quest

**Comment by GGabrielDev** [comment]
> > Not exclusive to HM, but the quest _#789 - Filters_ doesn't explain the Ore Dict Filter at all. There's the quest _#788 - Smart Item Filters_ that explains the previously mention type of filter, but the Ore Dict Filter is left out of the loop, and considering that Ore Dict Filtering is relevant in the pack in multiple instances (Being the Ore Processing Line the most noticeable one), I think it should have a mention somewhere.
> 
> Hmm... which one of these two do you think is better? A: combine quests into one massive filter quest B: quest for each filter C: seperate quest for ore-dict filter, similar to smart filter quest D: further mention ore-dict filter in smart filter quest

I would go with the same approach they took on CP and make one quest for each: Normal Item/Fluid Filters, Smart Item Filters and Ore Dict Item Filters.

**Comment by IntegerLimit** [comment]
> > > Not exclusive to HM, but the quest _#789 - Filters_ doesn't explain the Ore Dict Filter at all. There's the quest _#788 - Smart Item Filters_ that explains the previously mention type of filter, but the Ore Dict Filter is left out of the loop, and considering that Ore Dict Filtering is relevant in the pack in multiple instances (Being the Ore Processing Line the most noticeable one), I think it should have a mention somewhere.
> > 
> > 
> > Hmm... which one of these two do you think is better? A: combine quests into one massive filter quest B: quest for each filter C: seperate quest for ore-dict filter, similar to smart filter quest D: further mention ore-dict filter in smart filter quest
> 
> I would go with the same approach they took on CP and make one quest for each: Normal Item/Fluid Filters, Smart Item Filters and Ore Dict Item Filters.

Sounds good.

**Comment by IntegerLimit** [comment]
> Also, I just noticed that in HM, the quest for the Creative Chest is still called _Creative Vending Upgrade_, lmao.

Fixed that and more in https://github.com/Nomi-CEu/nomi-ceu/commit/1182ffca79f44452122a3337794862141c21480b.

**Comment by IntegerLimit** [comment]
> ## Sugguestion
> Not really related to HM, but because I have this issue already open, I guess I can just mention this here but: Is there a chance to get the Hand Framing Tool from DJ2 ported into Nomi? Is funny because they ported it from NomiCEu in the first place, but... Their implementation is more comftable and convenient (No, is not funny to load the actual one with sticks to use it)

Removed in https://github.com/Nomi-CEu/nomi-ceu/commit/4e4628f772419f2e44279d8a9603342618fd5524. Lang is being overhauled now.

**Comment by GGabrielDev** [comment]
With `Lang` you mean the language? Nomi will have multiple languages now?

**Comment by IntegerLimit** [comment]
I mean the JEI description page. Nomi has always had support for English, and mostly supports Chinese.

I'm contacting the Cleanroom Server's Chinese Channel to get a translation.

**Comment by IntegerLimit** [comment]
Ah, I forgot to implement the quest suggestions here for 1.6.1-beta-4. I'll add it to 1.6.1 release.

**Comment by Preladon** [comment]
In HM, the quest 'Glider' in the Genesis page still talks about using coins to buy 'spawn cow' eggs. Given that coins don't exist in HM, suggest this is removed.

**Comment by IntegerLimit** [comment]
Ok, Thanks!

**Comment by Preladon** [comment]
Another minor text change - the Actually Additions drill core has a tool tip that says you can purchase it for Nomicoins

**Comment by IntegerLimit** [comment]
> 

Thanks

**Comment by IntegerLimit** [comment]
> The quest _#94 - Sulfuric Acid_ doesn't count Glass Vials, so even thought gh I'm holding the sulfuric acid inside of them, I can't complete the quest.
> 
> You can still use a bucket to complete it, but I presume it should work with Vials as well...
> 
> Edit: I also think that just adding to the quest that you need to have the liquid in a bucket to complete it could be a workaround, but I don't like it.

BQu Problem

**Comment by IntegerLimit** [comment]
> In HM, the quest 'Glider' in the Genesis page still talks about using coins to buy 'spawn cow' eggs. Given that coins don't exist in HM, suggest this is removed.

Fixed with https://github.com/Nomi-CEu/Nomi-CEu/commit/953076857123c5254f3b867e90e5a76968dd3417.

**Comment by IntegerLimit** [comment]
> # Issue
> 
> It seems kind of odd than even if we have the LV Converters quest accept all kinds of converters, the LV Batteries one enforces it to be a x4 Battery Bank.
> # Solution
> 
> Make the quest so it accepts any type of LV Battery Bank. I think the quest that relates for the batteries is still fine if it requires 4 empty batteries, because that would be the minimum amount that you can get inside any bank regardless.

Will be done in 1.7.

**Comment by IntegerLimit** [comment]
> The quest _#76 - The First Tier Two Circuits_ needs its description changed to match HM.

Can you give a larger description?

**Comment by IntegerLimit** [comment]
> Not exclusive to HM, but the quest _#789 - Filters_ doesn't explain the Ore Dict Filter at all. There's the quest _#788 - Smart Item Filters_ that explains the previously mention type of filter, but the Ore Dict Filter is left out of the loop, and considering that Ore Dict Filtering is relevant in the pack in multiple instances (Being the Ore Processing Line the most noticeable one), I think it should have a mention somewhere.

For 1.7.

**Comment by IntegerLimit** [comment]
> Another minor text change - the Actually Additions drill core has a tool tip that says you can purchase it for Nomicoins

Fixed with https://github.com/Nomi-CEu/Nomi-CEu/commit/3d3f3d6cd20cd743eb0364eec6eb9b3d6888977c

**Comment by denisbublikov** [comment]
Some things in the QB that could be changed:

    1. Steam production - Make any boiler to be accepted, no reason to make just a small bronze one
    2. To the Nether - doesn't need a PBF
    3. LV Power Storage - you can get Lithium at LV via Lepidolite centrifuging 
    4. LV assembling machine - doesn't need extractor and can be useful even without one
    5. Machine controllers - shouldn't need aluminium
    6. Ore Processing for Byproducts - maybe it's worth to mention that Chem Bath can help with the initial lack of gold since not many people even think about it, but still complain?
    7. Vanadium pentoxide and Vanadiumsteel quests are outdated
    8. Dark steel enchanter can be made MUCH earlier, not MV, but even pre-tier
    9. Glider quest mentioning coins as was stated earlier here
    10. I don't get why small microverse projector requires a HV hatch
    11. Quantum Flux extractor recipe is inneeded
    12. Idk, maybe rename the "Deuterium" quest since it talks about the moon overall and there is even another quest that asks for specifically deuterium?
    13. Omnium quest states number of 487 instead of 486
    
That's all for now I guess

**Comment by IntegerLimit** [comment]
> Some things in the QB that could be changed:
> 
> ```
> 1. Steam production - Make any boiler to be accepted, no reason to make just a small bronze one
> 2. To the Nether - doesn't need a PBF
> 3. LV Power Storage - you can get Lithium at LV via Lepidolite centrifuging 
> 4. LV assembling machine - doesn't need extractor and can be useful even without one
> 5. Machine controllers - shouldn't need aluminium
> 6. Ore Processing for Byproducts - maybe it's worth to mention that Chem Bath can help with the initial lack of gold since not many people even think about it, but still complain?
> 7. Vanadium pentoxide and Vanadiumsteel quests are outdated
> 8. Dark steel enchanter can be made MUCH earlier, not MV, but even pre-tier
> 9. Glider quest mentioning coins as was stated earlier here
> 10. I don't get why small microverse projector requires a HV hatch
> 11. Quantum Flux extractor recipe is inneeded
> 12. Idk, maybe rename the "Deuterium" quest since it talks about the moon overall and there is even another quest that asks for specifically deuterium?
> 13. Omnium quest states number of 487 instead of 486
> ```
> 
> That's all for now I guess

Glider quest problem was already fixed (as seen in my above message) and is released with 1.6.1a.

Can you remove it?

**Comment by Preladon** [comment]
> > The quest _#76 - The First Tier Two Circuits_ needs its description changed to match HM.
> 
> Can you give a larger description?

Not the original author, but just arrived here myself, and noted that (in HM), it still says 'requires *two* Tier One Circuits plus *two* diodes' but it actually needs three Tier One Circuits.

**Comment by Preladon** [comment]
In my HM playthrough, I've noticed that villages can generate with Bounty Boards. Whilst the widget items required to complete these have had their crafting recipes removed, it's possible to get bounties for things like LV components. Crafting these, and turning them into the bounty board grants Nomipennies and Nominickels, which have no value in HM.

Additionally, it would appear that it's possible to still craft bounty boards, so even if you don't find a village, it's possible to get coins that you can never use.

**Comment by IntegerLimit** [comment]
> In my HM playthrough, I've noticed that villages can generate with Bounty Boards. Whilst the widget items required to complete these have had their crafting recipes removed, it's possible to get bounties for things like LV components. Crafting these, and turning them into the bounty board grants Nomipennies and Nominickels, which have no value in HM.
> 
> Additionally, it would appear that it's possible to still craft bounty boards, so even if you don't find a village, it's possible to get coins that you can never use.

Ah, will be fixed in next update (hopefully).

**Comment by IntegerLimit** [comment]
> > > The quest _#76 - The First Tier Two Circuits_ needs its description changed to match HM.
> > 
> > 
> > Can you give a larger description?
> 
> Not the original author, but just arrived here myself, and noted that (in HM), it still says 'requires _two_ Tier One Circuits plus _two_ diodes' but it actually needs three Tier One Circuits.

Thanks

**Comment by IntegerLimit** [comment]
> The quest _#76 - The First Tier Two Circuits_ needs its description changed to match HM.

Fixed with https://github.com/Nomi-CEu/Nomi-CEu/commit/1a35ae82d9830c5444c5634d93268e3b857f07bd.

**Comment by Preladon** [comment]
The quest 'Phosphoric Acid' in the chapter 'Into The Microverse' has a description that shows a number of ways of making it. The first of these is 'Phosphorous, Oxygen and Water can be chemically reacted to produce Phosphoric Acid'.

However, at least in HM, this is only true if you use a Large Chemical Reactor, it cannot be done in the single block version (presumably deliberately...). It'd be good to update the quest description to differentiate this, I think.

**Comment by IntegerLimit** [comment]
> The quest 'Phosphoric Acid' in the chapter 'Into The Microverse' has a description that shows a number of ways of making it. The first of these is 'Phosphorous, Oxygen and Water can be chemically reacted to produce Phosphoric Acid'.
> 
> However, at least in HM, this is only true if you use a Large Chemical Reactor, it cannot be done in the single block version (presumably deliberately...). It'd be good to update the quest description to differentiate this, I think.

Thanks!

**Comment by tracer4b** [comment]
> Some things in the QB that could be changed:
> 
> ```
> 1. Steam production - Make any boiler to be accepted, no reason to make just a small bronze one
> 2. To the Nether - doesn't need a PBF
> 3. LV Power Storage - you can get Lithium at LV via Lepidolite centrifuging 
> 4. LV assembling machine - doesn't need extractor and can be useful even without one
> 5. Machine controllers - shouldn't need aluminium
> 6. Ore Processing for Byproducts - maybe it's worth to mention that Chem Bath can help with the initial lack of gold since not many people even think about it, but still complain?
> 7. Vanadium pentoxide and Vanadiumsteel quests are outdated
> 8. Dark steel enchanter can be made MUCH earlier, not MV, but even pre-tier
> 9. I don't get why small microverse projector requires a HV hatch
> 10. Quantum Flux extractor recipe is inneeded
> 11. Idk, maybe rename the "Deuterium" quest since it talks about the moon overall and there is even another quest that asks for specifically deuterium?
> 12. Omnium quest states number of 487 instead of 486
> ```
> 
> That's all for now I guess

For points 2 and 8, yes you can get them by looting chests but I don't want to assume everyone plays in lost cities or bothers to explore them
