### ISSUE TITLE
Update 1.6.1-beta2 broke keep exact on robot arm covers

### ISSUE THREAD

**Issue by MatthiasMann** [Nomi-CEu/nomi-ceu#369]
### Nomi CEu Version

1.6.1-beta-2

### Launcher

Minecraft Lauchner

### Configurations or Mods Changed

I only changed ladder climbing speed and some AE2 terminal settings

### Environment

Singleplayer / Peaceful

### Mode

Normal Mode

### What Happened

A MV robot arm cover in "keep exact" mode with an item filter and 4 sand in the filter in import mode will put 32 sand into the machine, reducing the transfer speed still puts 8 sand in

### Expected Behavior

Exactly 4 sand should be put into the machine

### Reproduction Steps

1. Place any machine (I used an MV chemical reactor) next to a vanilla chest
2. Attach robot arm to the side facing the chest
3. Configure the robot arm to "keep exact" mode
4. Put in an item filter and 4 sand
5. Change direction to import
6. Put a stack of sand in the chest

**Comment by MatthiasMann** [comment]
Hmm - it seems like it tries to balance the number of items in the machine and the chest

**Comment by Folanlron** [comment]
Already fixed in next CEu update, just waiting on a release and hopefully a new beta will release

**Comment by IntegerLimit** [comment]
Next release might take a while, we will probably just bansoukou it in.

**Comment by Devilovania** [comment]
> Already fixed in next CEu update, just waiting on a release and hopefully a new beta will release

Could you release an emergency fix pack, my server needs this more often.

**Comment by IntegerLimit** [comment]
I'm a bit busy this weekend, I'll make it as soon as I can.

**Comment by mariotacke** [comment]
Running into the same at the moment. Could you prepare a release, please?

**Comment by IntegerLimit** [comment]
Yep, I'm planning to make a quick fix release today, and do the other fixes and features later down the track. I'm busy now, but I'll do it later today, in probably around 4 or 6 hours later. (Its morning for me)

**Comment by IntegerLimit** [comment]
Fixing a few small issues, then releasing update.

**Comment by mariotacke** [comment]
Thanks for this @IntegerLimit . Clicking the link, it still shows the old version (Updated May 19). Could you provide instructions how to apply the patch?

**Comment by IntegerLimit** [comment]
Sorry, the release was rejected, due to a removed mod. I've replaced the mod with a new one, and I'll make the release again today. Sorry for the inconvenience and delays!

**Comment by IntegerLimit** [comment]
@mariotacke here: https://www.curseforge.com/minecraft/modpacks/nomi-ceu/files/4569766.
