### ISSUE TITLE
Flux Reconstruction augment cannot function due to no way of getting Essence of Knowledge

### ISSUE THREAD

**Issue by ConanODoyle** [Nomi-CEu/Nomi-CEu#370]
### Nomi CEu Version

1.6.1-beta-2

### Launcher

Curseforge

### Environment

Multiplayer, private server

### Mode

Normal Mode

### What Happened

The Energetic Infuser with the Flux Reconstruction augment cannot repair any tools, as there is no way of producing Essence of Knowledge. It is unclear if this inability to get essence of knowledge is intended or not - no issues show up in searching for "energetic infuser" or "flux reconstruction" and no info is given about this augment on the Energetic Infuser quest under Mid-Game.

### Expected Behavior

Expected to be able to produce Essence of Knowledge, to repair tools using the Flux Reconstruction augment in the Energetic Infuser

### Reproduction Steps

1. Create, power, and upgrade an energetic infuser to Hardened or higher
2. Add the Flux Reconstruction augment
3. Attempt to insert liquid XP/Attempt to check the recipe for Essence of Knowledge

### Additional Information

Checking the usage of essence of knowledge also does not bring up anything.

**Comment by IntegerLimit** [comment]
There is one way... I'll look at this later.

**Comment by ConanODoyle** [comment]
I forgot about the lategame creative tank 😅

**Comment by IntegerLimit** [comment]
Oh, the one way I was actually talking about was using TE's xp collector thing.
