### ISSUE TITLE
Normal mode Quest 504 "Brewery" should also accept HV+ breweries

### ISSUE THREAD

**Issue by MatthiasMann** [Nomi-CEu/Nomi-CEu#371]
### Nomi CEu Version

1.6.1-beta-2

### Your Solution

I used the pyrolysis oven to make biomass and wood tar so I did not build a brewery at LV or MV levels - I made one at HV for lubricant. But that one is not recognized by the quest.

### How Will Your Solution Work

As the LV/MV brewery are non essential to progressing - the quest should also accept higher tier breweries.

### Alternatives You've Considered

Craft a LV/MV brewery and immediately recycle it after completing the quest

**Comment by IntegerLimit** [comment]
Good Suggestion. I think this applies to *many* more quests as well, so I'll put this one in 1.7 as machine quest overhaul.
