### ISSUE TITLE
Lapotronic Energy Orb Cluster only craftable using new Lapotronic Energy Orb

### ISSUE THREAD

**Issue by vrejhead** [Nomi-CEu/Nomi-CEu#375]
### Nomi CEu Version

1.6.1-alpha-1

### Launcher

Prism

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

I could only craft the luv battery using a brand new lapotron from the circuit assembler, a used but empty one does not work.

### Expected Behavior

The assembly line should craft the luv battery regardless of the nbt of the input lapotron.

### Reproduction Steps

1. Make an assembly line 14 long
2. Put in all the necessary items except the lapotron including the soldering alloy
3. Craft a new one using the circuit assembler, middle click it to obtain a full stack with the same nbt
4. Put the lapotron in, it crafts in the assembly line
5. Charge another lapotron, then drain it(I used energy converter and energy trash can from eu2)
6. Put it in the assembly line again, this time it does not craft

### Additional Information

The new and used lapotrons do not stack, the nbt reveals that the used lapotron has nbt {Charge:0L} while the new one does not
As a debugging step I also put all the items in the assembly line the same order as displayed in jei

**Comment by IntegerLimit** [comment]
Transfer to GTCEu: https://github.com/GregTech/GregTechCEu/issues

**Comment by IntegerLimit** [comment]
Thanks!

**Comment by serenibyss** [comment]
Fixed in https://github.com/GregTechCEu/GregTech/pull/1888, scheduled for release in GTCEu 2.7

**Comment by Folanlron** [comment]
Fixed via, https://github.com/Nomi-CEu/Nomi-CEu/pull/452
