### ISSUE TITLE
Rubber sheets not crafting in 1.6 version, alr tried to change to ore:gtceHardHammers, but that didnt help

### ISSUE THREAD

**Issue by At0mic17** [Nomi-CEu/nomi-ceu#377]
### Nomi CEu Version

1.6

### Launcher

Curseforge

### Configurations or Mods Changed

changed 
ore:ToolHammer to
ore:gtceHardHammers

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

The rubber sheets wont craft on a crafting table or any other crafting table. I put 2 sticky resin in the middle and lower middle and in upper middle a wrought hammer

### Expected Behavior

I expected to see a rubber sheet

### Reproduction Steps

1. Get your Sticky resins and place them in lower middle, middle and on top a wrought hammer
2. Then check the crafting table output. If there is nothing, then it doesnt work
3. normally there should be a rubber sheet

**Comment by IntegerLimit** [comment]
CurseForge Launcher breaks things. Do not try to change the script, that only fixes it in previous versions, and will break it even more if tried to apply in 1.6+.

Try using a different launcher, such as Prism Launcher, and updating to 1.6.1-beta-2.
