### ISSUE TITLE
update to 1.6.1-beta-3a but still not fixed yet

### ISSUE THREAD

**Issue by mimnin** [Nomi-CEu/nomi-ceu#380]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

Legacy launcher

### Configurations or Mods Changed

change nothing

### Environment

single

### Mode

Normal Mode

### What Happened

place a conduit near a maintance hatch result in a crash despite the fact that i hear it is fixed in 1.6 beta 3

### Expected Behavior

it should do nothing with each other

### Reproduction Steps

1. place down a maintance hatch
2. place a conduit near it
3. crash

### Logs

https://gist.github.com/mimnin/45147509fe3f2d2e9e98b4b726e6f654

### Additional Information

nothing

**Comment by Folanlron** [comment]
Fixed VIA Discord
