### ISSUE TITLE
Microverse Projectors missing Input/Output Bus/Hatch Limits

### ISSUE THREAD

**Issue by ghzdude** [Nomi-CEu/Nomi-CEu#381]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

MultiMC

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

All Microverse Projectors do not have limits set for the Input/Output Busses/Hatches, meaning that the structure can be formed without any microverse casings.

### Expected Behavior

I/O Busses/Hatches should have a limit set. (perhaps a maximum of 1?)

### Reproduction Steps

1. Look at the multiblock preview in JEI
2. hover over the I/O busses and hatches in the preview
3. see the lack of a limit.
4. Optionally, use the GT terminal to autobuild the microverse projector

**Comment by IntegerLimit** [comment]
I'll look and see if I can do this in CT later, but otherwise, this is postponed until groovy.
