### ISSUE TITLE
transparent texture

### ISSUE THREAD

**Issue by KT-TY** [Nomi-CEu/nomi-ceu#382]
### Nomi CEu Version

1.6

### Launcher

CurseForge Launcher

### Configurations or Mods Changed

Add modpack texture: Faithful 32, Faithful 32 mod support

### Environment

Singleplayer

### Mode

Both Modes

### What Happened

I encountered a problem when using both version 1.6 and updated version 1.6.2 beta, as shown in the picture below. I added the Faithful32 texture pack and its mod support pack, but after placing all of the GT coils, they became transparent blocks. This phenomenon also appeared in the multi-block structure preview of HEI. I attempted to add rendering-fixing mods such as Optfine or Better FPS, but they did not solve the issue. Could this be a problem with the Java version? My Java version is Eclipse Temurin JDK with HotSpot 8u362-b09(x64).
![78450e50a9d7d67f4170e687d2fa5aa1.png](https://tinypic.host/i/ouIRDJ)

### Expected Behavior

Fix rendering issues.

### Reproduction Steps

None

### Additional Information

If the image cannot be loaded successfully, please contact me promptly. Thank you!

**Comment by KT-TY** [comment]
url of picture is: https://tinypic.host/i/ouIRDJ

**Comment by Folanlron** [comment]
Because of a few bugs that popped up, and adding lights you need to update CEu textures.

https://github.com/marisathewitch/Faithful32-GTCEu
