### ISSUE TITLE
Duplication/Void Glitch when using Crafting/Pattern wireless terminal as a bauble.

### ISSUE THREAD

**Issue by Bookh1ll** [Nomi-CEu/Nomi-CEu#384]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

GDLauncher

### Configurations or Mods Changed

AE2 Fluid Crafting
Lazy AE2

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

When I was walking around my base, I noticed the blank patterns in my wireless pattern terminal were being deleted. As I tested, I found that this issue also affected items inside the crafting part of the wireless crafting terminal, and that the issue only affected a certain area. I also learned that if you placed an item into the grid before entering the area, you could dupe instead of void the item.

After some testing, I found the source of the glitched area was a EnderIo wireless charging antenna I had placed minutes prior, and was able to perfectly replicate the glitch in a new world (Video Below).

### Expected Behavior

The wireless crafting/pattern terminals properly save their contents when being charged by an EnderIo wireless charging antenna.

### Reproduction Steps

1a. Put thing you want to dupe in terminal
1b. Put Wireless Crafting/Pattern terminal in bauble slot
2. Move into antenna range
3. While the terminal is charging, open it via hotkey and take the item you want to dupe out.
4. Close the terminal.
5. Repeat as many times as you like, or until the terminal finishes charging. (If the terminal finishes charging there is a change the dupe can continue for a bit.)

https://github.com/Nomi-CEu/nomi-ceu/assets/128931567/49bfe48b-e3d5-4659-878b-89ebec36f166

### Additional Information

This bug seems to happen by the EnderIo charger somehow preventing the Wireless Terminals from properly saving their contents (The individual terminals contents. Not the ME Networks contents.) when they are used as a Bauble via hotkey. This glitch did not occur when the terminal was in the players hand, nor was it caused by Flux Capacitors.

**Comment by Folanlron** [comment]
Please report to AE2 git, 

https://github.com/PrototypeTrousers/Applied-Energistics-2

**Comment by Bookh1ll** [comment]
Will do, thank you!

**Comment by IntegerLimit** [comment]
Hopefully fixed with this https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/1500661e4344a94518a53818c775381007dd8c65. Will update AE2 in next update!

**Comment by IntegerLimit** [comment]
Should be fixed with https://github.com/Nomi-CEu/Nomi-CEu/commit/f876a98810dac96874d74ab9f5fb54eb543d8f4f. If this still occurs, comment, and I will re-open this issue.
