### ISSUE TITLE
ME Conduit disconnects from cleanroom hull on world load

### ISSUE THREAD

**Issue by nanohum** [Nomi-CEu/nomi-ceu#386]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

Curse

### Configurations or Mods Changed

N/A

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

ME conduits do not stay connected upon world reload to hulls used as pass-throughs into cleanroom (specifically an MV hull in my case).  This causes autocrafting to turn off.

### Expected Behavior

ME conduit should stay connected on world load.  It would be nice if it connected to hull blocks by default.

### Reproduction Steps

1. Use an MV hull to allow ME conduit passthrough into cleanroom.  
2. Conduit does not connect to the hull by default.  Click hull with EnderIO wrench and conduit connects properly.  
3. Close/save world and open save.  Conduit is disconnected again.

**Comment by Folanlron** [comment]
It is an issue with EnderIO, place a normal Glass Fiber connection on the Hull before going to EnderIO Conduits and it will fix the problem.

**Comment by nanohum** [comment]
I should have thought of that - thanks!
