### ISSUE TITLE
Unable to Join World on Personal Server due to Unknown Errors (help)

### ISSUE THREAD

**Issue by CrimsonCritter4** [Nomi-CEu/nomi-ceu#389]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

Minecraft launcher

### Environment

Personal Forge Server

### Mode

Normal Mode

### What Happened

Every time I try to join I am kicked with only the message "Disconnected." I went to read my server logs and there did not appear to be an issue with a specific mod. The server and client both function on a different world on the same server, so the issue is clearly with this specific world of mine. I tried running the world on singleplayer and it seemed to work except that it crashed whenever I clicked "options" from the escape menu. 
![image_2023-07-04_141731264](https://github.com/Nomi-CEu/nomi-ceu/assets/138616957/b5508853-ce7e-4041-9ecc-dc004afbfe4f)
I do have some progress so I really wouldn't like to just start over on a new world. I also do not have any backups as they were deleted when I upgraded the server.

### Expected Behavior

Being able to join the world

### Reproduction Steps

1. Try to join the world
2. Get disconnected

### Logs

(the disconnection issue happens at the very bottom of the log)
[latest.log](https://github.com/Nomi-CEu/nomi-ceu/files/11951706/latest.log)

### Additional Information

There seems to be an issue with the world file rather than my connection or anything because the server still works without this world on it. I tried to view the world data for clear issues but its all encrypted or something

**Comment by Folanlron** [comment]
World files are not encrypted in anyway, they are just files with chunk data.

I would check you installed/upgraded the server correctly, as that error message usually means you have a mod causing a conflict, and it can't get far enough into the world to tell us "which" one is the problem child.

**Comment by CrimsonCritter4** [comment]
> World files are not encrypted in anyway, they are just files with chunk data.
> 
> I would check you installed/upgraded the server correctly, as that error message usually means you have a mod causing a conflict, and it can't get far enough into the world to tell us "which" one is the problem child.

I know that the server is fine because I tried a new world save and it worked perfectly, it is just as soon as I put my world with progress on it, it fails to connect me.

**Comment by IntegerLimit** [comment]
Try using a different launcher. You never know what CF/MC launcher breaks (as they break a lot, even seemingly unrelevant issues, somehow).

I recommend trying out Prism Launcher.

**Comment by Folanlron** [comment]
Seems more like World Corruption then Installer be bad.

What was the world on before updating that pack? I have a feeling that world might be lost cause of the maintenance hatch issue.

**Comment by CrimsonCritter4** [comment]
> Try using a different launcher. You never know what CF/MC launcher breaks (as they break a lot, even seemingly unrelevant issues, somehow).
> 
> I recommend trying out Prism Launcher.

I tried using prism launcher and am experiencing the same issues.

**Comment by CrimsonCritter4** [comment]
> Seems more like World Corruption then Installer be bad.
> 
> What was the world on before updating that pack? I have a feeling that world might be lost cause of the maintenance hatch issue.

The world was on 1.5.2, but I since I am still able to play it on singleplayer I checked and found no conduits near maintenance hatches so that isn't the issue. Definitely a world thing though no idea what it is.

**Comment by IntegerLimit** [comment]
Try restoring from a backup. These are automatically created every 30 minutes (at least now) to your `/backups` folder.

**Comment by CrimsonCritter4** [comment]
> Try restoring from a backup. These are automatically created every 30 minutes (at least now) to your `/backups` folder.

When I updated my server I deleted all my old backups which was probably my old hope of getting it back. I think I'll just end this as world corruption and remember to save my backups.
