### ISSUE TITLE
Snowchestite Line Basalz Dupe

### ISSUE THREAD

**Issue by Emiuna** [Nomi-CEu/nomi-ceu#390]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

Prism

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

The first step of snowchestite processing takes 3 buckets of petrotheum, aka 12 petrotheum dust, aka 12 basalz powder:
![1](https://github.com/Nomi-CEu/nomi-ceu/assets/138958596/d318747f-9a0e-41da-b471-d5e6d66a9b51)

However, the next step gives 8 basalz powder per bucket of naq oxide petro solution, aka 24 basalz powder total:
![2](https://github.com/Nomi-CEu/nomi-ceu/assets/138958596/a93a187c-7980-4f1c-9348-f1d43a55dceb)

### Expected Behavior

You should instead get 4 basalz powder per bucket of petro solution processed, recycling all the basalz without giving any extra.

### Reproduction Steps

Just by doing snowchestite line lol

**Comment by IntegerLimit** [comment]
Fixing this later.
