### ISSUE TITLE
Iron/Steel dust Dupe

### ISSUE THREAD

**Issue by Emiuna** [Nomi-CEu/Nomi-CEu#391]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

Prism

### Environment

Singleplayer

### Mode

Both Modes

### What Happened

By macerating iron doors, you can get more iron out than you put in. It's 6 ingots per 3 iron doors by default, so 2 ingots per door, but each door gives 37 tiny piles of iron (About 4 ingots) when macerated, as well as a tiny pile of steel.

### Expected Behavior

You should get equal amounts of iron from macerating as you put in. The issue probably comes from that the vanilla iron door recipe (6 ingots) is enabled but the maceration step gives back the amount of resources that would be used if the hard iron door recipe was enabled (in GT config), so it could be fixed by properly enabling the hard door recipe or by changing the maceration step to just give 2 iron dust (Or 18 tiny piles or whatever).

### Reproduction Steps

1. Craft iron doors (6 iron for 3 doors)
2. Macerate them (Gives 37 tiny piles of iron each and one tiny pile of steel)

**Comment by Emiuna** [comment]
Also this is somewhat related to issue #365 so my guess is the regular door recipe that uses ingots is probably not meant to be enabled (At least in hard mode)

**Comment by IntegerLimit** [comment]
Yep. I'll fix this later today.

**Comment by IntegerLimit** [comment]
Problem in GT. Please move this to there: https://github.com/GregTechCEu/GregTech/issues. Mention #365 in your issue there too.

Thanks! Hopefully will be fixed over there.

**Comment by IntegerLimit** [comment]
Temp Fix will be happening now, hopefully with a proper fix in gt 2.7.3. (aka 1.7 alphas, betas, or release).

**Comment by IntegerLimit** [comment]
Ah, I accidentally put a closing keyword into that commit. Re-opening...

**Comment by Folanlron** [comment]
Fixed via, https://github.com/Nomi-CEu/Nomi-CEu/pull/452
