### ISSUE TITLE
Thermal  Fluxbore

### ISSUE THREAD

**Issue by theMegaTech** [Nomi-CEu/Nomi-CEu#392]
### Nomi CEu Version

1.6.1-beta-3a

### Related Problem

fluxbore feels useless compared to MV+ GT drills

### Your Solution

move fluxbore to lv (or at least early MV)

### How Will Your Solution Work

if fluxbore will become lv then it will feel ok because only LV GT drill is bad enough (breaks after 2-3 veins literally) to make fluxbore worth it, MV+ are better in range AND don't suffer that much from durability issues

(yeah i KNOW that you can replace drill heads but re-enchanting every time is lame)

### Alternatives You've Considered

remove fluxbore at all? why is it needed if it is outclassed by MV drill when you can get it and it doesn't become better than gt drills with signalum/enderium upgrades

**Comment by IntegerLimit** [comment]
Its kind of an alternative to those who decide to use it instead of GT Drills. Some people like it more, but we might consider removing it, considering its pretty much useless (like the removed vertical digger).

**Comment by Folanlron** [comment]
I like my fluxbore... a lot more then the GT drills ..

**Comment by theMegaTech** [comment]
> Its kind of an alternative to those who decide to use it instead of GT Drills. Some people like it more, but we might consider removing it, considering its pretty much useless (like the removed vertical digger).

alternative shouldn't be much worse than other drills, no? And fluxbore has considerably lower range than hv drill or even mv drill. IMO making it require at least aluminum head will make it worth it cuz you'll have choice between x3 depth and unbreaking drill (that can accept smashing/smelting rn, but might be better to remove those enchantments from fluxbore too), and hv one won't break that easily anyways

**Comment by Folanlron** [comment]
Not everyone wants the gt drills, some people don't need the massive area it drills out...

It's nice to have choices...

**Comment by theMegaTech** [comment]
my main point is making fluxbore lil cheaper yeah

**Comment by Folanlron** [comment]
You don't mine nearly as much as you think even in HM, the chunk miners are just too nice.

**Comment by theMegaTech** [comment]
miners have nothing to do with the topic tho

**Comment by IntegerLimit** [comment]
> I like my fluxbore... a lot more then the GT drills ..

Yeah, some people do like it more, and I do understand the reasons.

**Comment by theMegaTech** [comment]
sooo why exactly does it need to be stainless steel if it is on same level with lv drill? why not aluminum drill head?

stainless steel was ok in GTCE nomi cuz there was no other options BUT in CEU we got proper drills you know

**Comment by IntegerLimit** [comment]
Good Question. I'll have a look at if this needs some balancing, or tweaking of its mining speed/area (if that can be done).
