### ISSUE TITLE
Quest "Auto Chisel" doesn't detect diamond chisels and iChisels

### ISSUE THREAD

**Issue by Nayiko** [Nomi-CEu/nomi-ceu#393]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Quest doesn't mark chisel requirement as complete even when a diamond chisel or iChisel is in the inventory and pressing the detect button.

### Expected Behavior

Quest should detect the chisels.

### Reproduction Steps

1. Create a new world.
2. Unlock the quest "Auto Chisel"
3. Get a diamond chisel or iChisel in the inventory and press detect.

**Comment by IntegerLimit** [comment]
You may have an outdated quest book, or have edit mode on. Try doing these commands, in this order:
`/bq_admin default load`
`/bq_admin edit false`

If you find out that you cannot do this due to cheats being disabled, you can use `Open To Lan` to enable cheats temporarily.

**Comment by Nayiko** [comment]
Did this on a new world. It still happens.

**Comment by IntegerLimit** [comment]
Hmm. I'll have a look at this later.
