### ISSUE TITLE
EnderIO Conduits plus maitinince hatches brick my game at 16 gigs of ram

### ISSUE THREAD

**Issue by industrialmaniac314** [Nomi-CEu/nomi-ceu#394]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

nomi-ceu-client-1.6.zip curse forge

### Configurations or Mods Changed

i was just seting nitrogen for aluminium in my world an the conduit attached to the maitinince hatch and the game stopped responding

### Environment

single player

### Mode

Normal Mode

### What Happened

it bricked my world after i placed a item conduit
[a world.zip](https://github.com/Nomi-CEu/nomi-ceu/files/12045203/a.world.zip)
here's my world if you can un brick it somehow

### Expected Behavior

i expected it to not brick my world

### Reproduction Steps

i just placed a conduit on a maitince hatch

**Comment by Folanlron** [comment]
nomi-ceu-client-1.6.zip This says you are running 1.6, which has the Maintenance hatch bug(and not beta3a which is fixed)

You can find beta3a on the CF page, but as far as the world goes it is gone unless you can get in with WorldEdit and delete the offending conduit(This is still iffy as you have to load the world into WorldEdit without mods)

But you should have backups avail in /backups

**Comment by IntegerLimit** [comment]
Yep. CF Launcher may not launch properly, or perhaps you mistook your version. Please update to v1.6.1-beta-3, and perhaps change launchers, to something like Prism Launcher.

**Comment by IntegerLimit** [comment]
> nomi-ceu-client-1.6.zip This says you are running 1.6, which has the Maintenance hatch bug(and not beta3a which is fixed)
> 
> You can find beta3a on the CF page, but as far as the world goes it is gone unless you can get in with WorldEdit and delete the offending conduit(This is still iffy as you have to load the world into WorldEdit without mods)
> 
> But you should have backups avail in /backups

I think the conduit should not crash the game once you update into 1.6.1-beta-3, unless it caused world corruption.

**Comment by Folanlron** [comment]
> 

It does cause world corruption, that is the main problem with and why I think 1.6 should be yeeted off CF and 1.6.1 released.
