### ISSUE TITLE
Drawer Quest bug still present in expert questbook

### ISSUE THREAD

**Issue by Tahkra** [Nomi-CEu/nomi-ceu#395]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

The ignore NBT tag for the first storage drawers quest in expert mode is still set to false, causing the craft to only complete with an Oak Drawer.

See: https://github.com/Nomi-CEu/nomi-ceu/blob/00497554ff894b7ff172695768d714d6ec41055c/overrides/config-overrides/expert/betterquesting/DefaultQuests.json#L26484

### Expected Behavior

NBT data should be ignored, allowing the quest to complete with any drawerBasic.

### Reproduction Steps

1. Craft a 1x1 storage drawer made from spruce wood.
2. Observe the drawer quest did not update appropriately.

**Comment by IntegerLimit** [comment]
Not sure why this happened again. Very sorry.
