### ISSUE TITLE
Maintenance hatch + item conduit adjacent crashes world

### ISSUE THREAD

**Issue by TRR-Slimer** [Nomi-CEu/nomi-ceu#398]
### Nomi CEu Version

1.6

### Launcher

CurseForge

### Environment

Aternos server, singleplayer

### Mode

Normal Mode

### What Happened

World becomes unjoinable when placing an item conduit adjacent to a maintenance hatch.
Only breaks when maintenance hatch is placed first.
World is fixable with MCEdit by destroying the item conduit.
Client only crashes on singleplayer not on server.
Only occurs with normal maintenance hatch not automatic.

### Expected Behavior

Item conduit is able to be placed next to a maintenance hatch

### Reproduction Steps

1. place maintenance hatch.
2. place item conduit anywhere that would join to the hatch

**Comment by Folanlron** [comment]
Fixed in beta3a, either tell aeternos to allow beta updates in there service, or don't use it.

**Comment by 1006609** [comment]
I corrupted a backup doing this when automating some blast furnaces for aluminum, went to the previous back up, worked my way up to the same point, and then fucking did it again
