### ISSUE TITLE
Omnium doesn't work with circuits in wiremill

### ISSUE THREAD

**Issue by Cethannel** [Nomi-CEu/nomi-ceu#399]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

GD Luancher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

While I was trying to passive 16x wires for creative energy emitter I noticed that the 16x recipe in the wiremill was not working for omnium. It also does not work for 2x or 4x.

Screenshot:
![screenshot](https://i.imgur.com/4YqtH9P.png)

### Expected Behavior

Getting 16x omnium wire.

### Reproduction Steps

1. Set circuit in wiremill to 2, 4, 16
2. Place omnium in input slot

### Additional Information

The recipe shows up in JEI, so this is most likely a bug with gregtech not picking up the circuit in the wiremill for some reason.

**Comment by IntegerLimit** [comment]
Ah. I'll see if I can fix this.
