### ISSUE TITLE
JEI charts terminal app missing "+" button in JEI focus menu

### ISSUE THREAD

**Issue by Xodias** [Nomi-CEu/Nomi-CEu#403]
### Nomi CEu Version

1.6.1-beta-4

### Launcher

Prism

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

The JEI chart terminal app currently doesn't support adding machine recipes with the "+" button in GTCEu releases beyond version 1.5.4, which is included in all pack versions 1.6+.

### Expected Behavior

JEI focus button appears on recipe pages relevant to machine recipes (or all pages, like before the change)

### Reproduction Steps

Install any GTCEu version 1.6+ and JEI (Both included newer versions of the pack by default)
Load up, give yourself a terminal from JEI menu, open JEI charts app.
You'll see JEI focus doesn't add buttons to any machine crafting pages.

### Additional Information

Would need a bansouku patch for newer versions of the pack using the "src/main/java/gregtech/integration/jei/GTJeiPlugin.java" class from version 1.5.4 jar to restore functionality.

Later versions of GTCEu rename the class to "JustEnoughItemsModule.java", so you may need to rebuild from source and edit the class if any other changes were made to it. The issue is caused by the changes in [this commit](https://github.com/GregTechCEu/GregTech/pull/1638/commits/3ed6bf0e13bfe206070a619c40ca76292cc9a87d).

**Comment by Folanlron** [comment]
https://github.com/GregTechCEu/GregTech/pull/2030

**Comment by IntegerLimit** [comment]
No Bansoukou patch, will just fix this as part of 1.7.

**Comment by Folanlron** [comment]
Fixed via , https://github.com/Nomi-CEu/Nomi-CEu/pull/452
