### ISSUE TITLE
Wrong Display Name in Beta4

### ISSUE THREAD

**Issue by Emiuna** [Nomi-CEu/Nomi-CEu#404]
### Nomi CEu Version

1.6.1-beta-4

### Launcher

Prism

### Environment

Singleplayer

### Mode

Both Modes

### What Happened

The application name for beta-4 displays as beta-3a

### Expected Behavior

The application name should say beta-4

### Reproduction Steps

Launching NFu on the beta-4 version

**Comment by IntegerLimit** [comment]
Cannot Reproduce (Thankfully).
