### ISSUE TITLE
1.6.1-beta-4 crash when Effortless Building preview shows up while holding a drive bay

### ISSUE THREAD

**Issue by Dabvexx** [Nomi-CEu/Nomi-CEu#405]
### Nomi CEu Version

1.6.1-beta-4

### Launcher

ATLauncher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

quit to title crash when holding a drive bay with effortless building set to anything other than standard building.

### Expected Behavior

The game not immediately quitting to title.

### Reproduction Steps

1. Turn on an Effortless building mode other than normal
2. Hold a drive bay.
3. Have the game try to show the preview by looking at a block in placement range

### Logs

[crash-2023-07-29_02.11.30-client.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/12206422/crash-2023-07-29_02.11.30-client.txt)

### Additional Information

I would assume this happens because of the shader effect on the preview. not sure why it seems to only happen with drive bays.

**Comment by IntegerLimit** [comment]
You could try turning the shader off in the config, but this is an Effortless Building problem, and most likely won't be fixed (unless a fork is one day made).

Sorry. Closed as won't/can't be fixed.
