### ISSUE TITLE
Crashing when shift clicking recipes into AE2

### ISSUE THREAD

**Issue by DoughnutDev** [Nomi-CEu/Nomi-CEu#406]
### Nomi CEu Version

1.6.1-beta-4

### Launcher

Prism

### Configurations or Mods Changed

Added Fluid Reworks

### Environment

Multiplayer

### Mode

Normal Mode

### What Happened

When you shift click the + in JEI when you are inside a AE2 Terminal it will crash you to the start screen.

Edit: It seems like it happens when the items are missing and it shows red in JEI, but if it is blue it won't crash.

### Expected Behavior

I expected it not to crash, and add the items into the crafting terminal.

### Reproduction Steps

Open the AE2 Crafting Terminal
Shift click a recipe with the + symbol

### Logs

https://mclo.gs/uuW0liU

**Comment by DoughnutDev** [comment]
Further testing I found 3 recipes that if you remove them from the ME interfaces the crashing doesn't happen. As soon as you add any of them the crashing happens again.

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/6487557/079d7826-b554-43ec-9063-7ffb59581104)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/6487557/6cf36384-1f0d-4b5a-8f70-8bf2768b2a4c)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/6487557/e5f3408c-f859-460a-88e7-21bb2a6d217f)

**Comment by Folanlron** [comment]
Seems like Proto made a new release of AE2(that will hopefully fix this) last I heard he was waiting for a malware scan from CF for the upload it is version 0.55.20 (for the possible fix)

**Comment by IntegerLimit** [comment]
The version has been approved. Will be updated soon.
