### ISSUE TITLE
Ender IO Crafter deletes items

### ISSUE THREAD

**Issue by SigmundusFreudusEst** [Nomi-CEu/Nomi-CEu#409]
### Nomi CEu Version

1.6.1-beta-3a

### Launcher

ATLauncher

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

If something tries inserting items into an Ender IO Crafter from the "push" side - those items are irreversibly deleted.

My setup has a GT item pipe which acts as a shared "output bus" for a bunch of machines pushing products to the same inventory. I connected the crafter via the bus, which resulted in hundreds of lost items.

I then tried a smaller scale setup with only a hopper feeding into the crafter, which seems to narrow it down to the crafter's "push" side causing the issue.

### Expected Behavior

Items should not try to enter the Ender IO Crafter from the "push" side. At the very least, items should not get deleted.

### Reproduction Steps

1. Place an Ender IO Crafter
2. Set some recipe and set one side to "push"
3. Insert items into the "push" side using any method (hopper, item pipe)
4. Inserted items get deleted

**Comment by Folanlron** [comment]
This is a simple, "Don't do that"

Use a Mechanical Crafter.

Sadly this isn't something we can fix as we don't have access to the EnderIO Source, as there are several issues in the mod that would be nice to have fixed.
