### ISSUE TITLE
Ender Fluid Cover desync in LAN

### ISSUE THREAD

**Issue by RhenaudTheLukark** [Nomi-CEu/Nomi-CEu#410]
### Nomi CEu Version

1.6.1-beta-4

### Launcher

CurseForge, GDLauncher couldn't run the pack so /shrug

### Configurations or Mods Changed

Added some recipes related to Field Generators (shouldn't pertain to this issue)

### Environment

Open to LAN

### Mode

Normal Mode

### What Happened

Whenever my partner changes a channel on an Ender Fluid Link Cover, it seems that all covers I have set up myself are desynced from that cover, as if the covers were on private mode despite being on public mode.

### Expected Behavior

Channels shouldn't desync in public mode, and if the same channel is used on a cover that myself or my partner has set up, they should connect properly.

### Reproduction Steps

Unfortunately, this error seems to happen weridly, we do not have the exact reason as to why it does not work.
We tried reproducing the steps below, but it seems following them doesn't lead to the bug on a fresh cover channel...
However, we can try to give insight as to what seems to happen. Hopefully that's enough.

1. Player 1 setups a cover with a given channel, on public mode (the button has never be pressed, if that matters) and pushes liquid in it.
2. Player 2 setups another cover with the same channel, on public mode as well (button not pressed).
3. The channel set up by the other player should not have any liquid.

For info, said channels can be anything. We have this case happen for example on channels F000001D or even 00000017.
We use two covers connected to an Super Tank, with liquid input channels labelled following the rule F000XXXX (with X being a number), and output channels labelled following the rule 0000XXXX.

### Additional Information

This is likely caused because covers seem to be in private mode by default, as whenever I reset the channel of the cover, it syncs back up with all the cover I have personally set up.
However, as we weren't easily able to reproduce the problem, it's only speculation.

**Comment by IntegerLimit** [comment]
Sadly, LAN worlds break many mods. You could try hosting a local server, which is quite easy, and the issue shouldn't occur there. You could try submitting it to the GTCEu Github: https://github.com/GregTech/GregTech/issues

**Comment by IntegerLimit** [comment]
Also CF Launcher breaks stuff. Like Everything. Try Prism Launcher, or AT Launcher.

**Comment by RhenaudTheLukark** [comment]
That link you sent seems dead

**Comment by IntegerLimit** [comment]
Sorry about that. Glad you found the correct link, I saw your issue. Thanks!

**Comment by RhenaudTheLukark** [comment]
Update: We discovered that the issue comes from the Chunk Loading Ward from Extra Utilities 2.
We were chunk loading the areas with both FTB Chunks and the Chunk Loading Ward from Extra Utilities 2, which would break the liquid ender covers over and over again.
I would suggest removing this item, or nulling its recipe to fix the issue!

**Comment by Folanlron** [comment]
We will probably add a note that the wards don't work in LAN worlds.

As they work perfectly fine in SP/Real servers, the issue with LAN worlds is that MC is technically "tricking" the world into thinking it is a server, so certain things will never work correctly, this has always been the case sense overall the "LAN" trick is a hack.

**Comment by IntegerLimit** [comment]
@Folanlron I've added the 'LAN Problem' Label for this sort of stuff.

**Comment by RhenaudTheLukark** [comment]
I do want to add that this problem happens even without the double chunk loading issue I brought up, and also happens when the pack is played in singleplayer without LAN, although it happens less, so it might not just be linked to LAN.

**Comment by RhenaudTheLukark** [comment]
After a longer check, the problem hasn't happened again since we removed the wards, so the problem truly came from them.
Might be a good idea to add a warning linked to the item, but other than that, the issue's gone on our end!

**Comment by IntegerLimit** [comment]
Will add warning in QB, and to tooltip of that item. Thanks!

**Comment by IntegerLimit** [comment]
Small rare edge case issue, with no reported cases following this one, so we'll leave it be.
