### ISSUE TITLE
Shell file being released with CRLF, rendering it unusable on linux

### ISSUE THREAD

**Issue by feelingnothing** [Nomi-CEu/Nomi-CEu#411]
### Nomi CEu Version

1.6

### Launcher

None

### Environment

server

### Mode

N/A

### What Happened

`launch.sh` file though being ASCII in git repository
file ./launch.sh output: `launch.sh: POSIX shell script, ASCII text executable`
when installing the latest stable release is saved as dos file with CRLF
`./launch.sh: POSIX shell script, ASCII text executable, with CRLF line terminators`
This leads to `launch.sh` being unusable
`-bash: ./launch.sh: /bin/sh^M: bad interpreter: No such file or directory`

This could be caused by building in windows environment and not specifing encoding when saving the file

### Expected Behavior

_

### Reproduction Steps

_

**Comment by IntegerLimit** [comment]
Known issue, duplicate. Use 1.6.1-beta-4 instead.
