### ISSUE TITLE
Automatic Maintenance Hatch crashing in multiplayer when interacting with Wireless Crafting Terminal

### ISSUE THREAD

**Issue by nicklllmedia** [Nomi-CEu/Nomi-CEu#412]
### Nomi CEu Version

1.6.1-beta-4

### Launcher

GDLauncher, Minecraft Launcher

### Environment

Multiplayer

### Mode

Normal Mode

### What Happened

Me and my friend both crashing when trying to hover over '+' button in HEI, while in _Wireless Crafting Terminal_, trying to shape _Automatic Maintenance Hatch_ recipe. We're in the beginning of IV stage, so all progression structures present.

### Expected Behavior

The _Automatic Maintenance Hatch_ recipe should shape in the crafting grid of _Wireless Crafting Terminal_.

### Reproduction Steps

1. Join multiplayer (_nfu.valhallamc.io_ in our case).
2. Setup ME network and connect _Wireless Crafting Terminal_ to it.
3. Try to shape _Automatic Maintenance Hatch_ recipe from HEI.

### Logs

[crash-2023-08-17_21.17.07-client.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/12372623/crash-2023-08-17_21.17.07-client.txt)

### Additional Information

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/74980009/1e964df0-3655-40e1-ae44-5d904c787038)

**Comment by Folanlron** [comment]
Manually update AE2 on the server/client to anything above 55.20 you can grab the newer AE2:UEL here https://www.curseforge.com/minecraft/mc-mods/ae2-extended-life/files

Inte has been working on getting a new beta/1.6.1 release out but has been busy.

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/Nomi-CEu/Nomi-CEu/commit/59bc49b8924641243b79755870ef2325f9728de8.
