### ISSUE TITLE
Incorrect Power Consumption for Fluxed Electrum with ABS

### ISSUE THREAD

**Issue by WhitePr** [Nomi-CEu/Nomi-CEu#418]
### Nomi CEu Version

1.6.1a

### Related Problem

To make nine "Fluxed Electrum" with ABS you need only 1,080,000EU, but with EBF you need 348,480*9=3,136,320EU, which is almost three times more, which is incorrect, in my opinion.

### Your Solution

Compared with using EBF, using ABS should have a 25% efficiency increase, so I suggest changing the power consumption to 348480×9×0.75=2,352,240EU

### How Will Your Solution Work

modify Fluxed Electrum recipe for ABS

### Alternatives You've Considered

.

### Additional Information

ABS:
![Screenshot from 2023-09-01 02-46-01](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/3533e26e-e8c4-465e-888d-44a3b9aaa974)
EBF:
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/2e441ed2-29e6-43be-9de8-a2fc0360087b)

**Comment by Folanlron** [comment]
That is the benefit of the ABS though, not only does it remove the need for a Mixer(although the item still requires a Vac Freezer/Fluid Soldifier(depending on what it makes))

But if you are cooking only at MV.. You got other problems..


Remember 4 x power for 2 x Speed , so the power consumption of the item skyrockets pretty fast..

I don't really see it as a problem, an EBF will outpace a ABS(In single item cooks)

But nothing comes close to what the Rotary-Hearth Furnace does..

**Comment by WhitePr** [comment]
> Remember 4 x power for 2 x Speed , so the power consumption of the fluid skyrockets pretty fast..

No, ABS has the same "prefect overclock" as EBF. So if you overclock it when your Temperature is over 1100K, it will have a 4x speed boost.
![Screenshot from 2023-09-01 12-45-27](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/a59180b2-bda5-48af-ab13-fdc2808d74b9)


> I don't really see it as a problem, an EBF will outpace a ABS(In single item cooks)

 Yes,single cooks.But it is a material for making Exotic Materials Catalyst.So this problem will show up in the later stage of mass production.
![Screenshot from 2023-09-01 13-02-37](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/7c12fdab-be7a-4d69-9efe-611922db6053)

> But nothing comes close to what the Rotary-Hearth Furnace does..

Although Rotary Hearth Furnace is very good, it is expensive. ABS is very cheap in comparison, so it will be better than Rotary Hearth Furnace in post-production automation

**Comment by Folanlron** [comment]
> > Remember 4 x power for 2 x Speed , so the power consumption of the fluid skyrockets pretty fast..
> 
> No, ABS has the same "prefect overclock" as EBF. Therefore, when the temperature exceeds the required temperature of 1800K, overclocking will increase the speed by 4x ![Screenshot from 2023-09-01 12-45-27](https://user-images.githubusercontent.com/76523578/264913637-a59180b2-bda5-48af-ab13-fdc2808d74b9.png)

This is "built" into the EBF/ABS code, nevermind the 5% discount you get every 900k. and perfect overclock will only happen every 2 tiers of coils.
> 
> > I don't really see it as a problem, an EBF will outpace a ABS(In single item cooks)
> 
> Yes,single cooks.But it is a material for making Exotic Materials Catalyst.So this problem will show up in the later stage of mass production. ![Screenshot from 2023-09-01 13-05-52](https://user-images.githubusercontent.com/76523578/264916848-62c46698-0d33-4c40-9657-3879648ed3ed.png)
> 
> > But nothing comes close to what the Rotary-Hearth Furnace does..
> 
> Although Rotary Hearth Furnace is very good, it is expensive. ABS is very cheap in comparison, so it will be better than Rotary Hearth Furnace in post-production automation

False, very very False the RHF puts the EBF/ABS and even the Volcanus too shame you haven't used it I'm guessing,


Saying it "should" because it is used in the Exotic Material catalyst is not a valid point. Honestly It's fine how it is and if you are just gonna make the same points over and over, Then I will close this as not planned, I don't see the need for increasing the power consumption.

Honestly does it really matter ? After the first heart it is pointless ...

**Comment by IntegerLimit** [comment]
Sounds like an easy fix.
