### ISSUE TITLE
Problems transporting advanced dislocators

### ISSUE THREAD

**Issue by Terofale** [Nomi-CEu/Nomi-CEu#420]
### Nomi CEu Version

1.6.1a

### Launcher

Prism launcher

### Configurations or Mods Changed

LazyAE2

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

When you try to transport advanced dislocators to a super chest using gt cover it only works if the super chest is empty. You can't export to drawers if they have at least one too.

### Expected Behavior

Gregtech covers should be able to transfer advanced dislocators to drawers/superchest that have already one.

### Reproduction Steps

Put an advanced dislocator in a gregtech crate and use a conveyor to export into a super chest or a drawer

### Additional Information

This is probably because the advanced dislocators only stack to 1

**Comment by IntegerLimit** [comment]
Can you test if the same issue happens with other items that stack to 1? (Swords, armor, etc.)

**Comment by Terofal** [comment]
The same issue does happen with all the items that stack to 1

**Comment by IntegerLimit** [comment]
Hmm... Let me do some testing with GT 2.7.3, and then I'll determine what to do next.

**Comment by HandsomeAsianMan** [comment]
gtceu problem
