### ISSUE TITLE
EnderIO Item Conduits stopped trasnferring suger cane to storage drawer

### ISSUE THREAD

**Issue by Diamondskeleton0** [Nomi-CEu/Nomi-CEu#423]
### Nomi CEu Version

1.6.1a

### Launcher

Curseforge

### Configurations or Mods Changed

Added Essential

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

EnderIO Item Conduits suddenly stopped transferring sugar cane, backing up the system. It was working fine before, and I hadn't changed any settings. My other Item Conduit systems work just fine.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/26389466/5bcd8508-f74c-4c96-b7bc-4ceab5df9746)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/26389466/ed7b4a60-1e1b-4ff4-932b-c349f777a851)

### Expected Behavior

Suger cane should go into the storage drawer, which contains a void upgrade to prevent clogs

### Reproduction Steps

1. Set up suger cane farm with snad
2. Wait???

### Additional Information

Everything else is working fine, this just broke. I have no idea why.

**Comment by IntegerLimit** [comment]
Remove and replace EIO conduit. Sadly, EIO Conduits are a little jank, and we can't really do anything about it. If this happens again, just remove and replace.

**Comment by Diamondskeleton0** [comment]
actually, the problem was completely different; i ended up having to replace the vacuum chest instead. For some reason, making an entirely new one was the only working solution. Just wanted to mention it real quick

**Comment by IntegerLimit** [comment]
What? Thats... very weird. Maybe there is some configuration in the vacuum chest that was changed.

Well, I guess the vacuum chest is still from EIO.
