### ISSUE TITLE
Only way to passive lapis is with t4mm

### ISSUE THREAD

**Issue by Terofale** [Nomi-CEu/Nomi-CEu#425]
### Nomi CEu Version

1.6.1a

### Related Problem

Lapis is used in a lot of stuff, like palis crystals and batteries, but at the moment the only way to passive its production is with tier 4 micro miner's gemstone mission. This can be annoying in the mid-game when you don't have the resources to make a lot of these, but also post tank, if you want to passive a lot of things you can't really because you'll run out of lapis. Passiving t4mm only for lapis is a bit too much, and I think there should be other ways to get it.

### Your Solution

You could get lapis from a processing line, like how you can process stone into quartz, or black granite into various components.

### How Will Your Solution Work

This solution would still make lapis not free but obtainable in an easier way.

### Alternatives You've Considered

It could also come from DME, or in the form of a fluid able to be solidified after creative tank is obtained.

**Comment by Folanlron** [comment]
This is Intended , you have other options for getting Lapis(And all gem based ores) none of the gems are can be solidified for a reason, its suppose to add a challenge.

You can also Buy, and Ore Rig Lapis(doing this will get you tons)

**Comment by Terofale** [comment]
The other vanilla gems that you need a lot of (diamonds and emeralds) are obtainable through DML, just though it would make sense for lapis to be obtained more easily

**Comment by IntegerLimit** [comment]
You need to run t4 gems a lot anyways for rhodochrosite and diamonds, its fine.
