### ISSUE TITLE
Specific DME model with certain NBT tags malfunctions when put into a simulation supercomputer

### ISSUE THREAD

**Issue by haydedanny** [Nomi-CEu/Nomi-CEu#426]
### Nomi CEu Version

1.6.1a

### Launcher

Curseforge

### Environment

Aternos multiplayer

### Mode

Normal Mode

### What Happened

Most DME models have 3 tags after usage, dataCount, tier, and totalSimulationCount. But, in the simulation supercomputer, having the dataCount and totalSimulationCount will not make the model work. it must have no NBT data or only the tier tag, this is proven when looking at the JEI window when right clicking any model, it only shows the tier tag.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/99454127/31b59d37-d00c-4d93-abf4-cabfbdc338a0)

### Expected Behavior

It is supposed to work like any other model, occasionally produce a pristine matter based on the tier, and a matter.

### Reproduction Steps

1. Build and form a simulation supercomputer
2. Get some ppc and a used model (By putting it through a DME simulation chamber)
3. Insert the ppc and the used model, it shouldn'y work.
4. Add a crafted model that has not been used, that one should work. Observe the NBT data.

**Comment by IntegerLimit** [comment]
This has been fixed already, in commit https://github.com/Nomi-CEu/Nomi-CEu/commit/758f7e704ca8b13031f7ca859e6bc9c0f0a9e786. Will be included in 1.6.2 (if that will be released), else will be included in 1.7 betas and alphas.

**Comment by haydedanny** [comment]
alright cool
