### ISSUE TITLE
Fatal error, connection terminated

### ISSUE THREAD

**Issue by Diamondskeleton0** [Nomi-CEu/Nomi-CEu#427]
### Nomi CEu Version

1.6.1a

### Launcher

Curseforge

### Configurations or Mods Changed

added Essential

### Environment

Multiplayer

### Mode

Normal Mode

### What Happened

I try to join a server with a nomi CEu 1.6 world and place a block, and a lot of the time, it kicks me off with the message "a fatal error has occurred, connection has been terminated"

### Expected Behavior

I can place a block without getting kicked out of the server

### Reproduction Steps

1. Make a world on 1.6
2. Update to 1.6.1a
3. Join server
4. Place a block

### Additional Information

This only happens if the world is from a previous version of nomi CEu, at least from what I've found

**Comment by IntegerLimit** [comment]
Can you post the crash log? Also, try a different launcher, like Prism, as CF breaks stuff.

**Comment by Diamondskeleton0** [comment]
[latest.log](https://github.com/Nomi-CEu/Nomi-CEu/files/12570089/latest.log)

here's the latest log, the game itself didn't crash so I don't have a crash log

**Comment by Folanlron** [comment]
We can not support Essentials, just way to many quirks with the mod cause of what it does.

As worlds that were upgraded even coming from 1.5 -> 1.6.1a upgrade correctly without essentials, works perfectly fine.
