### ISSUE TITLE
SerializationIsBad 1.4 prevents launching the game without Internet connection

### ISSUE THREAD

**Issue by ntdesmond** [Nomi-CEu/Nomi-CEu#433]
### Nomi CEu Version

1.6.1a

### Launcher

MultiMC

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Upon launching the game, the mod tries to fetch the remote config from GitHub and fails, throwing an error and stopping the game from loading.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/29694249/ba6467fe-d6a5-4ce5-8e70-c97d7ba124e2)

### Expected Behavior

The mod could use a cached copy of the config as a fallback. Actually, the [mod version 1.5](https://github.com/dogboy21/serializationisbad/releases/tag/1.5) does that, check it out.

### Reproduction Steps

1. Disable all the Internet connection (Ethernet, Wi-Fi)
2. Try to launch the game in offline mode

### Logs

[2023-09-19-3.log](https://github.com/Nomi-CEu/Nomi-CEu/files/12656807/2023-09-19-3.log)

### Additional Information

Updating to SerializationIsBad 1.5 manually resolved the issue

**Comment by IntegerLimit** [comment]
Yeah, we will be adding SiB 1.5 next update.
