### ISSUE TITLE
Tier Three Microminer unnecessity

### ISSUE THREAD

**Issue by nicklllmedia** [Nomi-CEu/Nomi-CEu#438]
### Nomi CEu Version

1.6.1a

### Your Solution

As of now progressing through Tier Three Microminer is unnecessary and even unbeneficial.
After completing Creative Tank quest I can tell for sure that mining Perfect Diamonds with Tier One Microminer is way easier than with Tier Three as it mines just 66% per craft while needs way less Fuel/Power/Resources. And same goes for Dilithium, which you need at the same stage of the game. When I planed progression through Tier 8-9-10 Microminers, I realized that setting up a single autocraft for cheap Tier One is way smarter solution than wasting resources and time on Tier Three for Perfect Diamonds and Tier Two for Dilithium. And the most frustrating part about this topic is the fact you are quest blocked later in the game with this same Tier Three which you never ever need.

### How Will Your Solution Work

As it is a complex question covering changes in multiple quest/recipes, I can't suggest a solid solution as it is fully up to creator preferences. Only thing I can state is the fact this part of the questline doesn't work and ruins the experience. And you have a ton of ways to go for solving it:
1. Remove quest for Tier Three
2. Remove dependencies from Tier Three quest
3. Rework Tier Three recipes
...
99. Add custom reward for completion of the quest

### Alternatives You've Considered

...
99. Add custom reward for completion of the quest

### Additional Information

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/74980009/04d3cc0b-7945-4741-9fad-fa04506e5b79)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/74980009/ae107b81-fa38-4e18-bb4e-6bcb453541ec)

**Comment by tracer4b** [comment]
Fixed in #447 by removing dependency on the quest. 
T3 is still useful for Vanadium and the various other ores it brings. We will think more about its balance
