### ISSUE TITLE
Update Genesis power-related quest text to downplay steam dynamo without LV

### ISSUE THREAD

**Issue by sparr** [Nomi-CEu/Nomi-CEu#443]
### Nomi CEu Version

1.6.1a

### Related Problem

The Infinite Water and LV Power quests both have text that strongly suggest the player can/should have already been generating RF power. This is confusing because there seems to be no way to use RF power prior to getting the LV Energy Converter.

### Your Solution

Update those quest texts to eliminate the implication. Maybe even make it explicit that RF power is useless until later.

### How Will Your Solution Work

Changed quest text will better direct new players.

### Alternatives You've Considered

Status quo would remain confusing/misleading.

**Comment by IntegerLimit** [comment]
Or not... Adding in the Changes to qb-dev now.
