### ISSUE TITLE
Titanium Tetrachloride quests requires a bucket

### ISSUE THREAD

**Issue by MatthiasMann** [Nomi-CEu/Nomi-CEu#449]
### Nomi CEu Version

1.6.1a

### Launcher

Minecraft Lauchner

### Configurations or Mods Changed

Disable seasonal events in EnderIO
Reduced ladder climbing speed from 4 to 3

### Environment

Singleplayer / Peaceful

### Mode

Normal Mode

### What Happened

The Titanium Tetrachloride quests requires that the fluid is stored in a bucket while all other fluid quests also accept EnderIO tanks (which is my preferred method for manual chemistry) 

### Expected Behavior

All fluid containers should be allowed for this quest.

### Reproduction Steps

1. Have the Titanium Tetrachloride in an EnderIO tank and try to complete the quest
2. The quest does not detect the liquid
3. Transfer the liquid into a vanilla bucket
4. The quest can be completed

**Comment by Preladon** [comment]
Note this is also true in Hard Mode, without any of the pack changes detailed above.
