### ISSUE TITLE
Visual bug with large conduit/cable networks

### ISSUE THREAD

**Issue by Gamma-Andromedae** [Nomi-CEu/Nomi-CEu#455]
### Nomi CEu Version

1.6.1a

### Launcher

AT Launcher

### Configurations or Mods Changed

Mods Added:
Lazy AE2, Version: 1.12.2-1.1.26
Project Red - Illumination, Version: ProjectRed-1.12.2-4.9.4.120-lighting
Optifine, Version: OptiFine_1.12.2_HD_U_G5

Configs Changed:
advancedRocketry: B:overworldSkyOverride=false
AppliedEnergistics2: B:ColorApplicator=true, B:Channels=true

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

When placing or removing a cable to a large AE2 network (>40 components) or Enderio conduit network (>100 components) the change will happen mechanically but visually will not register for some time (up to 20 seconds sometimes). When placing cables, usually placing another connected to the same network forces previously placed to update but not the one just placed; however, when breaking cables this does not happen and it leaves a "ghost" cable that doesn't exist in the world (noclip, not connected to network) but is visually there.

I cannot reproduce this on an empty creative world building an identical ME Network.
Images attached:
![nomiBugEnderio](https://github.com/Nomi-CEu/Nomi-CEu/assets/84343889/51536416-7675-46f7-a5eb-7e68322c93f0)
![nomiBugAE2](https://github.com/Nomi-CEu/Nomi-CEu/assets/84343889/467cf73e-3680-4809-890a-780bf4034b8b)
![nomiBugAE2Destroy](https://github.com/Nomi-CEu/Nomi-CEu/assets/84343889/f1b7a274-445d-4465-b561-d7feee90f582)

EDIT: Glitch/bug only occurs inside the chunk that contains the largest part of the network (ME Controller with 120 p2p tunnels attached. Enderio power network with DML Polymer Clay and 128 Numismatic dynamos)

### Expected Behavior

Cable/conduits update visually when placing or destroying.

### Reproduction Steps

1. Have a world with a decent amount of machines/networks/cables expected after playing for a while.
2. Construct a large ME network controller using many p2p tunnels and a subnetwork controlling those (Central controller, p2p tunnels on every face all connected to a subnetwork controller) and/or construct a large enderio power system with numismatic dynamos. ME Network image:
![network controller](https://github.com/Nomi-CEu/Nomi-CEu/assets/84343889/cb7dc594-b2ff-4022-b01a-9e3f87f3a888)

**Comment by MatthiasMann** [comment]
I have this too - but it doesn't depend on the amount of EnderIO conduits in that chunk.
In my world this happens primarily in chunk with the oil processing set (4 refineries sharing walls, 4 oil cracking plants stacked on top of each other also sharing walls, fluid rig). So I assume it is related to many multiblock machines.

**Comment by IntegerLimit** [comment]
Optifine breaks a lot of stuff, especially texture rendering. Please uninstall it. However, if you still experience this after uninstalling optifine, EIO is pretty much unfixable, but you can try reporting it to PAE2. However, this is most likely not fixable.
