### ISSUE TITLE
Disconnect on Join: There was a critical exception handling a packet on channel deepmoblearning

### ISSUE THREAD

**Issue by TacticalUnicorn** [Nomi-CEu/Nomi-CEu#463]
### Nomi CEu Version

1.6.1a

### Launcher

All Launchers

### Configurations or Mods Changed

Loliasm updated to 15

### Environment

Sponge Server

### Mode

Normal Mode

### What Happened

Players experience disconnect upon world join while in effected chunks. As of now one base is effected an is unable to be loaded by any players. 

### Expected Behavior

Players should log in

### Reproduction Steps

1. Players joins world
2. Players is disconnected
3. Players and server receive error logs

### Logs

Client Log
https://pastebin.com/Hsc8pNpD
Server log
https://pastebin.com/vtkHfviG

### Additional Information

Cleared Echest data as trouble-shooting step.

**Comment by Folanlron** [comment]
Why did you update Loliasm? ... I'll put money that reverting the version fixes the problem.

**Comment by TacticalUnicorn** [comment]
Thank you for your comment, unfortunately that was the first thing I attempted. Here's error logs when loading with reverted loliasm in singleplayer world. World loads fine again in unaffected chunks, in singleplayer but on bother versions of loliasm game crashes in affected chunks:

https://pastebin.com/fFXTjvNf

(Sponge can not run on loliasm 14 period end of story)

**Comment by Folanlron** [comment]
Then it's probably a sponge problem, there is basic sponge support in GTCEu but we have 0 control over how sponge reacts, it is basically the same thing as what essentials problems cause.

We can't possibly support it, this is just a modpack not a full on dev pack.

There is some updates coming down the pipe, but GTCEu 2.7* is a big update, it might fix the problem but you are gonna have issues with whatever point you are at, as several thing have changed thru the whole of progression.

**Comment by TacticalUnicorn** [comment]
I'm not running sponge on my client and the map isn't opening, there's no clearly sponge related errors in console. I don't understand how this has anything to do with sponge? I  only specifically see DeepMobLearning and storage drawers in console.

I'm aware of multiple large community servers running spongeforge, who have not run into the issue. Is the Official nomi stance on sponge really to drop support for any server running one of the most popular server models for modded because it's easier to point fingers than to find the problem lol. No wonder this pack isn't run on public servers.

**Comment by IntegerLimit** [comment]
Closed (stale).
