### ISSUE TITLE
Can't start the game.

### ISSUE THREAD

**Issue by Shoelacedwithspaghetti** [Nomi-CEu/Nomi-CEu#473]
### Nomi CEu Version

1.6.1a

### Launcher

multimc

### Environment

Game didn't even start.

### Mode

Normal Mode

### What Happened

I am trying to use multimc for nomifactory because curseforge doesnt Linux OS. (Ubuntu 20.0.4)
The game crashes when trying to start.
![Screenshot from 2023-10-22 20-28-56](https://github.com/Nomi-CEu/Nomi-CEu/assets/147988410/fef59a6e-c6a9-41e1-ad1e-1fbddfb74c6b)

### Expected Behavior

Game should start

### Reproduction Steps

1: install nomifactory to multimc
2: start the game
3: game crashes

### Logs

https://mclo.gs/F3SMp40

### Additional Information

The game says that it is likely caused by nuclearcraft

**Comment by MatthiasMann** [comment]
I also run on Linux - what I did is this:
1. downloaded the server files archive
2. unzipped it
3. download the client files archive
4. extract the content of overrides folder and overwrote the files from step 2 with it
5. installed forge-1.12.2-14.23.5.2860.jar  
6. used the vanilla MC launcher and setup a new instance with that forge version and the folder from 2

**Comment by IntegerLimit** [comment]
This is a bad install. Try reinstalling. You could also try using [Prism Launcher](https://prismlauncher.org/) (fork of MultiMC, and better), as it works on linux. (I also use Linux)
Do not use the vanilla MC Launcher. That is a terrible idea.

**Comment by Exaxxion** [comment]
@MatthiasMann There are server-only and client-only mods. This is not a reliable method for installing most modpacks.

**Comment by MatthiasMann** [comment]
I know - it requires some fiddling with most packs - but that way I don't have to use any 3rd party launcher (I don't trust these).
