### ISSUE TITLE
QB#938 - Storage Crates

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#479]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Configurations or Mods Changed

Some edits, but unrelated

### Environment

Singleplayer, new world

### Mode

Expert Mode

### What Happened

Quest description mentions Storage Crates require only wood, but in hardmode storage crates require a steel crate.

### Expected Behavior

Not sure of a good fix.  Even GT wood crates require iron screws.  There doesn't seem to be a pure wood storage option besides chest.

### Reproduction Steps

Not needed, quest book description is incorrect

**Comment by Folanlron** [comment]
Anything to do with the Questbook in the alpha is all behind, right now they are trying to get the pack stable before diving into the questbook more.
