### ISSUE TITLE
can't use advanced SMD diodes to craft IV diodes

### ISSUE THREAD

**Issue by MatthiasMann** [Nomi-CEu/Nomi-CEu#480]
### Nomi CEu Version

1.6.1a

### Related Problem

I was crafting an IV diode for the sterile clean room but had already switched all my circuits over to advanced SMD components - only to discover that I had to use the standard SMD diodes to craft the IV diode block.

### Your Solution

I would like an alternate recipe for the diode blocks which uses the advanced SMD diodes (same amount - doesn't need to be cheaper)

### How Will Your Solution Work

This will avoid the need to keep the crafting for standard SMD diodes around while already having the advanced SMD ones setup.

### Alternatives You've Considered

I had to enter something here - so: blank :)

**Comment by IntegerLimit** [comment]
idk why it was closed

**Comment by MatthiasMann** [comment]
Now on 1.7-alpha2

I also discovered that the MV diode requires the basic diodes and can't use either of the SMD diodes for crafting.

Now the question might be: why do you want to craft an MV diode after already having SMD parts?
Well - in the clean room you either need to use transformers, multiple diodes or all machines of the same tier.
In this case I wanted to use MV for machines which craft the fiber reinforced epoxy circuit boards (the last step requires a clean room).

**Comment by IntegerLimit** [comment]
Simplest way: Make an oredict that allows all of that type of components, and then subsequent oredicts which only accept some. Meaning that each recipe accepts its original component, + all above.

**Comment by a-a-GiTHuB-a-a** [comment]
Maybe something like `diodes`, `diodesSmd`, `diodesAdvanced`?
