### ISSUE TITLE
Ethylene quest needs updating after Naphtha rebalancing

### ISSUE THREAD

**Issue by MatthiasMann** [Nomi-CEu/Nomi-CEu#491]
### Nomi CEu Version

1.7-alpha-1

### Launcher

Minecraft Lauchner

### Configurations or Mods Changed

Only changed backup interval and keybindings

### Environment

Singleplayer / Peaceful

### Mode

Normal Mode

### What Happened

The Ethylene quests states that Severely-Steam Cracked Light Fuel is most efficient for Raw Oil.

But GregTech changed the amount of Naphtha you get from Raw Oil which changes the calculation.

I did some math and came up with this:

50mB Raw Oil -> 75mB Naphtha
1000mB Naphtha -> 500mB Severely Steam Cracked Naphtha (3)
1000mB Severely Steam Cracked Naphtha -> 500mB Ethylene
=> 4000mB Raw Oil -> 1500mB Ethylene

50mB Raw Oil -> 25mB Light Fuel
1000mB Light Fuel -> 500mB Lightly Steam Cracked Light Fuel (1)
1000mB Lightly Steam Cracked Light Fuel -> 50mB Ethylene
=> 4000mB Raw Oil -> 50mB Ethylene
=> 120000mB Raw Oil -> 1500mB Ethylene

50mB Raw Oil -> 25mB Light Fuel
1000mB Light Fuel -> 500mB Severely Steam Cracked Light Fuel (3)
1000mB Severely Steam Cracked Light Fuel -> 250mB Ethylene
=> 4000mB Raw Oil -> 250mB Ethylene
=> 24000mB Raw Oil -> 1500mB Ethylene

Unless I mixed up some values the Naphtha route is vastly more efficient for raw oil.
Luckily still only requires LV machines.

### Expected Behavior

The quest book should point towards the best processing path

### Reproduction Steps

Check oil recipe in JEI - not sure if there is an easier way

**Comment by Folanlron** [comment]
Anything to do with the Questbook in the alpha is all behind, right now they are trying to get the pack stable before diving into the questbook more.

**Comment by IntegerLimit** [comment]
Please continue, we need to iron out these issues, and having people play is definitely the best way to do it.

Think of the previous comment as more of a disclaimer that you are going to see a LOT of issues.
