### ISSUE TITLE
Draconic Evolution Energy Core crashes game

### ISSUE THREAD

**Issue by geradeaus007** [Nomi-CEu/Nomi-CEu#494]
### Nomi CEu Version

1.7-alpha-1

### Launcher

MultiMc

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Game crashes upon placing or having an Energy Core Block or Multiblock from Draconic Evolution present in the world. After updating to the newest Version of the pack.

### Expected Behavior

No crash.

### Reproduction Steps

1. Place Energy Core or join world with Energy Core present.
2. Witness crash.
3. Crashes upon reentering world.

### Logs

https://mclo.gs/vKIfpOd

**Comment by Folanlron** [comment]
Known, and will be fixed in next "alpha" whenever it does come..

**Comment by IntegerLimit** [comment]
Fixed in https://github.com/Nomi-CEu/Nomi-CEu/commit/8fc1c45080f3247f973308aa8824629b98b18a91. You can download pack from https://github.com/Nomi-CEu/Nomi-CEu/actions/runs/6652128590, or just wait for next alpha.
