### ISSUE TITLE
QB Battery Buffer/Energy Converter

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#495]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Configurations or Mods Changed

Some, but shouldn't be impacting Quest Book

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

In my playtest, I created the lv battery buffer as per quest #911.  I then confused myself as to why my ender conduits weren't connecting to it.  After a Do'H moment, I realized that I didn't have the Energy Converter as pre QB#38.

### Expected Behavior

QB#911- Batt buffer only depends on QB#409 - Primer on power.
QB#409 only talks about amps per source into wires, but does not mention RF->EU conversions.

Should QB#911 also depend on QB#38 to ensure the player knows about RF conversions?  Especially since by this point the player has only made the Thermal Expansion Steam Dynamo for power generation.

### Reproduction Steps

New world, but should be visible

### Logs

n/a

### Additional Information

n/a

**Comment by MatthiasMann** [comment]
In my current save game (started a new one with 1.7-alpha-1) I did not make a MV energy converter as I used the MV battery buffer to bootstrap my MV setup from LV power - and then used advanced gas generators to produce power for MV.

So it is not strictly required to use energy converters if you have buffers (they accept lower tier power without issues).

**Comment by Kremnari** [comment]
True, and you can completely sidestep the need for the converters by making a LV steam turbine.  But, that is not how the Quest Book is arranged.

**Comment by Folanlron** [comment]
Anything to do with the Questbook in the alpha is all behind, right now they are trying to get the pack stable before diving into the questbook more.

**Comment by Kremnari** [comment]
Would you like me to hold off a bit then?  I'm currently doing a semi-creative playthrough to detect issues.

**Comment by IntegerLimit** [comment]
> Would you like me to hold off a bit then? I'm currently doing a semi-creative playthrough to detect issues.

No please continue, we need to iron out these issues, and having people play is definitely the best way to do it.

Think of the previous comment as more of a disclaimer that you are going to see a LOT of issues.

**Comment by a-a-GiTHuB-a-a** [comment]
This might be off-topic, but I'm currently in a playthrough. Should I upgrade it to alpha, or would there be too much of a risk of losing the world?

**Comment by MatthiasMann** [comment]
> This might be off-topic, but I'm currently in a playthrough. Should I upgrade it to 1.7-alpha, or would there be too much of a risk of losing the world?

A lot of recipes have changed - eg oil processing got some rebalancing, the assembly line now requires research, glow stone boules are gone and replaced with phosphorus ones - and they all need gallium-arsenic, freezer moved the EV tier etc. So it's likely that your factory will break.

On the other hand there are many nice improvements on 1.7-alpha-1:
- multi block input busses now have a ghost slot for the circuit / recipe selection :partying_face: 
- AE2 input/output busses/hatches
- you get a lot more ethylene from raw oil via severely steam cracked naphtha

Also so far I haven't found any bugs (except quest book enhancements I already posted) - so I would recommend making a new world and join the fun.

**Comment by Kremnari** [comment]
> Think of the previous comment as more of a disclaimer that you are going to see a LOT of issues.
Copy, I shall continue.

> This might be off-topic, but I'm currently in a playthrough. Should I upgrade it to 1.7-alpha, or would there be too much of a risk of losing the world?
If you create a new instance for 1.7 and copy over your world, it would give a better idea of what breaks, and allows your 1.6 to still be playable.

> * you get a lot more ethylene from raw oil via severely steam cracked naphtha
Patriots plastic is worth it!

> Also so far I haven't found any bugs (except quest book enhancements I already posted) - so I would recommend making a new world and join the fun.
Likewise, nothing overly funky found so far.  Just breaking into HV on a clean playthrough

**Comment by a-a-GiTHuB-a-a** [comment]
None of those changes seem to affect me—I'm still in LV pre-circuit-assembler.

**Comment by IntegerLimit** [comment]
> This might be off-topic, but I'm currently in a playthrough. Should I upgrade it to 1.7-alpha, or would there be too much of a risk of losing the world?

Not yet, maybe update on alpha-2 or the first beta, but I deem the current alpha too unstable for a proper playthrough. 

Especially since balancing stuff are going to change a lot.
