### ISSUE TITLE
Hatches and Buses Quest (Expert Mode)

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#496]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Configurations or Mods Changed

Some, but not affecting this

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Might be new to GTceu2.7 but now hatches and buses are made in the assembler with a minimum of glue. 

### Expected Behavior

We might need to add a quest after LV assembler, and before the Electric Blast Furnace to highlight this change.

### Additional Information

Not checked on in Normal Mode

**Comment by Folanlron** [comment]
Anything to do with the Questbook in the alpha is all behind, right now they are trying to get the pack stable before diving into the questbook more.

**Comment by IntegerLimit** [comment]
Please continue, we need to iron out these issues, and having people play is definitely the best way to do it.

Think of the previous comment as more of a disclaimer that you are going to see a LOT of issues.
