### ISSUE TITLE
HM Electric Blast Furnace

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#497]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Configurations or Mods Changed

Some, shouldn't affect this

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

It looks like the Electric Blast Furnace has reverted to requiring regular (cobblestone) furnaces.  In nomi1.6 HM,  the EBF required LV Electric Furnaces.

### Expected Behavior

Is this change desired for Expert Mode?

**Comment by Kremnari** [comment]
This is do to the 1.7 EM gregtech configs being reverted.  I think I saw it's awareness on discord already.

Also of note, in the Gregtech.cfg, the config options for
`
"worldgen options": {
I:additionalVeinsInSection
I:minVeinsInSection
}`
are also different from 1.6 Expert Mode.

**Comment by IntegerLimit** [comment]
> This is do to the 1.7 EM gregtech configs being reverted. I think I saw it's awareness on discord already.
> 
> Also of note, in the Gregtech.cfg, the config options for ` "worldgen options": { I:additionalVeinsInSection I:minVeinsInSection }` are also different from 1.6 Expert Mode.

Yep, tracer copied the config and forgot to change back the values.

**Comment by IntegerLimit** [comment]
Fixed by https://github.com/Nomi-CEu/Nomi-CEu/commit/39355a33827d8c2a3b3f80fe195a938661feb11b.
