### ISSUE TITLE
PBF - Firebrick reverted

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#498]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

It looks like the recipe for Firebricks (for the Primitive Blast Furnace) has reverted to the base fireclay dust recipe.

### Expected Behavior

Looks like the concrete bucket is present, but not the calcite/gypsum recipe.

**Comment by Kremnari** [comment]
See comment on #497, part of the 1.7EM gregtech configs

**Comment by IntegerLimit** [comment]
Fixed by https://github.com/Nomi-CEu/Nomi-CEu/commit/39355a33827d8c2a3b3f80fe195a938661feb11b.
