### ISSUE TITLE
VanadiumSteel Quest requires Pentaoxide?

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#499]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Why does the VanadiumSteel Quest (#837) require the Vanadium Pentaoxide (#810)?

 

### Expected Behavior

I don't think 837 should depend on 810 unless we wanted to create a more involved process for isolating the Vanadium.  
Looking at https://en.wikipedia.org/wiki/Vanadium(V)_oxide#Preparation  it may be possible to create a 3-4 step line to imitate V2O5 production, but not sure of a realistic way to decompose that to elemental Vanadium

**Comment by Folanlron** [comment]
This is actually a left over from when there was a Vanadium chain,

It was removed cause you would only use it to make a few batches of V.Steel and thats it. 

The next time you needed it, Ore Processing gives you so much that it was pointless to keep it around.
