### ISSUE TITLE
Angel Block QB

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#503]
### Nomi CEu Version

1.7-alpha-1

### Related Problem

I noticed that no quests mention the Angel Block from Extra Utilities 2.

### Your Solution

The Fluid Drilling Rig quest is the prime candidate for mentioning the presence of the Angel Block.  The ability to place a block arbitrarily above the water in order to build a FDR is worthy of mention...if not as cool as building supports all the way from the bottom of the ocean

### How Will Your Solution Work

Probably add a mention in the FDR quest to the Angel Block, and given it's cheap cost maybe include it in the Retrieval Tasks.

Or just be extremely subtle and change the icon of the quest to the Angel Block 😈 

### Alternatives You've Considered

Leave the plebs to their own devices?

**Comment by vrejhead** [comment]
there should be trivial things left out of the qb, if small things like this need to be mentioned the qb will become too cluttered

**Comment by IntegerLimit** [comment]
Could be mentioned in fluid rig quest, or in some kind of misc chapter. But not really needed currently I think.

**Comment by MatthiasMann** [comment]
I forgot that block exists …

**Comment by Kremnari** [comment]
It could also be a retrieval task on "Explore Extra Utilities 2 #339."  This way it can be subtly introduced without explicitly giving it a purpose.

**Comment by tracer4b** [comment]
I have added an optional retrieval task to the Fluid Rig quest for the Angel Block
