### ISSUE TITLE
Expert mode crafting recipes reverting/inconsistency

### ISSUE THREAD

**Issue by geradeaus007** [Nomi-CEu/Nomi-CEu#506]
### Nomi CEu Version

1.7-alpha-1

### Launcher

MultiMc

### Configurations or Mods Changed

/

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

1. Naquadria Reactor I and II have assembly line AND crafting table recipes. Allowing for bypassing research.
2. In the crafting table: Crafting Table, Furnace and Chest are vanilla recipes, unlike before.
3. Furnace doesn't require flint anymore in the assembler.
4. Maintanance Hatch circuit has changed from 1 to 8.
5. Clock recipe is vanilla in crafing table and requires plates in assembler (pretty sure it was more complex in 1.6.1a with springs and more).

### Expected Behavior

Recipes stay the same as in the previous expert mode version and don't get way easier or are inconsistent.

### Reproduction Steps

JEI

### Logs

/

### Additional Information

Just noticed a few things breaking while playing with the update.

**Comment by Folanlron** [comment]
Known issue and will be fixed next alpha release.

**Comment by IntegerLimit** [comment]
Naquadah Reactors having two recipes was fixed in https://github.com/Nomi-CEu/Nomi-CEu/commit/0da5fe09716110196a68013282de28ae2c70b691.

**Comment by IntegerLimit** [comment]
> Maintanance Hatch circuit has changed from 1 to 8.

That cannot be changed.
