### ISSUE TITLE
Should Nichrome#158 depend on Vacuum Freezers#150

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#512]
### Nomi CEu Version

1.7-alpha-1

### Launcher

MultiMc

### Configurations or Mods Changed

Updated Gregtech.cfg

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Nichrome ingots require the Vacuum Freezer. Their quest shows up immediately after Kanthal Coils, and the quest description does mention the Vacuum Freezer, but the VF is on a separate quest line.

### Expected Behavior

Just raising a possible point of confusion for new players.

**Comment by IntegerLimit** [comment]
Don't open until fixed in main / PR Merged.
