### ISSUE TITLE
Void Oil is actually not infinite

### ISSUE THREAD

**Issue by FooterMan15** [Nomi-CEu/Nomi-CEu#514]
### Nomi CEu Version

1.6.1a

### Launcher

Prism

### Configurations or Mods Changed

Added "ESSENTIAL MOD"

### Environment

Singleplayer (Open to Essential (Technically LAN) )

### Mode

Normal Mode

### What Happened

Drilling Raw Oil in the Void completely depleted deposits around and stopped the drill, even though JEI says  __deposits are infinite__.

### Expected Behavior

Infinite deposits.

### Reproduction Steps

Make a Drill (In my case, advanced drill (tier 2) );
Place in the Void, drill Oil for a bit;
Eventually, deposits will completely deplete.

### Logs

https://mclo.gs/wDTANoR - Latest.log

### Additional Information

Center of the cross is the drill:
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/71946346/69d3827f-eb0d-48e0-91b2-071a9650e117)
This is a couple chunks to the left:
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/71946346/355ed227-6bf6-4be9-a24c-1ea8c99c5bc2)

**Comment by MatthiasMann** [comment]
From the config file the yield of the void raw oil is between 80 and 81 initially - and once depleted it is 79. So it doesn't really matter.

On the other hand GT has an optimization for a depletion chance of 0: https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/api/worldgen/bedrockFluids/BedrockFluidVeinHandler.java#L236 - so changing it to truly infinite would be beneficial to performance?

**Comment by Folanlron** [comment]
I'm trying to find the way to fix the problem, but it's been so long.

Basically some things changed "Under" the hood and the way the fluid chunks are saved changed drastically.

If you go out to "new" generated chunks the oil should be infinite..
