### ISSUE TITLE
Suggestion allow titatnium cells to store acids

### ISSUE THREAD

**Issue by QuickStick123** [Nomi-CEu/Nomi-CEu#516]
### Nomi CEu Version

1.6.1a

### Related Problem

Stainless steel cells can store acids, titanium is both a higher tier and more known for acid resistance and should also be able too. The same goes for the fluid pipes.

Tungsten Steel cells should probably also be reconsidered especially when the whole limitation can be bypassed by super tanks, portable tanks, drums and fluid tanks.

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/31533893/73f57a90-34dc-4f17-8f66-8b5238954a50)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/31533893/aeb334f0-ef9f-4234-9c26-853fe013be60)

### Your Solution

Allow titanium to transfer/store acids.

### How Will Your Solution Work

Update the material properties.

### Alternatives You've Considered

Nothing really.

**Comment by a-a-GiTHuB-a-a** [comment]
Maybe there's a chemical reason why Titanium Cells can't hold acids or cryogenics?

**Comment by Folanlron** [comment]
This would be a GTCEu issue, take it up with them here, https://github.com/GregTechCEu/GregTech

**Comment by QuickStick123** [comment]
Will do thanks.
