### ISSUE TITLE
Some issues with custom multiblock from Multiblock Tweaker

### ISSUE THREAD

**Issue by BlazeHunterVN1610** [Nomi-CEu/Nomi-CEu#519]
### Nomi CEu Version

1.7-alpha-1

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added:
CompactMachine
GTFO 1.10.0.2
AE2 Fluid Crafting 2.4.32-r
Flux Network 4.1.1.34
ProjectRed Illumination 4.9.4.120

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Actualization Chamber, Naq Reactor MK1 and MK2 doesn't have minium amount of casing, you can spam input/output hatch to form the multiblock
![2023-11-05_01 41 25](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/6a7f02f7-a77a-409e-aee4-793f0373cd09)
Using the multiblock builder to auto-build the Actualization Chamber will not place the casing, but instead a bunch of hatch (for some reason the builder choose ME hatch instead of normal one)

https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/66c6230a-c38e-49a5-9cfd-be16cd6c6f54

The chamber doesn't need both input and output hatch in the multiblock, you only need one of them
![2023-11-05_01 57 39](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/31bb6785-cee5-489d-a9e7-2dbc3cc54444)
![2023-11-05_01 58 16](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/9d531fae-978a-44b4-9872-ae93fcd6b70b)

When you search @multiblocktweaker in JEI, it doesn't show the microverse projector, and ModNameTooltip doesn't even show it's mod name
![2023-11-05_02 06 25](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/23cd4b3e-6a96-4929-a7a5-914d1215c4e8)
![2023-11-05_02 05 22](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/3ba4b94f-d4f8-4a11-8ff1-b0d46c7e3278)

### Expected Behavior

1. Three of the multiblock I mentioned will not form if the amount of casing doesn't meet minimum requirements
2. Actualization Chamber only form if both input and output hatch in the multiblock
3. JEI will show microverse projector if you search @multiblocktweaker

**Comment by Folanlron** [comment]
already been fixed, no clue on next "Alpha" though.. people just busy..

https://github.com/Nomi-CEu/Nomi-CEu/pull/483

**Comment by IntegerLimit** [comment]
Note that the JEI issue for searching with `@multiblocktweaker` cannot be fixed as far as I know.

Actualisation chamber actually doesn't require any bus, as that is what all GT multis do.

**Comment by BlazeHunterVN1610** [comment]
I think I fixed the JEI searching issue
I open `multiblockexpert.zs` file and change `mbt:microverse_projector_basic` to `microverse_projector_basic`
![Ảnh chụp màn hình (67)](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/85aca751-d3c3-442c-bad4-92fd6dbc89cb)
![Ảnh chụp màn hình (70)](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/89d811df-b3e9-4cdf-a1f4-5d79da91f83f)
and `metaitem:mbt:microverse_projector_basic` to `metaitem:multiblocktweaker:microverse_projector_basic`
![Ảnh chụp màn hình (69)](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/50cf7783-a5bf-47bc-a435-859ae5dcb772)
![Ảnh chụp màn hình (72)](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/b9538423-5835-40a3-ae2e-d433fb039af8)
I do the same for the Advanced Microverse Projector I and II, and now JEI shows the projector when I search `@multiblocktweaker`
(the multiblock works normally)
![2023-11-05_18 03 32](https://github.com/Nomi-CEu/Nomi-CEu/assets/111768452/b246e855-cc8e-48e5-b47c-1d6c7d4a49ae)

**Comment by IntegerLimit** [comment]
> I think I fixed the JEI searching issue I open `multiblockexpert.zs` file and change `mbt:microverse_projector_basic` to `microverse_projector_basic` ![Ảnh chụp màn hình (67)](https://user-images.githubusercontent.com/111768452/280519814-85aca751-d3c3-442c-bad4-92fd6dbc89cb.png) ![Ảnh chụp màn hình (70)](https://user-images.githubusercontent.com/111768452/280519821-89d811df-b3e9-4cdf-a1f4-5d79da91f83f.png) and `metaitem:mbt:microverse_projector_basic` to `metaitem:multiblocktweaker:microverse_projector_basic` ![Ảnh chụp màn hình (69)](https://user-images.githubusercontent.com/111768452/280519940-50cf7783-a5bf-47bc-a435-859ae5dcb772.png) ![Ảnh chụp màn hình (72)](https://user-images.githubusercontent.com/111768452/280519944-b9538423-5835-40a3-ae2e-d433fb039af8.png) I do the same for the Advanced Microverse Projector I and II, and now JEI shows the projector when I search `@multiblocktweaker` (the multiblock works normally) ![2023-11-05_18 03 32](https://user-images.githubusercontent.com/111768452/280522105-b246e855-cc8e-48e5-b47c-1d6c7d4a49ae.png)

In my testing, that removed all custom multi items and blocks. If this is not the case in your testing, please comment, and I will add this fix to the PR and retest it.

**Comment by BlazeHunterVN1610** [comment]
When I changed the script, it only remove the old placed controller, nothing else was removed

**Comment by IntegerLimit** [comment]
Yeah, we can't remove people's controllers 👎

**Comment by BlazeHunterVN1610** [comment]
Maybe you can have a script that automatically convert the old placed controller to the new one, or telling people to break all controller before update the pack (because the controller in inventory won't be deleted, but I think no one will like this option)

**Comment by IntegerLimit** [comment]
No need. Maybe consider for 1.8/Nomi Labs/2.0.

**Comment by IntegerLimit** [comment]
The issue of searching in JEI will be fixed.
