### ISSUE TITLE
Ruridit Ingots in End Game requires only 1 ingot

### ISSUE THREAD

**Issue by EvelynTSMG** [Nomi-CEu/Nomi-CEu#520]
### Nomi CEu Version

1.6.1-alpha-1

### Launcher

Prism Launcher

### Configurations or Mods Changed

None relevant

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Unlike surrounding quests, "Ruridit Ingots" in the End Game tab requires only 1 ingot.

### Expected Behavior

Like surrounding quests, "Ruridit Ingots" should require 64 ingots.

### Additional Information

While I encountered the bug in 1.6.1a, the bug appears to still be there in the main branch judging by the config file

I believe the item count for this quest is set in [/overrides/config/betterquesting/DefaultQuests.json:20290](https://github.com/Nomi-CEu/Nomi-CEu/blob/9fc71696fcbb353ee5e892c2aed9f231d1a31be1/overrides/config/betterquesting/DefaultQuests.json#L20290)

**Comment by IntegerLimit** [comment]
Seems to be fixed.
