### ISSUE TITLE
Tungsten quest mentions EV Electrolyzer instead of EV Chemical Bath

### ISSUE THREAD

**Issue by someonelucas** [Nomi-CEu/Nomi-CEu#522]
### Nomi CEu Version

1.7-alpha-1

### Launcher

ATLauncher

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

The first sentence of the quest description mentions the machines required for getting tungsten, but it mentions an EV Electrolyzer insted of an EV Chemical bath. 

### Expected Behavior

The questbook text should list an EV Chemical Bath instead of an EV Electrolyzer.

**Comment by tracer4b** [comment]
Both an EV Electrolyzer and Chemical Bath are mentioned. There shouldn't be a problem
