### ISSUE TITLE
LuV Cable in Questbook

### ISSUE THREAD

**Issue by TimothyNardi** [Nomi-CEu/Nomi-CEu#523]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Configurations or Mods Changed

Flux Networks
Lazy AE2

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

In the questbook, late game page, it declares that Vanadium-Gallium is the cable material for the LuV tier, while it is used in the ZPM tier. The material used is Niobium-Titanium.

### Expected Behavior

I would thus expect Niobium-Titanium to be the material required in the quest.

**Comment by IntegerLimit** [comment]
Fixed by https://github.com/Nomi-CEu/Nomi-CEu/commit/9a911e14032a89a7f25b38e7ac71984cecbfebfd.

**Comment by IntegerLimit** [comment]
Oops, that did not fix this 😓

**Comment by tracer4b** [comment]
This was fixed somewhere along the line
