### ISSUE TITLE
Naquadah Chain bypass

### ISSUE THREAD

**Issue by Kremnari** [Nomi-CEu/Nomi-CEu#525]
### Nomi CEu Version

1.7-alpha-1

### Launcher

MultiMc

### Configurations or Mods Changed

Gregtech.cfg changed to harder recipes

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

The processing of Centrifuged Snowchestite through maceration gives a chance of Naquadah Hydroxide Dust.

This Nq(OH)3 dust can then be electrolysed at MV voltage to provide Naquadah dust, easily bypassing the complete Nq line.

### Expected Behavior

More than likely, the electrolysation recipe is automatically generated, but it should likely be removed.

The Naquadah Hydroxide is the Nq fuel for the LCR recipe.

**Comment by Folanlron** [comment]
This Shortcut is actually 100% Intended..

After a point you will be swiming in Naq Hydroxide, as the actual Naq Process in HM is slow, it is also a "back-up" in case you run out of Naquadah, and space on sending more MMs out for Snowchestnite it is a nice back-up.

The process is working as it should.

**Comment by IntegerLimit** [comment]
This is an intended bypass. Closing...
