### ISSUE TITLE
Oxygen doesn't appear in JEI

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [Nomi-CEu/Nomi-CEu#529]
### Nomi CEu Version

1.6.1a

### Launcher

CurseForge (likely doesn't affect it)

### Configurations or Mods Changed

I changed nothing.

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

I was looking for recipes involving oxygen (the GregTech gas)in JEI, but I couldn't find anything. The two Oxygen variants as well as Oxygen from Advanced Rocketry (which has no texture, but that's a different problem), but not regular old gaseous oxygen. However, oxygen _does_ appear in recipes—maybe something omitted it from the menu?

### Expected Behavior

Gaseous Oxygen should be visible on the main JEI menu.

### Reproduction Steps

1. Go to JEI
2. Search "Oxygen"
3. Find no mention of Oxygen
4. Right-click Oxygen Plasma
5. See Oxygen in the Plasma Turbing recipe!

### Additional Information

Some images for future reference:
<img width="452" alt="Screenshot 2023-11-10 at 17 13 13" src="https://github.com/Nomi-CEu/Nomi-CEu/assets/64599476/68194163-647d-4893-b524-cbda30a16fb1"/>
<img width="688" alt="Screenshot 2023-11-10 at 17 13 27" src="https://github.com/Nomi-CEu/Nomi-CEu/assets/64599476/12fed643-f745-4fb1-aedc-3c1c56c0e793"/>

**Comment by Folanlron** [comment]
https://github.com/Nomi-CEu/Nomi-CEu/issues/307
