### ISSUE TITLE
Sorting inventory while in a wireless crafting terminal delete/voids it

### ISSUE THREAD

**Issue by QuickStick123** [Nomi-CEu/Nomi-CEu#531]
### Nomi CEu Version

1.7-alpha-1

### Launcher

Curse Forge

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

1. Open a wireless **crafting** terminal
2. Sort inventory using middle mouse button
3. Observe your entire inventory disappear

### Expected Behavior

Sorting inventory.

### Additional Information
If you are unable to reproduce I can provide save files if needed.

**Comment by brachy84** [comment]
https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/317

**Comment by IntegerLimit** [comment]
> [PrototypeTrousers/Applied-Energistics-2#317](https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/317)

How was it fixed?

**Comment by brachy84** [comment]
https://github.com/PrototypeTrousers/Applied-Energistics-2/commit/b38148e09515da5fb4c733f6700ad127b1085423
