### ISSUE TITLE
Language Pack for Chinese Players

### ISSUE THREAD

**Issue by zero6six** [Nomi-CEu/Nomi-CEu#532]
### Nomi CEu Version

1.7-alpha-1

### Your Solution

For personal use, I [fork](https://github.com/zero6six/nomi-ceu-zh_cn) a repo from IAmNotGEM (#164) and combine it with official langguage pack to a resourcepack which is suitable for chinese players.It contains updated Chinese language file for GTCEu (provided by a [paratranz project](https://paratranz.cn/projects/7760), because official version is outdated) and questbook (not contain expert mode and some chapters, bilingual quest description).

Aiming to share it with more Chinese players, I open this issue. And nomi-ceu is popular and renowned among Chinese hardcore players but lack stable localization for latest version.

The main translated questbook text before version 1.6 is from IAmNotGEM with high quality.After that, I translate new quest and a few changed old ones by machine translation and polish.But I swear that the translated text can be understand by players and be true to the original.I also provide bilingual description for questbook. And that is all.

### How Will Your Solution Work

Releases from my repo function as normal resourcepack.Just need to load it in the game.

### Alternatives You've Considered

For Chinese Players, I have some optional advices:
1. load this languagepack with a [universal languagepack](https://github.com/CFPAOrg/Minecraft-Mod-Language-Package)(needing to remove gregtech file, for it provide wrong files(because GTCE,GTCEu, etc. use the same modid))
2. if necessary, remove serializationisbad mod or use proxy because it generate crash in downloading files, which is blocked by GFW.

### Additional Information

The main object of this issue is Chinese players.
**If someone was unhappy about that or I disturb someone, I apologize for that.**

**Comment by CrossElectronics** [comment]
Yeah, could use a section in README for different langpacks🤔

**Comment by zero6six** [comment]
> Yeah, could use a section in README for different langpacks🤔

In that case, adding links to Chinese and other language packs(if have) in README or a new tips quest in questbook is just enough.

BTW, is there any official translation project on ParaTranz, Crowdin, etc.?

**Comment by zero6six** [comment]
I'm currently still working on the modpack localization in [my repository](https://github.com/zero6six/nomi-ceu-zh_cn), but noticed that there are some hardcoded strings within the codebase.
https://github.com/Nomi-CEu/Nomi-CEu/blob/00a04e5426d683618643d1e855553cc29385abf8/overrides/scripts/electronics.zs#L65
These hardcoded strings pose a challenge for translation and internationalization efforts.

Would it be possible for you to refactor these strings to use localizable variables instead? I would be very grateful for this change.

**Comment by IntegerLimit** [comment]
Yep, we will be changing these soon. For now, just translate the current translatable texts.

Can you PR it back into this repo? We have decided to officially support translations.

**Comment by zero6six** [comment]
3. To avoid ambiguities caused by translation, the translation of the questbook in my repository is bilingual. The original text is attached with the translation. I implement this via a python script.

And what does “You don't need to wait, its already read” mean? Does this refer to some state of the repository?

**Comment by zero6six** [comment]
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/65449252/c1395c53-2d5a-4330-802f-3fe63fe72910)
There also seems to be some item names that are hardcoded.
