### ISSUE TITLE
Odd Phantom Breaker Behavior

### ISSUE THREAD

**Issue by TimothyNardi** [Nomi-CEu/Nomi-CEu#533]
### Nomi CEu Version

1.6.1a

### Launcher

CurseForge

### Configurations or Mods Changed

Lazy AE2
Flux Networks

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

I was attempting to automate the Ore Drilling Rig to gain access to the improved crushed ore output as compared to a macerator. 

After a period of testing, the first idea that worked was using the Actually Additions' Breaker and Placer to replace the primary Ore Drilling Plant block. In testing I used the Breaker and Placer without issue to successfully break and replace the block to reform the multiblock. The setup I used to do so had the Breaker under the Ore Drilling Plant block and would be unable to withstand repeated use, so I decided to use the Phantom Breaker(PB) to break the primary block.

Here the PB showed an odd behavior. When I first broke the Ore Drilling Plant in a testing setup, it did not appear in the PB. At this moment the PB had not been connected to any broader Item system; it did not have I/O setup. Confused I then repeated the test with a different tier Ore Drilling Plant, Advanced instead of Basic. This time, when the PB was activated, the Advanced Ore Drilling Plant disappeared and the Basic Ore Drilling Plant appeared instead. I then replaced the Basic Ore Drilling Plant and repeated the test again, where the Basic Plant disappeared and the Advanced Plant was instead in the PB.

In order to facilitate better testing I then attached the PB to a Placer, with the Placer in deactivation mode, and the PB in pulse mode. 
![2023-11-12_18 56 08](https://github.com/Nomi-CEu/Nomi-CEu/assets/57360842/3d2218a9-e660-4b98-bfe6-0a9262f0a6d1)
From there the Placer and PB would cycle the two items, with the other Ore Plant appearing only after the current one had been broken, shown below.
![2023-11-12_18 56 08](https://github.com/Nomi-CEu/Nomi-CEu/assets/57360842/67e81d7d-93fb-4628-8415-b05814c09dd3)
![2023-11-12_18 56 13](https://github.com/Nomi-CEu/Nomi-CEu/assets/57360842/8dc1da43-612b-4ecb-be4a-bfa85bee3b0a)
![2023-11-12_18 56 16](https://github.com/Nomi-CEu/Nomi-CEu/assets/57360842/55fc561b-f785-446e-8af6-b90b62b1f37a)
![2023-11-12_18 56 25](https://github.com/Nomi-CEu/Nomi-CEu/assets/57360842/abc2455c-415c-4b91-a040-09c0cc21ae8c)
![2023-11-12_18 56 26](https://github.com/Nomi-CEu/Nomi-CEu/assets/57360842/14f67e41-ebce-46b5-ad76-e90fa2379b8d)
![2023-11-12_18 56 30](https://github.com/Nomi-CEu/Nomi-CEu/assets/57360842/e0512b3f-5573-4358-93a3-ec896fe7c342)

In order to ensure that the issue was not world based, I rebuilt the setup in a creative world, where the issue persisted. In the creative world I ran a number of other tests.
1. Breaking other blocks in between Ore Plants: Using the PB to first break an Ore Plant and then break a block different from the Ore Plants, Neodymium Ore, seemed to not influence the Ore Plant, with the Neodymium Ore appearing in the PB as I would expect. Later breaking of an Ore Drilling Plant showed above behavior, with the first Ore Plant before the Neodymium Ore appearing in place of the new Ore Plant.
2. Breaking the PB in between Ore Plants: After using the PB to break an Ore Plant, I then broke the PB. After replacing the PB and rebinding the location to that of the Ore Plant, I repeated the test. The Ore Plant broken before the PB was broken appeared, and the new Ore Plant disappeared.
3. Breaking and Relocating the PB in between Ore Plants: After using the PB to break an Ore Plant, I then broke the PB. After replacing the PB in a new location and binding the location to that of the Ore Plant, I repeated the test. The Ore Plant broken before the PB was broken appeared, and the new Ore Plant disappeared.

### Expected Behavior

The immediate appearance of the broken block in the Phantom Breaker, as shown by most other blocks.

### Reproduction Steps

1. Place an Ore Drilling Plant of any tier.
2. Place a Phantom Breaker within range of the Ore Drilling Plant, change the mode to pulse, and bind the location of the Ore Drilling Plant to the Phantom Breaker.
3. Activate the Phantom Breaker with a redstone signal.
4. If the Ore Drilling Plant does not appear, place a new Ore Drilling Plant, preferably of a different tier for better visibility and repeat step 3.
5. The first Ore Drilling Plant should have appeared with the second one having diappeared.

### Additional Information

When the viewing the Phantom Breaker, it displayed the name of the Ore Drilling Plant(Any tier) as unnamed.name.

**Comment by Folanlron** [comment]
It is known, its cause of the way GT blocks are stored all under basically 1 ID(Meta ID separates them out). AA has 0 clue how this works, and it is something we cannot fix in current versions.

This has been fixed in the newer version, alpha1 you can just soft hammer any Miner/Drilling Rig to reset the search logic and it will cycle again.

Sadly though, this fix won't be coming to prior versions, too much stuff changed with in GT ..
