### ISSUE TITLE
crash caused by Redstone Arsenal

### ISSUE THREAD

**Issue by MrJefferySmith** [Nomi-CEu/Nomi-CEu#534]
### Nomi CEu Version

1.6.1a

### Launcher

Plain Craft Launcher

### Configurations or Mods Changed

none

### Environment

Before playing on the world

### Mode

N/A

### What Happened

The game crashed when loading, and if file check is disabled the crash won't happen.

### Expected Behavior

No crash

### Reproduction Steps

No replicate

### Logs

crash-report : paste.ubuntu.com/p/rf67CV2tJT

**Comment by MrJefferySmith** [comment]
The game may launch normally with file check abled after relaunching it for some times, or after a sucessful launch with file check disabled

**Comment by IntegerLimit** [comment]
May be due to SiB not having internet connection, try updating that to 1.5. Otherwise, this is caused by a bad launcher, or a bad install. Try using Prism Launcher, and/or reinstalling.
