### ISSUE TITLE
Crafting Table On A Stick voids items

### ISSUE THREAD

**Issue by v-tl** [Nomi-CEu/Nomi-CEu#536]
### Nomi CEu Version

1.7-alpha-1

### Launcher

Prism Launcher

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

Crafting Table on a Stick from Actually Additions voids items remaining in the crafting grid upon closing the UI. 

### Expected Behavior

The remaining items should go to inventory / be dropped.

### Reproduction Steps

1. Open Crafting Table on a Stick from Actually Additions. 
2. Put items into the crafting grid.
3. Close the Crafting Table UI.
4. Items are gone.

### Additional Information

I believe it worked fine previously as I've been using this item quite a lot in my previous runs through the modpack. It might make sense to completely remove this item as Handheld Crafting Table has exactly the same functionality but does not void items.

**Comment by IntegerLimit** [comment]
Yeah we'll probably hide this and have people use the Handheld Crafting Table instead.

**Comment by IntegerLimit** [comment]
This is due to RealBench. Technically, it can be fixed, with mixins.
