### ISSUE TITLE
Crash when teleporting with the Staff of Travelling

### ISSUE THREAD

**Issue by sylvia43** [Nomi-CEu/Nomi-CEu#539]
### Nomi CEu Version

1.7-alpha-1

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

I've gotten a crash like this twice sporadically when teleporting with the Staff of Travelling. The first time it occured when teleporting to a travel anchor, and listed the caused mod on this screen as Dimensional Edibles. I destroyed both the cakes in my void world, and continued playing another ~8 hours before getting this crash in the screenshot. This happned when using the Shift-RClick teleport, possibly at a range that would have clipped into a block. These are the only two crashes in the ~100 uses of the staff within the world.

![4149779c-689e-4eb8-887d-67d166dd97b8](https://github.com/Nomi-CEu/Nomi-CEu/assets/5544386/8d1bf9c8-fb79-4e6f-a116-3a8888cc1cd4)

### Expected Behavior

Game probably shouldn't crash.

### Reproduction Steps

I haven't been able to reproduce it yet, will update if I can find more info.

### Logs

[stacktrace.log](https://github.com/Nomi-CEu/Nomi-CEu/files/13446709/stacktrace.log)
[crashreport.log](https://github.com/Nomi-CEu/Nomi-CEu/files/13446711/crashreport.log)

**Comment by sylvia43** [comment]
Strange, I'm getting this exact same crash immediately every time I try to load the world. I guess we've reproduced it!

**Comment by Folanlron** [comment]
https://github.com/Nomi-CEu/Nomi-CEu/issues/521

Duplicate

**Comment by IntegerLimit** [comment]
@sylvia43 can you post a zip file to your world in #521? Thanks
