### ISSUE TITLE
update Neeve's AE2: Extended Life Additions mod

### ISSUE THREAD

**Issue by XingRenZzz** [Nomi-CEu/Nomi-CEu#540]
### Nomi CEu Version

1.7-alpha-1

### Related Problem

the Neeve's AE2: Extended Life Additions mod in this pack is still in 1.3.1 but the newest version is 1.5.4 (or 1.5.3 for stable release), and it has been added many QoL new items.

### Your Solution

update this mod to the newest version

### How Will Your Solution Work

everyone will be happy

### Alternatives You've Considered

just keep it as in 1.3.1 i guess

### Additional Information

https://www.curseforge.com/minecraft/mc-mods/nae2/files?page=1&pageSize=20

**Comment by Folanlron** [comment]
There is a new alpha coming down the road, they are waiting for some things, this is already planned to be updated.

If you want to update yourself then just update..

**Comment by IntegerLimit** [comment]
Main reason we haven't updated this yet is because we need to make quests. We are awaiting a PR from neeve for that.
