### ISSUE TITLE
Only Able to Scan Lapotronic Energy Orb Cluster with new Lapotronic Energy Orb

### ISSUE THREAD

**Issue by TimothyNardi** [Nomi-CEu/Nomi-CEu#541]
### Nomi CEu Version

1.7-alpha-1

### Launcher

CurseForge

### Configurations or Mods Changed

Lazy AE2
Flux Networks

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

I could only scan the Lapotronic Energy Orb when new and when used, even if empty, I was unable to scan the Orb. I suspect that a similar event would appear when scanning the Cluster or Energy Module in the Research Station, but did not test.

### Expected Behavior

Scanning the Lapotronic Energy Orb, used or not, will produce the needed data.

### Additional Information

I did see that [issue 375](https://github.com/Nomi-CEu/Nomi-CEu/issues/375) seemed related, but still distinct.

**Comment by IntegerLimit** [comment]
Not another NBT issue :weary:
