### ISSUE TITLE
game crashes after rejoining

### ISSUE THREAD

**Issue by complainertheII** [Nomi-CEu/Nomi-CEu#543]
### Nomi CEu Version

1.6.1a

### Launcher

Tlauncher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/152195260/783510dd-44ee-49ef-bf0f-00d3982545f8)
it crashes every time i join a second time, Always. Not even when i don't create worlds

### Expected Behavior

for the game to load properly

### Reproduction Steps

1. join the game
2. leave
3. join back
4. crash screen

### Logs

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/152195260/3d7184c4-c773-4088-b2b8-7920b195131c)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/152195260/7c60cf50-c2a3-48d9-bd1f-a17d08edfe2f)

### Additional Information

i don't know anything about it so if it's a simple problem don't be mad at me, first launch plays perfectly, second loads halfway through and crashes

**Comment by Folanlron** [comment]
Buy the game, use a real launcher..

**Comment by complainertheII** [comment]
would do if i could... no literally im from russia and i tried every other way but i couldn't, not my fault
