### ISSUE TITLE
Processing Arrays fail frequently and stay frozen until the machines refreshed

### ISSUE THREAD

**Issue by BrickedKeyboard** [Nomi-CEu/Nomi-CEu#549]
### Nomi CEu Version

1.6.1a

### Launcher

crafterland

### Environment

multiplayer

### Mode

Normal Mode

### What Happened

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/1306372/e73b320d-1e2f-46ea-98cd-415e8ca79733)
I used a bunch of processing arrays.  This one here has an LuV input hatch, 2 ULV input buses, and one ULV output bus.  It has 16 elite chemical reactor in the machine interface slot and is making master circuit boards.

For no reason at all, with adequate power supplied, the machine will stop working forever.  Removing and placing the 16 ECRs back into the machine will cause it to start again.

This bug essentially breaks the base, the game is not really playable with it.

### Expected Behavior

I expect that the machine, if for some reason in the logic it is stopped, it should periodically do a complete check of the recipe and all inputs, the same check triggered when you remove and replace the machine input.  

### Reproduction Steps

It's a sporadic condition however extremely frequent, your best bet to fix it is to address the failure of the machine to ever restart.

**Comment by MrAutismo** [comment]
happens to me on 1.6.1 with ATLauncher aswell

**Comment by IntegerLimit** [comment]
Cannot reproduce.
