### ISSUE TITLE
Shift clicking in crafting table broken

### ISSUE THREAD

**Issue by MatthiasMann** [Nomi-CEu/Nomi-CEu#563]
### Nomi CEu Version

1.7-alpha-2

### Launcher

Minecraft Lauchner

### Environment

Singleplayer / Peaceful

### Mode

Normal Mode

### What Happened

I used a vanilla crafting table to turn 7 logs into 28 planks - but shift clicking didn't work and normal clicking placed 4 planks in the "hand" (mouse cursor) and after that the output slot of the crafting table was empty. I had to remove and put the logs in again.

### Expected Behavior

Shift clicking should consume the items placed into the crafting table.

### Reproduction Steps

1. Create a new world
2. Get a crafting table and some logs
3. Try shift clicking multiple logs into planks

**Comment by MatthiasMann** [comment]
Also happens when crafting axes

**Comment by MatthiasMann** [comment]
Disabling the mod RealBench-Nomi-CEu-1.0.3 fixes this issue.

**Comment by IntegerLimit** [comment]
Yep, suspected it was our mod. Know why, fixing soon.
