### ISSUE TITLE
Solar Flux Reborn using field accessor make Nomi-CEu not compatibility with Cleanroom Loader

### ISSUE THREAD

**Issue by kappa-maintainer** [Nomi-CEu/Nomi-CEu#577]
### Nomi CEu Version

1.7-alpha-2a

### Related Problem

Solar Flux Reborn uses javax.scripts for its custom solar panel script engine, but this javax module no longer exists in newer Java's Jakarta EE bundle, and there is no replacement. 

### Your Solution

Fork this mod and strip out one script engine class and one reference in mod class. It would be better to strip out hammer lib dependency too, since it's problematic in many ways.

### How Will Your Solution Work

No script engine, no ClassNotFound

### Alternatives You've Considered

Bundling an alternative script engine instead. Candidates are Rhino, Javet, Graaljs, etc.

### Additional Information

Join Cleanroom Discord for more details about Cleanroom Loader

**Comment by kappa-maintainer** [comment]
Fixed in Cleanroom side

**Comment by kappa-maintainer** [comment]
Update: The mod is using fieldAccessor to access NetworkSF.INSTANCE which is a class from same jar. This way is not supported in newer Java anymore and I can't see the necessary to make it final and hackily set it by field accessor. Nomi-CEu need to fork it or make a bansoukou patch to compat with Cleanroom.

**Comment by IntegerLimit** [comment]
> Update: The mod is using fieldAccessor to access NetworkSF.INSTANCE which is a class from same jar. This way is not supported in newer Java anymore and I can't see the necessary to make it final and hackily set it by field accessor. Nomi-CEu need to fork it or make a bansoukou patch to compat with Cleanroom.

Can you link to where it is in the code? It will also be nice if you can fix it in a fork you made, then we transfer it to mixins. Alternatively, you can PR mixins to https://github.com/Nomi-CEu/Nomi-Labs.

Thanks!

**Comment by kappa-maintainer** [comment]
https://github.com/kappa-maintainer/SolarFluxReborn/actions/runs/7314980733
This should work, or do you prefer the Mixin way?

**Comment by IntegerLimit** [comment]
> [kappa-maintainer/SolarFluxReborn/actions/runs/7314980733](https://github.com/kappa-maintainer/SolarFluxReborn/actions/runs/7314980733) This should work, or do you prefer the Mixin way?

Mixins, as bansoukou is unstable, especially with cf launcher and launcher updates.

**Comment by IntegerLimit** [comment]
Not sure how to do this...

https://github.com/kappa-maintainer/SolarFluxReborn/commit/e241ee838cbc79102e0ac774051257485e753371 so this needs to be changed from final to non-final, right?

https://github.com/kappa-maintainer/SolarFluxReborn/commit/89930887f92f57d85152883ad7f0080b711ed212 and this needs to be changed to remove that class.

How do I remove the class? How do I make the field non-final?

**Comment by IntegerLimit** [comment]
Or is it enough to remove the calls to that static class in `SolarFlux.java`?

**Comment by kappa-maintainer** [comment]
If you don't call the class it should be fine
I will make a PR soon, this could be handled by setter mixin and redirect

**Comment by kappa-maintainer** [comment]
Is remap-v2 the latest branch?

**Comment by IntegerLimit** [comment]
> Is remap-v2 the latest branch?

Ignore that branch, pr to main. I pushed all my commits to the wrong branch... its rebased now.
