### ISSUE TITLE
Server started randomly crashing (Beta 2)

### ISSUE THREAD

**Issue by CarePlay34** [Nomi-CEu/Nomi-CEu#578]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Server?

### Configurations or Mods Changed

Nothing/Tried starting the server without the added mods

### Environment

Server

### Mode

Expert Mode

### What Happened

Was working fine before, stopped working after a restart

### Expected Behavior

Server should start

### Logs

[crash-2023-12-11_13.42.29-server.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/13636182/crash-2023-12-11_13.42.29-server.txt)

**Comment by IntegerLimit** [comment]
Caused by Corruption of Universal Tweaks Configs.
