### ISSUE TITLE
assembly line isn't working with hard mode enabled

### ISSUE THREAD

**Issue by kirito78320** [Nomi-CEu/Nomi-CEu#581]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

curse forge

### Configurations or Mods Changed

last versions of flux network , lazy ae2 , ae2 fluid crafting reworks and project red illumination

### Environment

multiplayer

### Mode

Expert Mode

### What Happened

When i try to craft a LuV motor with all necessary fluids and items , the craft don't work

### Expected Behavior

produce a LuV motor by consumming items and fluids needed

### Reproduction Steps

put items
put energy
put data stick with the craft data

**Comment by MatthiasMann** [comment]
AFAIK in hard mode you need to insert all items in the correct order - otherwise it won't craft

**Comment by IntegerLimit** [comment]
Changed this issue to Quest Book: This should be mentioned in the Quest Book (Pretty sure it is, just need to make sure)

Also: There should also be a warning specifically when the items are in the wrong order.

Read the Tooltip!

This should also be in the changelog.
