### ISSUE TITLE
DE energy core requierements

### ISSUE THREAD

**Issue by Tijmender** [Nomi-CEu/Nomi-CEu#593]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

CurseForge

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Draconic Evolution energy core requires activated draconium. When clicking assemble core it either gives an 'expected:  draconicevolution:draconium_block" warning on the GUI, or an "Error: found invalid block at [location]" warning when regular draconium has been placed. Tested with both the T7 and T8 DE energy cores. The same problem occurs with awakened draconium

### Expected Behavior

DE energy core forms with regular draconium blocks or awakened draconium blocks respectively, or a method of creating active draconium blocks is added.

**Comment by IntegerLimit** [comment]
Why did you close this?

Also if you are still having this issue, its because of a bad install/update. Don't press update on your launcher; instead, make a new instance.
