### ISSUE TITLE
Alternate Coated Circuit Board Recipe (I forgot the actual name, but it's the first one)

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [Nomi-CEu/Nomi-CEu#603]
### Nomi CEu Version

1.6.1a

### Related Problem

The Phenolic Substrate (the second tier of board) requires the first tier of board and some phenol. However, the only recipe for the first board is the crafting recipe with Sticky Resin and Wood Planks, which feels weird for this stage of the game, where one has already unlocked the Assembler and is likely using those recipes (the ones that need glue rather than resin, e.g., the resistor recipe).

### Your Solution

Add a new recipe! This could also be used to fix the weird Assembler recipe for the LV circuit board (the one with copper foil and glue), replacing the Wood Plank with the Coated Circuit Board itself (making it more consistent with other recipes).

### How Will Your Solution Work

1 Wood Plank + 100 mB Glue --> 1 Coated Circuit Board in an Assembler

### Alternatives You've Considered

Maybe implementing the recipe for 1 board from 1 plank and 2 sticky resin? The original Nomifactory had this, and it was quite convenient.

### Additional Information

this will probably be rejected tbh

**Comment by MatthiasMann** [comment]
I never automate these recipes - I I craft a stack and rush to the plastic boards

**Comment by a-a-GiTHuB-a-a** [comment]
It's not for automation (I have nothing automated atm)—it's more of a QoL recipe.

**Comment by a-a-GiTHuB-a-a** [comment]
I just realized that changing the Assembler recipe as described wouldn't work—it'd actually be _more_ expensive than the current recipe. However, even without changing that, the update would still be useful.

**Comment by Folanlron** [comment]
Will have to look further once we actually update to GregTech 2.8, or beyond..

A bunch of early game circuit stuff has changed, I don't remember all the changes exactly for it.

**Comment by IntegerLimit** [comment]
Yeah, will relook into this in the gt-2.8 branch, but this solution, or something similar/cheaper, sounds good, if it is not too drastically changed in GT 2.8.

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/Nomi-CEu/Nomi-CEu/pull/821.
