### ISSUE TITLE
Basic/advanced steam turbine consumption

### ISSUE THREAD

**Issue by PatRakowicz** [Nomi-CEu/Nomi-CEu#606]
### Nomi CEu Version

1.6.1a

### Related Problem

Was just wondering what the conversion from the steam turbines. In JEI it only shows basic steam turbine and would like to know the different in energy production and the consumption of steam per machine.

### Your Solution

A lot of testing in creative world, as well as trying to find the conversion between basic/advanced/ultimate

### How Will Your Solution Work

Some testing producing steam from creative tank in to the respective single block steam turbine

### Alternatives You've Considered

Trying to see if the conversion is similar like 12 basic == 6 advanced and the respective steam consumption.

### Additional Information

If I could just get the ratio for each steam machine that would work. Or an update for JEI for the type of steam turbine with respective values.

**Comment by Doniazade** [comment]
Steam generators convert steam at a ratio of 2 steam = 1 EU = RF, except for the multiblock which has turbine efficiency modifiers. But I will add a note to ensure this is properly covered in the quest book. Thanks.
