### ISSUE TITLE
Add quest for singleblock miners

### ISSUE THREAD

**Issue by sylvia43** [Nomi-CEu/Nomi-CEu#611]
### Nomi CEu Version

1.7-alpha-2a

### Your Solution

The fluid mining drills and the basic ore drilling plant both have quests, but it might make sense to have a quest for the singleblock miners.

Suggestions:

- Have a quest in The Beginning for the LV miner to introduce it to the player.
- Add a line to the Large Miners quest to mention the Advanced Ore Drilling Plant available at IV.

### How Will Your Solution Work

It'll point out that the singleblock miners exist as an early option.

**Comment by IntegerLimit** [comment]
Fixed in https://github.com/Nomi-CEu/Nomi-CEu/commit/52357c69f23fdc8d3c4982f3b7eb4d892b01c78f.

**Comment by IntegerLimit** [comment]
Oops... Forgot to Close...
