### ISSUE TITLE
Addressing 2.8 Tungstensteel Progression Tweaks

### ISSUE THREAD

**Issue by windyknight** [Nomi-CEu/Nomi-CEu#621]
### Nomi CEu Version

1.7-alpha-2a

### Your Solution

2.8 dramatically pushed back tungstensteel's obtainability by enforcing the use of RTM alloys. Importantly, the R standing for ruthenium, forces the player to do platline up to stage 2 and send several T3s for tetrahedrite, as that is the only way to obtain ruthenium then. The other method, T4 MM, requires Signalum which needs the RTM coils to smelt. While I personally do not mind setting up platline for it anyway, I do think:
1. Previous versions did not require platline at all. Will this intent carry on or no?
2. Isn't it a bit much ruthenium just to progress?

The other issue is that pushing back tungstensteel also pushes back several non-Greg things that needed it. Notably, the Slice-n-Splice and Soul Binder both need tungstensteel, and consequently the Angel Ring. Will it be intended to push these back all the way to the end of EV?

As such, I suggest the following:
1. Change the tungstensteel in the recipes of the above EIO machines, and others if necessary, to tungstencarbide, which as far as I recall hasn't had its place in progression changed.
2a. Lower the amount of ruthenium necessary to make RTM, my suggestion is changing Ru_4W_2Mo to RuW_4Mo_2, and/or
2b. Provide some way to reaccess ruthenium without platline, such as lowering signalum smelt temp or providing some kind of ore like the custom 80/20 ores that can be oreproc'd into ruthenium in a T3 mission.

### How Will Your Solution Work

Solution 1 allows the mentioned machines and items to retain their place in early EV as they were before.

Solution 2a will still make platline mandatory, but lessen the number of microminers sent, since in my opinion it's a bit too early at this point to have to send multiple miners.

Solution 2b will restore the old progression of platline being optional.

**Comment by IntegerLimit** [comment]
Thank you, this is important.
