### ISSUE TITLE
Possible Unintended Black Steel Recipe in Nightly

### ISSUE THREAD

**Issue by windyknight** [Nomi-CEu/Nomi-CEu#622]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Prism

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Is this black steel recipe intended to be here?
![2024-02-16_05 01 20](https://github.com/Nomi-CEu/Nomi-CEu/assets/9163117/af7983e8-d863-4efe-a7d4-9ac846cab274)

### Expected Behavior

I assume this is the default Gregtech recipe, which should probably be removed in favor of the red coal one?

**Comment by IntegerLimit** [comment]
This issue only occurred in Nightly, so it doesn't need to close with the PR.

Thus, Closing Now.
