### ISSUE TITLE
alloy blast smelter recipes for energetic alloy and vibrant alloy missing (Latest nightly)

### ISSUE THREAD

**Issue by LunarLunarLunar** [Nomi-CEu/Nomi-CEu#625]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

prism

### Environment

singleplayer

### Mode

Both Modes

### What Happened

abs recipes for energetic and vibrant alloy missing

### Expected Behavior

abs recipe for energetic and vibrant alloy should exist

### Reproduction Steps

check jei

**Comment by IntegerLimit** [comment]
Waiting for https://github.com/GregTechCEu/gregicality-multiblocks/pull/67 to be merged.

**Comment by IntegerLimit** [comment]
Fixed a long time ago via https://github.com/Nomi-CEu/Nomi-CEu/commit/31be59de24a4276a502ffeda88a70a080fdd84fc.
