### ISSUE TITLE
item invisible

### ISSUE THREAD

**Issue by sDemonCat** [Nomi-CEu/Nomi-CEu#630]
### Nomi CEu Version

1.6.1a

### Launcher

curseforge

### Environment

forge server

### Mode

Normal Mode

### What Happened

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/161550101/cfb89bcd-deee-4926-be4f-a2eed20edfd0)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/161550101/2f81661a-54a3-4336-82e0-fdcb4ea52990)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/161550101/2a5c8d1e-c1ba-4ea0-9852-1d12aea7bbd0)
After I crafted the EBF, I started place blocks, quest books, item bars, and a lot of things became invisible.

### Expected Behavior

expected craft ebf is normal operation

**Comment by IntegerLimit** [comment]
This is usually caused by changing the resource pack in-game. After you do so, you must restart your instance. See if that fixes it.

**Comment by IntegerLimit** [comment]
Closed as assumed to be normal after proposed fix, as there was no response received afterwards.
