### ISSUE TITLE
Server crash on Turkish locale from littletiles 

### ISSUE THREAD

**Issue by rogerwim** [Nomi-CEu/Nomi-CEu#631]
### Nomi CEu Version

1.6.1a

### Launcher

N/A, is about server packs

### Environment

Forge server with server pack

### Mode

Normal Mode

### What Happened

Server crash on start when locale is Turkish 

### Expected Behavior

Server to not crash

### Reproduction Steps

1. Have/set Turkish locale
2. Run server launch file

### Logs

[crash-2024-02-28_11.16.27-server.txt](https://github.com/Nomi-CEu/Nomi-CEu/files/14431183/crash-2024-02-28_11.16.27-server.txt)

### Additional Information

I’d add the -Duser.country=US -Duser.language=en to server launch file by default

**Comment by Folanlron** [comment]
Take this up with Little tiles , https://github.com/CreativeMD/LittleTiles/issues

**Comment by rogerwim** [comment]
> Take this up with Little tiles , https://github.com/CreativeMD/LittleTiles/issues
> 
> 
> 
> 

I know, but that mod is out of support:

**Comment by IntegerLimit** [comment]
This was fixed by Universal Tweaks, by setting the locale to english if turkish is set.
