### ISSUE TITLE
Able to summon arbitrary items in survival using PackagedAuto

### ISSUE THREAD

**Issue by Iris-xii** [Nomi-CEu/Nomi-CEu#632]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added Fluid Craft for AE2-2.5.7-r.jar, OpenComputers-MC1.12.2-1.8.3+274990f.jar

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

You're able to use PackagedAuto to obtain arbitrary items. This ME creative cell was obtained in survival without using any cheats throughout the process
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/ea08ae3c-b9f8-4435-a327-bf96a9125d7a)
Details about the process down below!

### Expected Behavior

For PackagedAuto to not let you obtain new items from thin air

### Reproduction Steps

1. Encode a Cheap Item -> nothing PackagedAuto recipe:
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/ca3fbc63-4060-4913-a241-5fddaabda11a)
A cheap item.
2. Encode a Target Item -> nothing PA recipe:
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/a70af95f-5f76-440b-90bc-fa71f58f0074)
3. Hover over the package shown in the target item recipe and press 'A' to bookmark it to JEI.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/e869b65f-8c83-465e-927c-863e63fff2e9)
4. Encode another PA recipe of this bookmarked package -> nothing. If you can't drag the item from your JEI bookmarks into the crafting grid, just hover over it and press R to instead put it on the bar of recently viewed recipes, and drag it from there into the crafting table
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/a8099240-e50b-44b7-a1d7-6f505ef45afb)
5. Save the patterns into a packaged recipe holder, and then put it on a (powered) Packager
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/e85072d5-73c5-48d7-b247-fb5e2dda5a93)
6. Put the cheap item into the packager. It'll get bundled into a package (probably intended behavior so far)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/56e1266e-0a37-4407-b8dc-2aa990bf95d9)
7. Grab the packages you just got and put them -back- into the packager. You will obtain a new package containing a package containing the target item (probably unintended behavior) 
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/fcb8a5de-05d2-4ef5-a0ce-af98e57709f3)
8. Shift-right-click the package obtained. You will get -another- package
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/ed973089-e2cb-47be-9c74-ef6af6e56170)
9. Shift-right-click that package you just got. Congratulations! You now have your Target Item!
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/48930896/b2f9197c-55fb-4525-9a40-e1fd6d731e13)

This seems to work for any items you're able to JEI-drag into the PA crafting grid, which is basically all of them. Oops.

### Logs

N/A

### Additional Information

This is probably? a packagedauto bug and not to do with NomiCeu, but I know NomiCEU has plenty of custom stuff, so who knows, definitely not me.

**Comment by IntegerLimit** [comment]
Smart Dupe Bug. Will Look into it.

**Comment by IntegerLimit** [comment]
Please do not close this issue, but create a new issue [here](https://github.com/TheLMiffy1111/PackagedAuto/issues). Lets see if they deal with it.

**Comment by IntegerLimit** [comment]
Also, I believe step 7 is the culprit. It should not be outputting the package of the package of the target item.

**Comment by IntegerLimit** [comment]
Sorry for the confusion, but before you create the issue in their GitHub, can you please try updating both PAuto and PackagedExCrafting (If there is a new version), then seeing if the bug occurs? If it does not, please repost a comment here saying the new PAuto and PackagedExCrafting Version.

Thanks in advance!

**Comment by IntegerLimit** [comment]
Thank you for doing so! If they don't fix it a bit before beta-4, I will try to fix it via mixins in Nomi Labs.

Thanks for finding this issue and your cooperation!

**Comment by TheLMiffy1111** [comment]
Fixed in 1.0.10.39

**Comment by IntegerLimit** [comment]
Thanks!
