### ISSUE TITLE
Problem with crafting CPU waffer with Enderpearl and Diamond Lens on latest nightly

### ISSUE THREAD

**Issue by Kamikzu** [Nomi-CEu/Nomi-CEu#638]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Prism Launcher

### Configurations or Mods Changed

Alpheim version 1.1.1
Red Core version 0.5.1

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

There is a similar problem with black steel, when the server does not craft CPU waffer with Diamond and Enderpearl Lens

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/6589daeb-0cee-478a-b520-c2184790ca4d)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/46d31bf5-8d86-47d8-8a79-c90c76d00ea3)

### Expected Behavior

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/e552854c-d358-432e-990a-422bf55877ca)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/016ba2be-9476-4d7d-abb6-f1a5c98ed868)

### Reproduction Steps

1. start launch.bat from server.zip
2. log in
3. create a design from CEF and Laser Engraver and put either Enderpearl or Diamond Lens in it

### Additional Information

I assume the problem is similar to what was happening with Emerald Lens. Perhaps this problem is also present with other lenses

**Comment by IntegerLimit** [comment]
Should be the same issue as Black Steel. That one damn groovy file!

**Comment by IntegerLimit** [comment]
Can you take a screenshot of the recipes in JEI, hovering over the blue i button, or the cross if it is a cross?

**Comment by IntegerLimit** [comment]
I've closed this issue for now. If Launching on Nightly `f11c63d` doesn't fix the issue, please comment.

**Comment by IntegerLimit** [comment]
Fixes https://github.com/Nomi-CEu/Nomi-CEu/commit/f11c63d529d0a6d56c67cecd5e201253c9d79de3
