### ISSUE TITLE
Problem with craft output hatch/bus in the latest nightly version

### ISSUE THREAD

**Issue by Kamikzu** [Nomi-CEu/Nomi-CEu#639]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Prism Launcher

### Configurations or Mods Changed

Alpheim version 1.1.1
Red Core version 0.5.1

### Environment

Forge Server and Singleplayer

### Mode

Normal Mode

### What Happened

I can't scraft an output hatch/bus using the recipes
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/70c8ed7a-5b1c-4f7c-81f2-4bc29d772e71)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/6444f80c-d8d2-4bfa-9b75-51bf9decc8ca)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/497f75c9-e5a4-440b-ae99-ba71bdb9a7a1)

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/0d2e33f3-2777-4c0d-aaa8-d5724c01f8f1)

### Expected Behavior

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/711c1f88-b3c4-42e6-a32b-f586a82c2300)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/2942b929-4df2-464d-9b63-1507a97b1da5)

### Reproduction Steps

1. open JEI
2. type Output hatch/bus
3. try to craft

### Additional Information

I see that the problem is identical input and output hatch/bus recipes

**Comment by IntegerLimit** [comment]
I see. For now, you can use the Input -> Output conversion recipe.

Looking at it.

**Comment by Kamikzu** [comment]
> I see. For now, you can use the Input -> Output conversion recipe.
> 
> Looking at it.

Is this recipe the main one now?

**Comment by IntegerLimit** [comment]
No, its just a temporary fix you can use.

**Comment by IntegerLimit** [comment]
Fixed by https://github.com/Nomi-CEu/Nomi-CEu/commit/e0c1aad2c19575bc913c8b57fa6be2ac4504ac09.
