### ISSUE TITLE
Stacking 2 Rubber Wood Slabs and then breaking them deletes them

### ISSUE THREAD

**Issue by Avalarr** [Nomi-CEu/Nomi-CEu#640]
### Nomi CEu Version

1.6.1a

### Launcher

CurseForge

### Configurations or Mods Changed

- ae2-uel-v0.56.3
- nae2-1.6.1
- Fluid Craft for AE2-2.5.7-r
- libnine-1.12.2-1.2.1
- lazy-ae2-1.12.2-1.1.26
- compactmachines3-1.12.2-3.0.18-b278
- Chunk-Pregenerator-1.12-4.4.2

### Environment

Singleplayer in Overworld

### Mode

Normal Mode

### What Happened

- Placed two Rubber Wood Slabs in the same block space to make a full block
- Mined them (with bare hand and various tools) and it didn't drop the slabs

### Expected Behavior

It should have dropped the slabs like it does with every other wood.

### Additional Information

I know I have a lot of mods added, but it shouldn't make a difference. Got someone else on the Nomi CEu Discord server to test it and it happened to them as well.

**Comment by IntegerLimit** [comment]
Can you test if the same issue occurs in [GT 2.8 Nightly](https://nightly.link/Nomi-CEu/Nomi-CEu/workflows/testbuildpack/dev%2Fgt-2.8?preview)?

**Comment by Avalarr** [comment]
Is that another modpack? How do I install it? 😳

**Comment by IntegerLimit** [comment]
Download the client zip, import into your favourite launcher.

For CurseForge, follow steps 5 and 6 of this [guide](https://serverminer.com/article/how-to-install-a-custom-modpack-on-your-computer-curseforge/).

**Comment by Avalarr** [comment]
> Can you test if the same issue occurs in [GT 2.8 Nightly](https://nightly.link/Nomi-CEu/Nomi-CEu/workflows/testbuildpack/dev%2Fgt-2.8?preview)?

Works fine in this one.

**Comment by IntegerLimit** [comment]
Closed as fixed in nightly.

**Comment by IntegerLimit** [comment]
Oops. Reopened this.
