### ISSUE TITLE
Central monitor can't access to power station's data

### ISSUE THREAD

**Issue by Alanxtl** [Nomi-CEu/Nomi-CEu#644]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

PCL2

### Environment

singleplayer, 1.7-alpha-2a

### Related Problem

central monitor can't access to power station's data in energy mode
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/25652981/5173fd2f-a94e-44d3-908a-cf1d231b18df)

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/25652981/55682108-f036-4f6b-bb03-915268b6eef5)

### Your Solution

Compatible with power station like battery compartments

### How Will Your Solution Work

none

**Comment by IntegerLimit** [comment]
Will be fixed next GTCEu update (After 2.8.7).

The fix is already merged into their master branch. See https://github.com/GregTechCEu/GregTech/commit/fd65290173b5de45c22ad1e0398bfd3714b70689.

I will close this when a GTCEu update is made, and is updated on main.
