### ISSUE TITLE
Bug with signalum satchel quest

### ISSUE THREAD

**Issue by Icebodhi** [Nomi-CEu/Nomi-CEu#648]
### Nomi CEu Version

Nightly

### Launcher

Prism Launcher

### Configurations or Mods Changed

Alpheim version 1.1.1

### Environment

Forge server

### Mode

Normal Mode

### What Happened

Unable to complete quest due to signalum now being in nomi labs.
![javaw_atvevyItjw](https://github.com/Nomi-CEu/Nomi-CEu/assets/136127932/9a2bc864-2ccf-44c9-963f-a14831047199)
![javaw_mYdfIyH2Fp](https://github.com/Nomi-CEu/Nomi-CEu/assets/136127932/6906c22a-7ef8-469f-999c-b424e809cc24)
![изображение](https://github.com/Nomi-CEu/Nomi-CEu/assets/136127932/6ac76644-f7df-4452-9786-3f1f995cf8c0)

### Expected Behavior

Complete quest

### Reproduction Steps

1. Open quest book on the mid-game page.

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/Nomi-CEu/Nomi-CEu/commit/cc36c58d0395d3641e796ce5e6b10c1a65ba64f7.
