### ISSUE TITLE
Bug with the quest "The Outer Islands" where don't exist item

### ISSUE THREAD

**Issue by Kamikzu** [Nomi-CEu/Nomi-CEu#651]
### Nomi CEu Version

Nightly

### Launcher

Prism Launcher

### Configurations or Mods Changed

Alpheim version 1.1.1

### Environment

Forge server Nightly 0893668

### Mode

Normal Mode

### What Happened

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/b8681dea-47ca-4411-be18-e31fcaddd846)

### Expected Behavior

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/113759044/610096bb-c5df-4c79-9369-cf786e6716ad)

### Additional Information

I think this is happening with other things that have been moved to Nomi Labs as well

**Comment by IntegerLimit** [comment]
Fixed with https://github.com/Nomi-CEu/Nomi-CEu/commit/cc36c58d0395d3641e796ce5e6b10c1a65ba64f7.
