### ISSUE TITLE
Extremely slow start time caused by HEI during Indexing Ingredients

### ISSUE THREAD

**Issue by RRKS101** [Nomi-CEu/Nomi-CEu#654]
### Nomi CEu Version

1.6.1a

### Launcher

CurseForge Launcher

### Configurations or Mods Changed

JVM Arguments: `-Xmx6144m -Xms256m -Dminecraft.applet.TargetDirectory="C:\Users\the4g\AppData\Roaming\.curseforge\Instances\Nomifactory (GTCEu Port)" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -Duser.language=en -Duser.country=US -DlibraryDirectory="C:\Users\the4g\AppData\Roaming\.curseforge\Install\libraries" -XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M`

### Environment

Singleplayer during modpack startup. 

### Mode

Normal Mode

### What Happened

Game took approx. 30 minutes to start due to FML stage 6, Had Enough Items, Indexing ingredients. While indexing ingredients the game was not doing _anything_. CPU utilization was ~3% with no thread ever fully loaded, No disk or network usage nor logging output - it is as if the mod is `Thread.sleep`ing. 

### Expected Behavior

Expected a significantly faster start time of ~1 minute, not 30.

### Reproduction Steps

1. Launch the game via Curseforge and press play on the Minecraft launcher. 
2. The issue should present itself while approaching the end of the FML loading screen.

### Logs

[latest.log](https://github.com/Nomi-CEu/Nomi-CEu/files/14568505/latest.log)

### Additional Information

This does not occur in `Pack version 1.5.2` and prior but does in `Pack version 1.6` and up to `Pack version 1.6.1a` with the issue mostly resolved in `Pack version 1.7-alpha-1`. 
Only `1.5`, `1.5.2`, `1.6`, `1.6.1a` and `1.7-alpha-1` have been tested explicitly.  `1.7-alpha-1` is slower than `1.5.2` with regards to indexing ingredients however as mentioned above it is negligible.

**Comment by IntegerLimit** [comment]
Try using another Launcher, such as Prism Launcher. CurseForge Launcher screws so many things up.

**Comment by IntegerLimit** [comment]
Cannot Reproduce.
