### ISSUE TITLE
seeds can't be broken when planted

### ISSUE THREAD

**Issue by maimvice13** [Nomi-CEu/Nomi-CEu#657]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

prism launcher

### Configurations or Mods Changed

Default settings

### Environment

dedicated server launched via Cubecoders AMP software
![server software](https://github.com/Nomi-CEu/Nomi-CEu/assets/5694271/241f8763-39f1-43d7-b283-d827ca650a55)

### Mode

Normal Mode

### What Happened

Seeds and other planted food can't be broken.

Both types; player planted or village generated

### Expected Behavior

can be broken

**Comment by playX18** [comment]
I experience the same bug on 1.7 nightly, the only way to break them is break the block under the seeds

**Comment by lynxx131** [comment]
Oh... I noticed this with Sugarcane a few weeks again when I first started trying 1.7 where you can't break the bottom cane I just assumed it was intentional behaviour for some reason.

**Comment by IntegerLimit** [comment]
Oh yeah this was an intentional change, I see how it can be annoying. Will revert.

**Comment by IntegerLimit** [comment]
@playX18 @maimvice13 You can shift to break the seeds.
