### ISSUE TITLE
Some name replacements in "resources/modpack/lang" are not working

### ISSUE THREAD

**Issue by Namacha-10514** [Nomi-CEu/Nomi-CEu#660]
### Nomi CEu Version

1.6.1a

### Launcher

GDLauncher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Some name substitutions on "resources/modpack/lang" do not seem to be working.

### Expected Behavior

All name changes apply.

### Additional Information

I feel it needs to be fixed and improved, including moving it to "gregtech/lang".

**Comment by IntegerLimit** [comment]
Which name replacements?

**Comment by Namacha-10514** [comment]
```
metaitem.circuit.energy_flow.name=Crystal Processor
metaitem.circuit.nano_processor_assembly.name=Nanoprocessor
metaitem.circuit.processor_assembly.name=Microprocessor
metaitem.circuit.basic_electronic.name=Electronic Circuit
metaitem.circuit.basic.name=Primitive Circuit
metaitem.board.phenolic.name=Phenolic Substrate
metaitem.circuit.wetware_super_computer.name=Wetware Processor Array
```

That's all.

**Comment by IntegerLimit** [comment]
Those are old, are not meant to work.

**Comment by Namacha-10514** [comment]
Then these keys doesn’t have to translates?

**Comment by IntegerLimit** [comment]
Yes.
