### ISSUE TITLE
Version 1.6.1a or higher crash when launching

### ISSUE THREAD

**Issue by drazigu** [Nomi-CEu/Nomi-CEu#661]
### Nomi CEu Version

1.6.1a

### Launcher

TLauncher

### Environment

didnt even load

### Mode

Normal Mode

### What Happened

launched the game but instead got error message

### Expected Behavior

game turning on

### Reproduction Steps

1. get TLauncher
2. download Nomifactory CEu version 1.6.1a
3. launch game

### Logs

https://github.com/Nomi-CEu/Nomi-CEu/files/14624556/2024-03-16-6.log

**Comment by CommandantWagyu** [comment]
Experienced the same issue, resolved by updating SerializationisBad to version 1.5.2 instead of 1.4.

**Comment by drazigu** [comment]
i  replaced it and it still doesnt work

**Comment by CommandantWagyu** [comment]
On the Nomifactory discord in the announcements channel there's a potential solution to this, hope it works for you.

https://discord.com/channels/927050775073534012/927053122151530517/1218408318301769768

**Comment by LemurVladimir** [comment]
Yeah, thanks to Github updating their certificate, some mods are broken. To fix your particular problem, in /config/serializationisbad.json change the value of "remoteConfigUrl" to "https://serializationisbad.dogboy.io/serializationisbad.json".

Source: https://github.com/dogboy21/serializationisbad/issues/83

**Comment by drazigu** [comment]
doesnt work  i cant even play the modpack anymore

**Comment by drazigu** [comment]
turning it on and off multiple times somehow fixed it? but thanks for the help

**Comment by IntegerLimit** [comment]
Update to 1.6.1b. Fixed there. Will close this when Main Nightly has the fix.
