### ISSUE TITLE
Cupronickel quest requires invar ingot instead of copper

### ISSUE THREAD

**Issue by lynxx131** [Nomi-CEu/Nomi-CEu#667]
### Nomi CEu Version

Nightly

### Launcher

Prism Launcher

### Environment

dev/gt-2.8 commit 881f95b tested in single player expert mode

### Mode

Expert Mode

### What Happened

As per the screenshot, the curponickel quest asks for invar and nickel ingots instead of nickel and copper.
![qb_screenshot](https://github.com/Nomi-CEu/Nomi-CEu/assets/12794418/edb2d977-e7eb-4eaf-810e-e1b6faba2876)

### Expected Behavior

Quest should require a copper ingot instead of an invar ingot.

**Comment by tracer4b** [comment]
Invar is another metal needed for future procedures including the EBF right after this. It's supposed to be there
