### ISSUE TITLE
No recipe for GCYM alloy

### ISSUE THREAD

**Issue by Herminos** [Nomi-CEu/Nomi-CEu#668]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Hello! Minecraft Launcher

### Configurations or Mods Changed

Changed LoliASM: onDemandedAnimation to false
Added AE2FCR 2.5.8-r
Lazy AE2 1.1.26
Optifine HD_U_G5
Flux Network 4.1.1.34
Project Red: Illumination 
Tinker's Construct 1.12.2-2.13.0.183

Update AE2UEL to 0.56.4

### Environment

Singleplayer

### Related Problem

I am in IV now, and I want to make a multiblock version of some machine to get rid of those slow single-block machine .
And I found there's no recipe to make some of their alloys, neither by mixer-EBF nor alloy blast smelter.
eg. Zeron-100, Watertight Steel.

### Your Solution

Add these alloy's recipe in the new version.

### How Will Your Solution Work

It will make GCYM more useful.

**Comment by Herminos** [comment]
I also hope there's a new way to make steel rather than Primitive Blast Furnace
I don't think when we use Fusion to make new element, we use what stone age human to make steel is something reasonable

**Comment by windyknight** [comment]
Are you sure you checked the right recipe? You need to look for the **molten** liquid form for the GCYM alloys.

Also for steel, don't worry, GTCEu 2.8 (which is already deployed in the nightly version of this pack) implements a new fun recipe for steel in the EBF once you hit EV and Kanthal.
