### ISSUE TITLE
Various non-GT original materials breaking

### ISSUE THREAD

**Issue by SparkedTheorem** [Nomi-CEu/Nomi-CEu#673]
### Nomi CEu Version

Nightly

### Launcher

Prism Launcher

### Configurations or Mods Changed

Updated Neeve's AE2 to 1.6.1
Added AE2 Fluid Crafting 2.5.3-r
Added Flux Networks 1.12.2-4.1.1.34
Added Lazy AE2 1.12.2-1.1.26

changed EnderIO Configs to make Telepad and Rod of Return take no fluid to use, also made Rod of Return cheaper to use power wise and faster

### Environment

Singleplayer on nomi-ceu-devgt-2.8-081e806-client

### Mode

Normal Mode

### What Happened

![2024-03-22_17 02 56](https://github.com/Nomi-CEu/Nomi-CEu/assets/162088357/0e50c82f-9e5b-4d32-be29-fb61623c86ee)
![Screenshot_40](https://github.com/Nomi-CEu/Nomi-CEu/assets/162088357/ca50cb5e-fc2d-4a53-9bab-70b404a8c853)

All my non-Gregtech original supercons (read: basically all my wires that werent Arsenic Iron Samarium Oxide) turned into Aluminium wires upon dragging my world over from alpha 2 to the latest nightly, breaking a lot of shit. However, upon further inspection, it seems that a large number of my patterns pertaining to metals that aren't originally from GregTech have broken somehow.

### Expected Behavior

All the wires that turned into Aluminium Wires should have stayed in their original form (Signalum or End Steel wires)

### Reproduction Steps

1. Download nightly version nomi-ceu-devgt-2.8-081e806
2. copy-paste save from alpha 2 to new nightly instance
3. click yes on all warnings that pop up when transferring world over

**Comment by SparkedTheorem** [comment]
![Screenshot_41](https://github.com/Nomi-CEu/Nomi-CEu/assets/162088357/fb167eb9-b299-43a8-819a-26bf25ec29de)

After deleting my save and copy-pasting my world from alpha-2 again, my save seems completely fine now. No broken recipes, no wires transformed into aluminium.

**Comment by IntegerLimit** [comment]
Probably just a bad transfer, or something interrupted the process.
