### ISSUE TITLE
Assembly Line does not work when using Data Module

### ISSUE THREAD

**Issue by qksuki** [Nomi-CEu/Nomi-CEu#674]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

PCL2

### Environment

Singleplayer, downloaded form github _Alpha Release 1.7-alpha-2a_.

### Mode

Normal Mode

### What Happened

Assembly Line does not work when entering an archive and using the Data Module for the first time. When I go into the game and use Assembly Line to make something, he doesn't work. When I take the Data Module out of the Data Bank and put it back in, it works. This definitely happens the first time I enter the archive, and it triggers this bug from time to time in subsequent builds, especially when crafting items with AE2, where the frequent stops are annoying.

I realized that this could be a GTCEU bug, so I created a new game with only the GTCEU mod loaded. I noticed that 1.7a2 was using greg 2.7.4 and reproduced the problem in a new archive. So I tested the latest version of greg 2.8.7 again and the problem has been fixed.

For more information and pictures check out Reproduction Steps

### Expected Behavior

Update the GTCEU version or fix this bug.

### Reproduction Steps

a. nomi 1.7a2

1. Making items using _Assembly Lines_.
![1](https://github.com/Nomi-CEu/Nomi-CEu/assets/105899310/8cfc373e-d325-49ee-93a2-15ed170f30d8)

2. Noticed the _Assembly Line_ wasn't working.
![2](https://github.com/Nomi-CEu/Nomi-CEu/assets/105899310/b101c34c-b401-4f8c-b74f-0a3d8111de5a)

3. Take the Data Module out of the Data Bank and put it back in, it works.
![3](https://github.com/Nomi-CEu/Nomi-CEu/assets/105899310/ad836415-00b6-4a7c-83a1-2c2e60f09b92)
![4](https://github.com/Nomi-CEu/Nomi-CEu/assets/105899310/48487204-9f80-490b-8fd1-1ebd6479f9df)

4. This happens from time to time and causes AE2 to be unable to continue synthesizing items. The first time you enter the game archive, the above problem must occur, but other occurrences cannot be 100% reproduced.

b. GTCEU 2.7.4 in new minecraft 1.12.2

1. Create a new archive and reproduce the above situation
![d0c1c5fa63bb2eb188ddcda7b3cf5511](https://github.com/Nomi-CEu/Nomi-CEu/assets/105899310/6d54309c-dd8c-4148-befc-9b4f184d3106)

2. Take out the Data Module and put it back, it works.
![73999b7f1a23a3fa0441f3ffb435e82c](https://github.com/Nomi-CEu/Nomi-CEu/assets/105899310/433e6402-a69d-490e-a8a0-17ed521a995f)

c. GTCEU 2.8.7
The above bug did not occur. It might be fixed.

**Comment by IntegerLimit** [comment]
Test again with 1.7-alpha-3 (coming in around 1-2 hours)

**Comment by IntegerLimit** [comment]
Oh I didn't see the other part, mentioning its fixed in GTCEu 2.8.7. Fixed by https://github.com/Nomi-CEu/Nomi-CEu/pull/619.

**Comment by qksuki** [comment]
> Oh I didn't see the other part, mentioning its fixed in GTCEu 2.8.7. Fixed by #619.

Thanks for your work! It is a wonderful modpack.
