### ISSUE TITLE
Add Discord Rich Presence

### ISSUE THREAD

**Issue by steph-lion** [Nomi-CEu/Nomi-CEu#679]
### Nomi CEu Version

1.7-alpha-3

### Launcher

Prism Launcher

### Configurations or Mods Changed

None

### Environment

Singleplayer

### Your Solution

I would like to have a discord rich presence as we did for modern nomi. It is just a little gem that could be nice to see on discord.

### How Will Your Solution Work

I would suggest Simple Discord RPC, which is basically the first one shown and the one used on modern.

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/52045633/13005491-0a26-4196-80e3-b6629933d0b0)

**Comment by theMegaTech** [comment]
for an alternatime i'd propose [CraftPresence](https://www.curseforge.com/minecraft/mc-mods/craftpresence) because of quite wider customizability, but overall nice idea yeah

**Comment by IntegerLimit** [comment]
Hope something like this was what you were looking for!

Auto-updating tiers!

<img width="698" alt="image" src="https://github.com/Nomi-CEu/Nomi-CEu/assets/103940576/6c51394c-841d-470c-88db-fa540a5d037b">

**Comment by steph-lion** [comment]
Yeah, very very nice!
