### ISSUE TITLE
Stocking Bus/Hatch copy

### ISSUE THREAD

**Issue by MaGeBZz** [Nomi-CEu/Nomi-CEu#680]
### Nomi CEu Version

1.7-alpha-2a

### Launcher

Prism Launcher

### Environment

Singleplayer

### Related Problem

You can't easily use stocking busses for oreproc for example and it would be pretty nice and make the stocking bus/hatch more viable, if you could copy/paste the settings of it

### Your Solution

I would love to see the feature to copy the exact stocking bus/hatch settings with left clicking a datastick on it + right click to paste it in another stocking bus/hatch

### How Will Your Solution Work

Described above

### Alternatives You've Considered

I mean if it's left click to copy and right click to paste is debatable maybe but I would say there are no good alternatives
Eventually even adding a stocking bus/hatch that can auto-pull items from the whole network (like subnet for example)

**Comment by IntegerLimit** [comment]
https://github.com/GregTechCEu/GregTech/pull/2419
