### ISSUE TITLE
Final LV and MV circuit recipe output lowered

### ISSUE THREAD

**Issue by dustinpedlar** [Nomi-CEu/Nomi-CEu#690]
### Nomi CEu Version

1.7-alpha-3

### Launcher

Prism Launcher

### Configurations or Mods Changed

Disabled Worley Caves
Added Fluid drawers

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Before updating to Alpha 3, the final tier LV, MV and corresponding HV circuit recipes produced two of each circuit but now they only produce once. Is this intended or a side effect of updating GT to 2.8?

### Expected Behavior

Expected to produce two but only produced one.

**Comment by IntegerLimit** [comment]
This is intended, as part of the new circuit balancing introduced in GT 2.8.
