### ISSUE TITLE
RTM alloy coils are incorrectly referred to as tungstensteel by the quest book.

### ISSUE THREAD

**Issue by Urizel** [Nomi-CEu/Nomi-CEu#693]
### Nomi CEu Version

1.7-alpha-3

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

RTM alloy replaced tungstensteel as the material for 4500K coils. However in the questbook:
- they're still referred to as tungstensteel by the quest text;
- the respective quest is gated by tungstensteel despite it not being required.

![2024-03-27_16 53 39](https://github.com/Nomi-CEu/Nomi-CEu/assets/5451636/c2cd0ea7-d39e-445a-9deb-14d1b1fe36cd)
![2024-03-27_16 58 41](https://github.com/Nomi-CEu/Nomi-CEu/assets/5451636/7a7eef9a-a980-4a94-9eba-f36e447b811b)

### Expected Behavior

1. Quest text uses actual coil name.
2. Quest is gated behind T3 miner since it seems to be the only way to get ruthenium needed for the alloy.

**Comment by IntegerLimit** [comment]
Probably already fixed in the QB pr, but that wasn't included in alpha-3.

**Comment by a-a-GiTHuB-a-a** [comment]
I got Ruthenium from Inert Metal Mixture in the platline—I've only gone up to T2, and it should be theoretically possible to get through to it pretty early on in progression (maybe even before the microverse!)

**Comment by SparkedTheorem** [comment]
Ruthenium is obtainable from Tier 3 Micro Miner

**Comment by tracer4b** [comment]
Fixed in 31bdd3d
