### ISSUE TITLE
Normal Oil replacing Raw Oil

### ISSUE THREAD

**Issue by CarePlay34** [Nomi-CEu/Nomi-CEu#701]
### Nomi CEu Version

1.7-alpha-3

### Launcher

Prism

### Configurations or Mods Changed

Ender Utilities, AE2 Fluid Crafting and Lazy AE2. These shouldn't interfere with whatever is happening.

### Environment

Server

### Mode

Expert Mode

### What Happened

![2024-03-29_18 15 33](https://github.com/Nomi-CEu/Nomi-CEu/assets/122828262/69447293-35e4-47f1-84ec-013749cc4d35)
Normal Oil has taken over, no more Raw Oil in Void DIM. 

### Expected Behavior

Raw Oil should be the only Oil present

### Reproduction Steps

Just load up the Void DIM in Alpha 3, I think ?

**Comment by a-a-GiTHuB-a-a** [comment]
This was an intentional change, if I remember right.

**Comment by IntegerLimit** [comment]
Apparently the change has massively debuffed Naptha, which is needed in large quantities for HM.

**Comment by IntegerLimit** [comment]
Intended. The yield from Oil now is the same as the yield from Raw Oil before.
