### ISSUE TITLE
Nomi Labs' Thermal Expansion series of alloys has formulation issues

### ISSUE THREAD

**Issue by WhitePr** [Nomi-CEu/Nomi-CEu#705]
### Nomi CEu Version

1.7-alpha-3

### Launcher

Prism

### Configurations or Mods Changed

AE2FC 
LazyAe2

### Environment

singleplayer

### Mode

Expert Mode

### What Happened

The Thermal Expansion alloy fired using Nomi Labs’ Thermal Expansion alloy powder is the Thermal Expansion alloy rather than the Nomi Labs alloy, but most Thermal Expansion alloys have no other effects.

Moreover, the synthetic exotic material catalyst only supports Nomi Labs alloys and does not support thermal expansion alloys.

![Screenshot from 2024-03-31 14-52-19](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/3f219f46-542e-4f48-b6b1-8be70c85bdbc)
![Screenshot from 2024-03-31 14-52-04](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/29e11db4-2852-4d22-bf47-941cfc75656b)
![Screenshot from 2024-03-31 14-52-00](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/3bd4ed5b-a9cb-4458-b4f4-c2dd0b6a26d1)

![Screenshot from 2024-03-31 14-50-21](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/686902eb-e368-453e-9358-09176ec6f04e)
![Screenshot from 2024-03-31 14-50-14](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/232384ed-d00d-449e-a730-309a614e9b4c)
![Screenshot from 2024-03-31 14-50-10](https://github.com/Nomi-CEu/Nomi-CEu/assets/76523578/be8e218f-8be4-45f0-b8b9-90718aedd512)

### Expected Behavior

Firing Thermal Expansion Alloy Powder from Nomi Labs produces Thermal Expansion Alloy from Nomi Labs instead of Thermal Expansion Alloy

### Additional Information

因该是Nomi Labs的问题导致没有完全覆盖Thermal Expansion的合金导致的,修复起来因该不难

**Comment by WhitePr** [comment]
Redstone Arsenal's Fluxed Electrum Ingot also owns this issue

**Comment by IntegerLimit** [comment]
I know the issue, I forgot to update HM's gt config...

**Comment by IntegerLimit** [comment]
Wait, its updated?

**Comment by IntegerLimit** [comment]
I can't reproduce this.

**Comment by WhitePr** [comment]
> I can't reproduce this.

It has been fixed in alpah4
close issues
