### ISSUE TITLE
Dye Recipes broken

### ISSUE THREAD

**Issue by CarePlay34** [Nomi-CEu/Nomi-CEu#709]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Prism

### Configurations or Mods Changed

Nothing Significant

### Environment

Multiplayer

### Mode

Expert Mode

### What Happened

Cannot make any dye

### Expected Behavior

I mean it's me again, I tried reinstalling the pack, tried making the dyes in an LCR, HV Chem, LV Chem and MV Chem, nothing worked. Like I said, reinstalled the pack on both my server and client, nothing changed.

### Reproduction Steps

Just the normal sulfuric, salt + color to make Dye. Doesn't work.

**Comment by CarePlay34** [comment]
Kinda fixed, the default GT recipe needs to be made, and then the custom ones work. Still something that should get looked into.

**Comment by IntegerLimit** [comment]
Yes, this is intended. Unless the recipes with the normal colors are shown in JEI, everything is working as intended.

(JEI Cleanup in Action)
