### ISSUE TITLE
ZPM Adjustable Transformer lacks the word "Adjustable"

### ISSUE THREAD

**Issue by a-a-GiTHuB-a-a** [Nomi-CEu/Nomi-CEu#721]
### Nomi CEu Version

1.6.1b

### Launcher

CurseForge (doesn't matter)

### Configurations or Mods Changed

Added AE2FC

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

I looked at JEI uses for the small Vanadium-Gallium spring (irrelevant), where I realized that the ZPM Adjustable Transformer was still called the "Zero Point Module Transformer", which is the same as its lower-amp counterpart.

### Expected Behavior

I would expect it to be called the "Zero Point Module Adjustable Transformer", or at least have "Adjustable" in it.

### Reproduction Steps

1. go to JEI
2. look for the ZPM transformers
3. find the two with the same name for some reason

### Additional Information

this is probably patched in alpha. womp womp

**Comment by Underio3298** [comment]
This issue has indeed been resolved in the alpha build and the ZPM adjustable transformer is now named `ZPM Voltage Power Transformer`. The thread can be closed by a maintainer. Thank you.
