### ISSUE TITLE
cannot craft ulpic wafer via sapphire lens

### ISSUE THREAD

**Issue by Ult1mateNoob** [Nomi-CEu/Nomi-CEu#723]
### Nomi CEu Version

1.7-alpha-3

### Launcher

pcl2

### Configurations or Mods Changed

chinese language resource pack

### Environment

forge serverpack

### Mode

Expert Mode

### What Happened

the production of ulpic wafer via sapphire lens cannot proceed in MV laser engraver, however it is doable with blue glass lens instead

### Expected Behavior

Expected to produce ulpic wafer with silicon wafer and sapphire lens.

### Reproduction Steps

1. put sapphire lens and silicon wafer in an MV powered MV laser engraver
2. nothing happens in the engraver

**Comment by Ult1mateNoob** [comment]
just tested in singleplayer it works fine, might something went wrong with expert mode config? 
i ran the mode switch bat and it did not work right, since when i was trying to craft steam age machines. so then i manually overrided the config and it did fixed the steam machines crafting, now i got up with the issue mentioned above.

**Comment by MatthiasMann** [comment]
this is the same bug as https://github.com/Nomi-CEu/Nomi-CEu/issues/708

**Comment by Ult1mateNoob** [comment]
closed due to duplicate. Thanks!
