### ISSUE TITLE
Visual bug in create world screen on widescreen

### ISSUE THREAD

**Issue by millennIumAMbiguity** [Nomi-CEu/Nomi-CEu#725]
### Nomi CEu Version

1.6.1b

### Launcher

Curse forge

### Environment

When creating the world on the "Choose Your World"

### Mode

Both Modes

### What Happened

"Next" button has visual issues.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/37588844/c6114428-dc43-4a9f-898e-b0341a2b72f2)

### Expected Behavior

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/37588844/731d197c-efb0-4109-87d2-36436d66f7aa)

### Reproduction Steps

1. Go to the "Choose Your World" screen
2. expand the window width to 2650px or more

**Comment by IntegerLimit** [comment]
Fixed here: https://github.com/Nomi-CEu/Nomi-Labs/commit/08e2c72ea6cc3c791abfe094b51d6395c1c7599a

Will update soon.
