### ISSUE TITLE
Make Microverse Casings have Wrench as Best Tool

### ISSUE THREAD

**Issue by SparkedTheorem** [Nomi-CEu/Nomi-CEu#726]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added AE2FCR, Flux Networks and LazyAE2
Modified EnderIO Telepad to take no fluid, modified EnderIO Rod of Return to use no fluid and be cheaper to use

### Environment

singleplayer with LAN on

### Related Problem

The Microverse casings using a pickaxe as their best tool pisses me off to no end when attempting to relocate or fix the multiblocks as I use a wrench to break a hatch or whatever and then get stopped and have to switch to my drill for the casings and then back to my wrench when hitting the controller or something. Let me use my Tungstencarbide wrench to instabreak most of the stuff >:(

### Your Solution

Make Microverse Casings have Wrenches be the tool that breaks them fastest instead

### How Will Your Solution Work

Microverse Casings would still be able to be mined by a pickaxe like other GT casings but like other GT casings Wrenches would mine them most effectively.

**Comment by IntegerLimit** [comment]
Fixed Here: https://github.com/Nomi-CEu/Nomi-Labs/commit/314aa25717b7bc50118af827b478b2e29de1cfe2

Will update soon
