### ISSUE TITLE
Add the component/circuit assembly lines to CEu

### ISSUE THREAD

**Issue by AAlp22** [Nomi-CEu/Nomi-CEu#728]
### Nomi CEu Version

1.7-alpha-4

### Launcher

CurseForge

### Configurations or Mods Changed

Added AE2FCR.

### Environment

Singleplayer

### Related Problem

Components and circuits take way too long to assemble, especially when you need/want hundreds.

### Your Solution

  Add component and circuit assembly lines to assemble components and circuits in stacks, instead of one by one

### How Will Your Solution Work

Scan components/circuits with research station.
Assemble wraps of ingredients.
Use said wraps to assemble components and circuits en masse.

**Comment by Folanlron** [comment]
Take it up with CEu here.

https://github.com/GregTechCEu/GregTech/issues
