### ISSUE TITLE
ZPM energy hatch uncraftable without already having zpm

### ISSUE THREAD

**Issue by kirito78320** [Nomi-CEu/Nomi-CEu#732]
### Nomi CEu Version

1.7-alpha-4

### Launcher

curse forge

### Configurations or Mods Changed

added flux network , ae2 crafting rework

### Environment

multiplayer

### Mode

Expert Mode

### What Happened

To make ZPM energy hatch you need uranium rhodium dinaquadide  to make research station , but to cool the ingot you need a zpm vacuum freezer , so you can't craft the research station and the zpm energy hatch
![2024-04-20_16 32 51](https://github.com/Nomi-CEu/Nomi-CEu/assets/44950353/d2139c4e-d0a3-4fba-9593-a166eebc768c)
![2024-04-20_16 32 58](https://github.com/Nomi-CEu/Nomi-CEu/assets/44950353/71c6cd69-2527-4d24-b999-785ddf5702e0)

### Expected Behavior

change the craft or the voltage to reach the zpm energy hatch

**Comment by kirito78320** [comment]
And same thing with assembly line that ask for zpm energy to craft the research station

**Comment by IntegerLimit** [comment]
I think you figured it out... You can use two LuV hatches.
