### ISSUE TITLE
Duplicated recipe for magnet cards in Inscriber

### ISSUE THREAD

**Issue by AnteSocial** [Nomi-CEu/Nomi-CEu#733]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Prism

### Configurations or Mods Changed

Added AE2 fluid crafting 2.5.7, Lazy AE 1.1.26

### Environment

Singleplayer, 1.7 alpha-4

### Mode

Normal Mode

### What Happened

Inscriber recipe page in JEI lists 75 pages of recipes, 71~ of which are duplicated recipes for the magnet card due to every chiseled variant of redstone and lapis blocks being listed, adds unnessecary clutter.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/40402996/bbcaa343-6013-4907-aabe-4d75ec4d56a1)

### Expected Behavior

JEI should list one recipe for the magnet card with the default redstone and lapis blocks, along with the other incscriber recipes for AE2 processors.

### Reproduction Steps

1. Search for Inscriber with JEI
2. Right click on Inscriber
3. View recipe tab for Inscriber

**Comment by IntegerLimit** [comment]
Would be fixed with https://github.com/AE2-UEL/Applied-Energistics-2/pull/430.

**Comment by IntegerLimit** [comment]
Will be fixed when we update to ae2 `0.56.5`, but GS also needs to update its api and util functions for ae2 first. If this does not happen soon, we may PR it to them, or just implement it into Nomi-Labs.
