### ISSUE TITLE
unknow bug to crash save

### ISSUE THREAD

**Issue by qianbing233** [Nomi-CEu/Nomi-CEu#735]
### Nomi CEu Version

1.7-alpha-4

### Launcher

prism Launcher

### Configurations or Mods Changed

mcjtylib-1.12-3.5.4 (1)
xnet-1.12-1.8.2-zh_cn-2023-5-3
jecharacters-1.12.0-3.7.2
hecharacters-1.12.2-1.4.0 (1)
Fluid+Craft+for+AE2-2.4.12-r
FluxNetworks-1.12.2-4.1.1.34
[平滑字体] SmoothFont-mc1.12.2-2.1.4

### Environment

singleplayer

### Mode

Normal Mode

### What Happened

today i update game from nomi-ceu 1.7 alpha 1 to 1.7 alpha 4 ,when i launch game ,it crash twice . before i succseful lauch game in the thrid lauch . but i don't to join my save ,when i change laucher too and i reinstalling again

### Expected Behavior

visualores crash game

### Logs

https://paste.gg/p/anonymous/0b037b31d0014f3e9d3bcf4b3b1a0796

**Comment by IntegerLimit** [comment]
Corrupted Save. Reload from Backup.
