### ISSUE TITLE
DME Simulation Supercomputer not forming/unforming

### ISSUE THREAD

**Issue by Tijmender** [Nomi-CEu/Nomi-CEu#738]
### Nomi CEu Version

1.7-alpha-4

### Launcher

CurseForge

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

DME Simulation Supercomputer was formed and functioning properly for about 200 iterations. After manually inserting some more polymer clay it unformed. The tooltip showed structure incomplete, whereas the GUI showed invalid structure. Debugging using the terminal showed that the issue seems to be the empty space inside the cube of omnium blocks. Breaking and replacing those fixes the problem temporarily, however after some iterations the multiblock unforms again

### Expected Behavior

For the multiblock to form and not break

### Reproduction Steps

1. Build the DME simulation supercomputer multiblock. I used LV input and output busses, and automated maintenance hatch, and two UV energy input hatches (position of all of those didn't solve the problem)
2. Run ender dragon model for a couple of stacks
3. multiblock breaks
4. (Maybe using alt+tab to exit the game temporarily whilst having the player inventory open played a role)

**Comment by IntegerLimit** [comment]
Will take a look at it. Can you send the `latest.log` and the `debug.log` (located in `/logs` folder)?

**Comment by Tijmender** [comment]
[latest.log](https://github.com/Nomi-CEu/Nomi-CEu/files/15248406/latest.log)

**Comment by IntegerLimit** [comment]
`debug.log`?

**Comment by Tijmender** [comment]
There is no debug.log in my /logs folder

**Comment by Tijmender** [comment]
The quickest in-game temporary fix seems to be placing and then breaking a block in the hollow centre

**Comment by MatthiasMann** [comment]
Do you have a feral flare lantern (or how it's called) nearby which places these invisible lights?

**Comment by Tijmender** [comment]
I removed the Feral Flare lanterns nearby and let it run for a while. That seems to have fixed the problem. Thanks! Do I close the issue?

**Comment by IntegerLimit** [comment]
Uh, not yet. I will consider allowing any block in empty spaces. Thanks to @MatthiasMann for considering that factor, and saving me a lot of time!

**Comment by IntegerLimit** [comment]
Fixed. Will Update Nomi-Labs in Nomi-CEu Soon!
