### ISSUE TITLE
Questbook tungstensteel / RTM coil dependency is backwards

### ISSUE THREAD

**Issue by unplannedlunch** [Nomi-CEu/Nomi-CEu#743]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

No configs or mods changed

### Environment

Singleplayer v1.7-alpha-4

### Mode

Normal Mode

### What Happened

The midgame chapter of the quest book places RTM coil blocks after tungstensteel (and calls them tungstensteel coils).

### Expected Behavior

 RTM coils are required to EBF tungstensteel, so these quests' dependency relationship should be swapped.

**Comment by Folanlron** [comment]
Already fixed on QB end.

https://github.com/Nomi-CEu/Nomi-CEu/issues/693
