### ISSUE TITLE
multiblock structures don't form with laser target hatches

### ISSUE THREAD

**Issue by FaccoCris** [Nomi-CEu/Nomi-CEu#744]
### Nomi CEu Version

1.7-alpha-3

### Launcher

CurseForge

### Configurations or Mods Changed

Added Fluid Craft for AE2 version 2.5.6

### Environment

Multiplayer Forge server

### Mode

N/A

### What Happened

Building the circuit assembler multiblock using the target hatch as seen here
![2024-05-18_19 35 50](https://github.com/Nomi-CEu/Nomi-CEu/assets/73462627/3fd12919-ebf8-4147-b94c-8da78527aa5e)
the multiblock still doesn't form and the controller still reads structure incomplete
![2024-05-18_19 30 11](https://github.com/Nomi-CEu/Nomi-CEu/assets/73462627/58d0f8a3-21f3-4980-a12b-2df9ca1e6974)

### Expected Behavior

The multiblock should've accepted the laser target hatch as an acceptable energy hatch and formed the structure correctly.

### Reproduction Steps

To recreate the bug simply setup a functioning transformer and laser line that connects and delivers energy to the laser target hatch and then build the structure of the multiblock, it doesnt matter if you place the laser hatch and then the structure or the structure and then the laser hatch as the bug happens regardless

**Comment by MatthiasMann** [comment]
I don't think the laser hatch counts as energy hatch - I think you need to go from the sub station to an transformer, and from there with normal cables or super conducting wires to the machines.

**Comment by Folanlron** [comment]
Intended , you will have to take it up with the GCYM dev.

https://github.com/GregTechCEu/gregicality-multiblocks
