### ISSUE TITLE
RTM Coil Quest

### ISSUE THREAD

**Issue by cmallery99** [Nomi-CEu/Nomi-CEu#749]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Curse Forge

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

No quest for RTM coils, tungsteel coil quest replaced requirement with RTM coils, but quest unlock still requires tungsteel ingot, which requires RTM coils to smelt

### Expected Behavior

new quests for RTM and RTM coils before tungsteel quest

**Comment by Underio3298** [comment]
Thanks for reporting this.

1. Assuming you mean "tungstensteel" not "tungsteel", the tungstensteel coils have been replaced by RTM Alloy coils for balancing in https://github.com/GregTechCEu/GregTech/pull/2185
2. There is an RTM Alloy coil quest in the current repo state, (added in https://github.com/Nomi-CEu/Nomi-CEu/pull/681/commits/31bdd3dabef180b6e253fa96fb4fc2dab099924b) however, no RTM Alloy Ingot quest, which I will add. 
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/117237424/3147a667-5a8c-4eef-92c2-86434d809584)
4. Also, I noticed the spot in which the Tungstensteel quest is placed makes it look as if it comes before the RTM Alloy Coils in the Progression tab, which I will also fix.
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/117237424/04f8238f-f23f-4e50-b9bb-592e17f39c22)
