### ISSUE TITLE
4A Energy Hatches don't boost recipe level but 2x2A do

### ISSUE THREAD

**Issue by QuickStick123** [Nomi-CEu/Nomi-CEu#751]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Curse

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

4A
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/31533893/a3b58dd1-b60a-4f43-b062-815d8becece5)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/31533893/e85b37c7-5bc2-4a20-80f5-3dc390d79e54)

2x2A
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/31533893/12536e1c-1d41-4e08-9c84-c3ab6290c32d)
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/31533893/95bbcd1e-aeb5-4067-8198-fa3699ac59ed)

### Expected Behavior

![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/31533893/95bbcd1e-aeb5-4067-8198-fa3699ac59ed)

Recipe boosting is expected otherwise it would impossible to progress to IV tier on the blast furnace as signalum is used for t4 micro miners to get iridium but requires IV the other methods is via iridium metal residue which is also an IV tier recipe on large chemical reactor.

### Reproduction Steps

Use a 4A energy hatch and observe blast furnace recipe isn't raised.

Probably introduced in https://github.com/GregTechCEu/GregTech/pull/2139 / https://github.com/Nomi-CEu/Nomi-CEu/pull/681

**Comment by QuickStick123** [comment]
Upon closer inspection of https://github.com/GregTechCEu/GregTech/pull/2139 it seems this was intentionally for whatever reason. Not sure why they would introduce such a confusing thing that feels like a bug though.

**Comment by IntegerLimit** [comment]
This is not a bug. This is intended. You can use 2x4A Hatches instead. (Same for 8A or 16A)

This was specifically implemented so that GCYM Multiblocks cannot overclock past their energy hatch voltage tier, via limiting their hatch amount to a maximum of 1. Making 4A/8A/16A implicitly increase the Max Recipe Tier would break this, and/or cause confusion and inconsistencies.
