### ISSUE TITLE
it keeps crahing

### ISSUE THREAD

**Issue by bombaatomowa123456** [Nomi-CEu/Nomi-CEu#752]
### Nomi CEu Version

1.6.1b

### Launcher

FTB desktop app

### Configurations or Mods Changed

i changed the air to be air instead of air(i changed nothing)

### Environment

it crashes and fails to launch. 

### Mode

N/A

### What Happened

i try to launch it and CRASH

### Expected Behavior

i expected it to actually launch

### Reproduction Steps

launch 

### Logs

[latest.log](https://github.com/user-attachments/files/15545850/latest.log)

### Additional Information

i have no fucking clue what happened

**Comment by IntegerLimit** [comment]
Don't use the FTB Desktop App. For a similar but slightly (very slightly) more reliable experience, try the CurseForge Launcher. However, it is recommended you use Prism Launcher.

If the issue still occurs from using Prism Launcher, please reopen this issue.
