### ISSUE TITLE
Central Monitor wireless does not work across dimensions

### ISSUE THREAD

**Issue by NoHaxJustPi** [Nomi-CEu/Nomi-CEu#753]
### Nomi CEu Version

1.6.1b

### Launcher

Prism Launcher

### Environment

Discovered in Multiplayer, but replicated in Singleplayer

### Mode

Normal Mode

### What Happened

Attempted to connect a Fusion Reactor Mk.1 and a Super Tank in the void world via wireless digital interface cover to a central monitor in space, but neither showed up on the list.

### Expected Behavior

Expected them to connect to the Monitor as standard

### Reproduction Steps

1. Set up a Central Monitor
2. Place something down which can have covers on it (machine, crate, etc.) in a different dimension
3. Put a Wireless Digital Interface bound to the Monitor on it
4. Return to the Monitor, observe that it is not listed

### Additional Information

Removing the covers off of the machines showed that their NBT did not include a `dimension` tag, even though they had it in NBT before placement.

**Comment by Folanlron** [comment]
Please report to CEu team, as even in CE(which the central monitor comes from), it never did NH uses the Nuclear Info Mod for it's Info Panels(so works much differently)

https://github.com/GregTechCEu/GregTech
