### ISSUE TITLE
Gregify AE2 recipes for late game

### ISSUE THREAD

**Issue by D-Alessian** [Nomi-CEu/Nomi-CEu#754]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Prism

### Configurations or Mods Changed

Only ones relevant are :
AE2FCr
Lazy AE2

### Environment

Forge server

### Related Problem

Currently, late game, making anything anything AE2 related is particularly painful. Lazy AE2 somewhat fixes this with circuit etchers and pulse centrifuges, but it isn't in the pack by default.

### Your Solution

Make recipes for AE2 components (processors, purified quartzes, charged quartz, fluix crystals) have crafts in GT machines.

### How Will Your Solution Work

> Purified (certus quartz, quartz, fluix) : Use the new greenhouse multi, and have the same recipe as the phytogenic isolator recipe for them. Gate it at EV and make it take 2 seconds so it takes 1t at UHV.

> Processors : Have the same recipes as the circuit etcher recipes, but in a forming press, I think it's the machines that makes the most sense. Gate it behind IV, recipe speed doesn't matter as much since it can parallel

> Fluix : Make a mixer recipe for fluix dust that uses `charged certus quartz dust, nether quartz dust, redstone` that makes 2 fluix dust. Have an autoclave recipe that make fluix crystals from fluix dust and water/distilled water. The gating on this should be around EV too I feel like, and speed again is less important since parallels.

> Charged certus quartz : This one, I'm not entirely sure what recipe to have for it, but maybe electrolyser? It should be the least gated though I think, it's the least "precious" AE2 material. Maybe HV with a very low recipe time, like 0.5s.

### Alternatives You've Considered

Adding Lazy AE2, but it still doesn't feel the same. I use Lazy AE2 on my world, still feels slow at post tank where I'm at.

Having custom machines made for AE2 recipes that are gregified would also be a better alternative imo, but it may be too much work for a limited impact.

### Additional Information

I think it's important to gate them pretty late to not make it too easy. But late game, AE2 is necessary, and you have pretty much no good options to make a ton of AE2 items that isn't painful. That pain is what I'm proposing to fix, not making AE2 less gated and easier.

_No response_

**Comment by MatthiasMann** [comment]
Hmm - I just used a few advanced inscribers and 3 growth chambers to make all AE2 parts passively. Easily to automate using the counting item filter from EIO and AE2.
