### ISSUE TITLE
THE LV ENERGY CONVERTER CONVERTS FE NOT RF 

### ISSUE THREAD

**Issue by bombaatomowa123456** [Nomi-CEu/Nomi-CEu#755]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Prism launcher

### Configurations or Mods Changed

Added mods that dont affect the other mods at all

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

It doesnt work with steam dynamo as it needs FE for EU

### Expected Behavior

Expected it to convert rf to eu but it converts fe to eu

### Reproduction Steps

1. get the steam dynamo and a water source and fuel
2. put the lv energy converter on it
3. 4.  3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 
4. apparently the bug report is also bugged i clicked enter and it made those 3s
actual 3. it doesnt work

**Comment by Folanlron** [comment]
FE/RF are both the same thing, they are 100% interchangeable.
