### ISSUE TITLE
Suggestions for mods

### ISSUE THREAD

**Issue by JackMeds** [Nomi-CEu/Nomi-CEu#76]
Suggestions for mods
RAD is a simple, client-side only mod which allows you to reload the audio driver / sound library by pressing F3 + R. It also appears on the list when you press F3 + Q.
(as you know, sometimes changed audio divices need to restart game
https://www.curseforge.com/minecraft/mc-mods/reload-audio-driver-rad
========
This mod adds a way to auth within your game in the multiplayer screen.
https://www.curseforge.com/minecraft/mc-mods/oauth

**Comment by IntegerLimit** [comment]
I don't feel like these mods are needed. However, if you wish to use them, you can simply add them to your game.
