### ISSUE TITLE
Draconium Recipe error.

### ISSUE THREAD

**Issue by v3ect0rgames** [Nomi-CEu/Nomi-CEu#760]
### Nomi CEu Version

1.6.1b

### Launcher

CurseForge Launcher

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

The Draconium recipe with high octane gasoline can do the same thing but with less fuel and the same amount of power and time.
<img width="558" alt="Screenshot 2024-06-12 at 10 27 52 PM" src="https://github.com/Nomi-CEu/Nomi-CEu/assets/164247766/83c1e24a-c484-4f63-85ad-fdbfa15f1736">
<img width="571" alt="Screenshot 2024-06-12 at 10 28 06 PM" src="https://github.com/Nomi-CEu/Nomi-CEu/assets/164247766/7b01f6f2-f13f-4311-b024-d45c460523fb">
<img width="569" alt="Screenshot 2024-06-12 at 10 27 19 PM" src="https://github.com/Nomi-CEu/Nomi-CEu/assets/164247766/6efb7b62-0fdc-40e9-b59c-e11f0b8bb057">
<img width="577" alt="Screenshot 2024-06-12 at 10 26 35 PM" src="https://github.com/Nomi-CEu/Nomi-CEu/assets/164247766/4856af09-14ac-4f08-8ce3-16b858d23e2c">

### Expected Behavior

It should use the same amount of fuel.

### Reproduction Steps

Look at the recipe for hot draconium ingots.

### Additional Information

This does not to apply to Cetane Boosted Diesel

**Comment by v3ect0rgames** [comment]
I just realized that it uses Gasoline instead of High Octane and thats why it uses more.

**Comment by v3ect0rgames** [comment]
Please Mark This as invalid

**Comment by IntegerLimit** [comment]
Marked as invalid. Its fine, mistakes happen.
