### ISSUE TITLE
ae2 interface dupe

### ISSUE THREAD

**Issue by xx146542xx** [Nomi-CEu/Nomi-CEu#763]
### Nomi CEu Version

1.7-alpha-4

### Launcher

HMCL

### Configurations or Mods Changed

modified 
enderio liquid tank cap 32000 ->128000

+mod ftb uitimine

### Environment

nomi-ceu-1.7-alpha-4-server downloaded at release pate on 5th june

### Mode

Normal Mode

### What Happened

ae2 dupe coke block 
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/109429390/1db49e88-72b1-4cba-8c23-1d87426abcb1)

### Expected Behavior

ae2 dupe by shift click me interface with full thermal backpack 
then break it or wrench it
one stack become 512 but in nbtexplorer shows that is 1674905[usually is 64]

### Reproduction Steps

see video bwlow

### Logs

console does not output anything

### Additional Information

https://github.com/Nomi-CEu/Nomi-CEu/assets/109429390/62e746e5-5eb8-4bd8-9474-5d32acf540d5

**Comment by IntegerLimit** [comment]
Fixed in current version of AE2, as tested by Exa.

**Comment by IntegerLimit** [comment]
Fixed in version if AE2 in dev (.56.4).
