### ISSUE TITLE
lv 4x battery buffer doesnt charge batteries inside

### ISSUE THREAD

**Issue by bombaatomowa123456** [Nomi-CEu/Nomi-CEu#768]
### Nomi CEu Version

1.7-alpha-4

### Launcher

prism launcher

### Configurations or Mods Changed

added some mods that dont change anything

### Environment

singleplayer 

### Mode

Normal Mode

### What Happened

it doesnt charge 
![image](https://github.com/Nomi-CEu/Nomi-CEu/assets/115266523/b0e73e96-ce9b-4fcf-94e2-a56b1383ae68)

### Expected Behavior

expected the batteries to charge

**Comment by IntegerLimit** [comment]
The output of the converter is facing the wrong way. You are not inputting energy into the battery buffer.
