### ISSUE TITLE
Item Duplication with Extra Utilites 2's Enchanter

### ISSUE THREAD

**Issue by Fix3dll** [Nomi-CEu/Nomi-CEu#770]
### Nomi CEu Version

1.7-alpha-4

### Launcher

Prism Launcher

### Environment

Multiplayer server with 3 GB RAM on Ubuntu 22

### Mode

Normal Mode

### What Happened

I can duplicate wirecutter (didnt tried others yet) with Extra Utilities 2's Enchanter.
![eu2's enchanter](https://github.com/Nomi-CEu/Nomi-CEu/assets/10743391/8c644fe5-592b-4131-b4e9-e8980f528a13)

### Expected Behavior

Expected to produce enchanted wirecutter by consuming old wirecutter

### Reproduction Steps

Try to enchant damaged steel wirecutter with 1 Lapis Lazuli on Extra Utilities 2's Enchanter.

**Comment by v3ect0rgames** [comment]
For some reason the enchanter adds damage to the items instead of removing them

**Comment by IntegerLimit** [comment]
I'll fix this via mixin in labs.

**Comment by IntegerLimit** [comment]
Not closing this until Labs is updated in Nomi-CEu.
