### ISSUE TITLE
Hide/remove Liquid/Dust versions of Molten/ABS metals

### ISSUE THREAD

**Issue by xClockworkx** [Nomi-CEu/Nomi-CEu#771]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Environment

Singleplayer

### Mode

Both Modes

### Your Solution

Remove the dusts and skip to allow ingot in centrifuge to get the parts back(know it doesnt make sense but only reason to have dusts like Zenon-100 is for centrifuge for the parts back) remove/hide the plain liquid version of molten metals

### How Will Your Solution Work

Clean up JEI and not go through making a process for a dust that you cant make in first place(your meant to use ABS for molten but click through JEI starting from the ingot to the dust)

**Comment by Folanlron** [comment]
The Mixer/EBF recipes are in place cause of the RHF, you cannot add a Para hatch to the ABS which is why the normal style recipes are there.

At End game Solidification is much better then Extrusion.

Breaking down combined dusts to base resources is fine.

This is just a big No.
