### ISSUE TITLE
Game crashes upon trying to craft Data frames, CEu 1.6

### ISSUE THREAD

**Issue by arsinec** [Nomi-CEu/Nomi-CEu#775]
### Nomi CEu Version

1.6

### Launcher

Prism Launcher

### Environment

Singleplayer, forge server, LAN off

### Mode

Normal Mode

### What Happened

I attempted to craft a Zombie Data frame. and once i hovered over the result of the craft (i.e, the frame) my game crashed. This happened twice.

### Expected Behavior

I expected to be able to craft the zombie data module/frame.

### Reproduction Steps

1. Open a crafting table (or use the 2x2 in your inventory, both result in the same thing)
2. Either use JEI or manually put in a piece of a rotten flesh and a blank data module in the crafting table.
3. Hover over the resulting zombie data module
4. Crash.

### Logs

https://mclo.gs/PyTbiLM

### Additional Information

This has happened consistently through several installations of the modpack at 1.6.

**Comment by arsinec** [comment]
Oh, to add on; it seems to apply for any data model.

**Comment by IntegerLimit** [comment]
Can you see if this issue occurs in 1.7-alpha-4.

**Comment by arsinec** [comment]
I'll check in a minute, but we ended up solving it. I had my crouch bound to a mouse button, and changing that back to Lshift fixed it.

**Comment by arsinec** [comment]
Bug is fixed in 1.7.4.
