### ISSUE TITLE
Issue In Silicon Wafers Quest (Quest 81)

### ISSUE THREAD

**Issue by v3ect0rgames** [Nomi-CEu/Nomi-CEu#777]
### Nomi CEu Version

1.6.1b

### Launcher

CurseForge Launcher

### Environment

Forge Server

### Mode

Normal Mode

### What Happened

The Quest for silicon wafers requires the cutting machine, but the cutting machine is not needed to make a wafer. The wafer is used in a cutting machine to make other things.

### Expected Behavior

Expected silicon wafer quest to not require cutting machine as cutting machine is not needed to make wafer. Can either be fixed with a new quest for cut wafers, or just removing the cutting machine requirement.

**Comment by v3ect0rgames** [comment]
I think this is half bug, half enchancement, so I'm not sure what this should be market as

**Comment by v3ect0rgames** [comment]
actually this should be marked as quest book

**Comment by Folanlron** [comment]
You must mean the Boules, which you can't do anything with without cutting the boules down to wafers.

There is no use for the full on "boules" in any recipe, so the cutting machine requirement is fine.

**Comment by v3ect0rgames** [comment]
The requirment is wrong because it requires the MV sawmill instead of the LV one, even though you can make them with the lv ones

**Comment by v3ect0rgames** [comment]
Ok, I was confused because I thought you could make wafers with the lv sawmill and didn't need an mv one.

**Comment by v3ect0rgames** [comment]
This should be market as invalid

**Comment by v3ect0rgames** [comment]
thanks
