### ISSUE TITLE
There are no recycle recipes for 4+ amp multiblock hatches

### ISSUE THREAD

**Issue by xClockworkx** [Nomi-CEu/Nomi-CEu#780]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Environment

Singleplayer

### Mode

Both Modes

### Related Problem

No Macerator/Arc Furnace recipe to recycle 4+ amp hatches/dynamos for multiblocks

### Your Solution

Add recycle recipes

### How Will Your Solution Work

After upgrading from EV+ you can only trash currently

**Comment by v3ect0rgames** [comment]
Ok We have the IV-UHV 4A, IV-UHV 16A energy hatches, and the IV-UHV 4A, IV-UHV 16A dynamo hatches

**Comment by Folanlron** [comment]
Probably cause of the custom recipes we use for the Energy Hatches, would probably have to be fixed via Nomi-Labs, but will wait for Integer to chime in.

**Comment by v3ect0rgames** [comment]
ive been working on the recipes on groovy to add them

**Comment by v3ect0rgames** [comment]
it seems to work fine so far

**Comment by IntegerLimit** [comment]
Of course the recycle recipes won't be added by hand, but with Labs helpers, it should be really easy. @v3ect0rgames leave it.

**Comment by v3ect0rgames** [comment]
ok

**Comment by v3ect0rgames** [comment]
the labs helper can automatically generate them?

**Comment by v3ect0rgames** [comment]
cool
