### ISSUE TITLE
Some items/blocks are missing their custom recipes

### ISSUE THREAD

**Issue by GavinFF-SS** [Nomi-CEu/Nomi-CEu#803]
### Nomi CEu Version

1.7-beta-5

### Launcher

Prism Launcher

### Configurations or Mods Changed

Running using CleanroomMC
Updated Nomi Labs to the commit a2a9694 on Github Actions
Added AE2 Fluid Crafting

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Copper Furnace uses a normal furnace over the iron as it used in Alpha 4
And EVERYTHING from AE2 that had custom recipes do not have them anymore.

### Expected Behavior

The recipes are correct (Copper Furnace requires an Iron Furnace and AE2 items have their specified recipes in the .groovy files.)

### Reproduction Steps

1. Load a world
2. Check the recipes of anything from AE2 or the recipe of the Copper Furnace
3. Reverse profit (it's way cheaper and progression could be considered broken depending on how you see it.)

### Logs

[groovy.log](https://github.com/user-attachments/files/16229788/groovy.log)
All I could find for a groovy log is only for the copper furnace issue.

**Comment by GavinFF-SS** [comment]
Fixed with latest github actions release of the pack (or the latest github actions release of nomi-labs, i can't tell which, but at least the issue is fixed, right?)

**Comment by IntegerLimit** [comment]
There was nothing like that changed in Nomi-Labs GHA update, or the latest commits in Nomi-CEu. Sounds like a bad install, but at least the issue is fixed.
