### ISSUE TITLE
ae2stuff Advanced Inscriber deplete Inscriber press

### ISSUE THREAD

**Issue by qianbing233** [Nomi-CEu/Nomi-CEu#804]
### Nomi CEu Version

1.7-beta-5

### Launcher

Plain Craft Launcher 2

### Configurations or Mods Changed

mcjtylib-1.12-3.5.4 (1)
xnet-1.12-1.8.2-zh_cn-2023-5-3
jecharacters-1.12.0-3.7.2
hecharacters-1.12.2-1.4.0 (1)
Fluid+Craft+for+AE2-2.4.12-r
FluxNetworks-1.12.2-4.1.1.34
[平滑字体] SmoothFont-mc1.12.2-2.1.4

### Environment

singerplayer

### Mode

Normal Mode

### What Happened

when i update save from 1.7alpha1. ae2stuff Advanced Inscriber deplete Inscriber press. In other game to test haven't this bug 

### Expected Behavior

https://github.com/user-attachments/assets/b3d10970-21e2-40c3-b1cc-bf11f948b829

https://github.com/user-attachments/assets/d83cabcc-76a5-4d1e-ba59-4c76310eb7b3

**Comment by tildeman** [comment]
Normal presses seem to work, this might be an issue with AE2 Stuff Unofficial.

**Comment by qianbing233** [comment]
> ~Normal inscribers seem to work, this might be an issue with AE2 Stuff Unofficial.~ Oops, they don't

but 1.7 beta 5 is AE2 stuff official version

**Comment by zero6six** [comment]
> ~Normal inscribers seem to work, this might be an issue with AE2 Stuff Unofficial.~ Oops, they don't

When you automatically installed 1.7-beta-5 release, did you install AE2 Stuff Unofficial? I installed it and found that it was AE2 Stuff. And I pinged Integer Limit on discord for this glitch.

**Comment by qianbing233** [comment]
In test  ae2 unofficial Extended Life Inscriber have same bug

**Comment by tildeman** [comment]
> > ~Normal inscribers seem to work, this might be an issue with AE2 Stuff Unofficial.~ Oops, they don't
> 
> When you automatically installed 1.7-beta-5 release, did you install AE2 Stuff Unofficial? I installed it and found that it was AE2 Stuff. And I pinged Integer Limit on discord for this glitch.

I updated my existing Nomi-CEu instance to beta-5, and after changing the mods directly, both AE2 Stuff and AE2 Stuff Unofficial have the same problem. This might require a recipe override.

**Comment by v3ect0rgames** [comment]
this bug has been fixed already i think it was fixed yesterday

**Comment by tildeman** [comment]
I'll try to build the nightly, hopefully this gets fixed.

**Comment by tildeman** [comment]
As a temporary solution until beta-6 or the full release (unless you're playing on nightly), replace `/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/misc.groovy` with the file in commit [14c38dd](https://github.com/Nomi-CEu/Nomi-CEu/blob/14c38dd/overrides/groovy/postInit/Post-Initial/Main/Mod-Specific/ae2/misc.groovy).

**Comment by IntegerLimit** [comment]
Fixed in https://github.com/Nomi-CEu/Nomi-CEu/pull/801.
