### ISSUE TITLE
regression: AE2 inscriber consumes inscriber press

### ISSUE THREAD

**Issue by nyyyxnyxnyx3302** [Nomi-CEu/Nomi-CEu#810]
### Nomi CEu Version

1.7-beta-5

### Launcher

SKlauncher

### Configurations or Mods Changed

changes:
config/loliasm.cfg: in block `textures` set B:onDemandAnimatedTextures=false
config/advRocketry/advancedRocketry.cfg: in block `client` set B:PlanetSkyOverride=false and B:overworldSkyOverride=false

mods added: AE2 Fluid Crafting Rework version 2.6.4-r; tested without this mod, behaviour still regresses

### Environment

environment 1: singleplayer
environment 2: multiplayer (forge server)

### Mode

Normal Mode

### What Happened

attempting to produce printed silicon/any printed circuit in the inscriber (both regular and advanced) consumes the inscriber press

### Expected Behavior

inscriber should have produced printed circuits/silicon from the appropriate plates, with the appropriate inscriber press, without consuming the inscriber press

### Reproduction Steps

1. have an inscriber/advanced inscriber powered and ready to process
2. insert (for example) calculation press and certus quartz plate into appropriate slots
3. the inscriber press gets consumed as a result of the processing

**Comment by Folanlron** [comment]
Fixed via https://github.com/Nomi-CEu/Nomi-CEu/pull/808

**Comment by IntegerLimit** [comment]
Closing as not planned (as duplicate).
