### ISSUE TITLE
Inscriber Press consumed on craft

### ISSUE THREAD

**Issue by vertice30c** [Nomi-CEu/Nomi-CEu#814]
### Nomi CEu Version

1.7-beta-5

### Launcher

Prism Launcher

### Configurations or Mods Changed

AE2 Fluid Crafting Version 2.6.4-r

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Crafting printed silicon from AE2 when press is consumed upon the craft completion.

https://github.com/user-attachments/assets/b4536ce0-2ceb-4ed5-bbae-3e8c90a9b8d1

### Expected Behavior

Not typically normal behavior

### Reproduction Steps

1. Place Silicon press in inscriber
2. Place Silicon wafer in second slot
3. Wait for craft completion

**Comment by vertice30c** [comment]
nvm i just saw this in closed sorry yall

**Comment by IntegerLimit** [comment]
Closing as not planned (as is duplicated).
