### ISSUE TITLE
DE Energy Core cannot use gt draconium block

### ISSUE THREAD

**Issue by slime1001** [Nomi-CEu/Nomi-CEu#823]
### Nomi CEu Version

1.7-beta-5c

### Launcher

Multimc

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

The energy core does not accept the gt draconium block.
![image](https://github.com/user-attachments/assets/c617778a-7c77-42e6-a917-e79e90ff2c3e)
![image](https://github.com/user-attachments/assets/65e46a68-37a8-4f21-a33f-cdd34344ac92)
But in 1.7-alpha-4 , it accept the gt draconium block again.
![image](https://github.com/user-attachments/assets/498618c0-f690-4e24-961c-3d35ca34008b)
![image](https://github.com/user-attachments/assets/1b0dfb13-7300-4117-bcdc-2e487fddc540)

### Expected Behavior

Energy core should formed with gt draconium block.

**Comment by IntegerLimit** [comment]
Most likely caused by GrS stuff, investigating this now.
