### ISSUE TITLE
Fluid Drilling Rig drilling the wrong fluid

### ISSUE THREAD

**Issue by miclol** [Nomi-CEu/Nomi-CEu#830]
### Nomi CEu Version

1.6.1b

### Launcher

Prism Launcher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

I placed a drilling rig on an oil vein but the drilling rig gave natural gas from a chunk over instead.
![image](https://github.com/user-attachments/assets/cff4bc0f-d923-42e0-b2a5-6cc26d18a2a9)
![image](https://github.com/user-attachments/assets/e16b6397-7de9-4122-aa63-60b3400fbf62)
![image](https://github.com/user-attachments/assets/75f36951-9908-47aa-81b7-224e1467b5f7)
![image](https://github.com/user-attachments/assets/7e61b7f4-c51f-4d35-ad17-f1be141cd5bf)

### Expected Behavior

For oil to be outputted at the drilling rig instead of natural gas.

### Additional Information

The oil drilling rig seems to be drilling 1 chunk offset to the east from what the prospector scanner is telling me.

**Comment by IntegerLimit** [comment]
Fixed in 1.7-beta-5c.
