### ISSUE TITLE
DME Simulation Supercomputer not working as intended

### ISSUE THREAD

**Issue by Thecommand64** [Nomi-CEu/Nomi-CEu#845]
### Nomi CEu Version

1.7-beta-5c

### Launcher

Prism launcher

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

The DME Simulation Supercomputer does not produce pristine matter, for some reason it accepts parallel hatches, it also does not appear on HEI.
![2024-07-31_13 31 03](https://github.com/user-attachments/assets/2bc739ba-71a8-41fd-a5c4-a8c976c7c675)
![2024-07-31_13 31 15](https://github.com/user-attachments/assets/ad395281-7426-459e-98f2-2a0ab96f1272)
![2024-07-31_13 31 29](https://github.com/user-attachments/assets/f86664e9-4ad7-4864-b8e0-3091faccde81)
![2024-07-31_13 31 32](https://github.com/user-attachments/assets/a701520f-28d8-4ee6-9758-610c9addd5c0)
![2024-07-31_13 31 35](https://github.com/user-attachments/assets/5622c051-68b1-47ec-bc05-614e2c03c3fd)
![2024-07-31_13 31 41](https://github.com/user-attachments/assets/6599ff40-263f-44b1-b460-c197704c27f2)
![2024-07-31_13 32 36](https://github.com/user-attachments/assets/0d7a8401-04fc-4392-b9a1-16fd50dc1ce6)

### Expected Behavior

The DME simulation supercomputer should work the same as a simulation chamber, it also should not accept parallel hatches and it should appear on HEI to the side of the simulation chamber tab

### Additional Information

I am using java version 8.0.422 downloaded from https://adoptium.net/temurin/archive/?version=8

**Comment by IntegerLimit** [comment]
Whoops?

**Comment by IntegerLimit** [comment]
I think it should accept parallel hatches, but not sure why its not showing in JEI or running recipes.

**Comment by Thecommand64** [comment]
That definitely solved it however, now i have encountered a different one but i dont know if its worth a new issue, the problem is that the data models that the player crafts doesn't work on the supercomputer, but if the data model is obtained with a nbt tag like this : /give Player deepmoblearning:data_model_wither 1 0 {tier:0}, it works but it also upgrades the tier of the data model when it runs the simulation on the supercomputer

**Comment by IntegerLimit** [comment]
That is intended, as using `/give` gives you a `faulty` data tier. Similarly, it does not run in DME's Simulation Chamber.
