### ISSUE TITLE
Crafting table dupe

### ISSUE THREAD

**Issue by Lucman00** [Nomi-CEu/Nomi-CEu#853]
### Nomi CEu Version

1.6.1b

### Launcher

Prism launcher

### Environment

Multiplayer

### Mode

Normal Mode

### What Happened

Duped crafted items

### Expected Behavior

Block disappears on 2nd person's GUI

### Reproduction Steps

Example: craft ore block with 9 ingots.(works with any craft) block result doesn't show up on other person. other person takes out 1 ingot and puts it back in. block shows for both people. 1st person takes out block -> block doesn't disappear for 2nd person -> 2nd person spamclicks block and gets infinite of said blocks

### Additional Information

https://github.com/user-attachments/assets/7a64304e-d9a6-4bb3-9fcb-8eb148b08f1e

**Comment by v3ect0rgames** [comment]
is this on lan or multiplayer?

**Comment by Lucman00** [comment]
Server

**Comment by Lucman00** [comment]
> is this on lan or a server?

server

**Comment by v3ect0rgames** [comment]
ok

**Comment by v3ect0rgames** [comment]
lan is buggy, but if your not on lan thats weird

**Comment by v3ect0rgames** [comment]
try switching to beta 5c and see if the bug is fixed

**Comment by Lucman00** [comment]
> lan is buggy, but if your not on lan thats weird

pretty sure its a bug with the crafting interface and how it saves the items

**Comment by v3ect0rgames** [comment]
it might be fixed in beta 5c, can you switch the server to that

**Comment by Lucman00** [comment]
server owner is currently not online and will only come tmrw but yea we can try

**Comment by v3ect0rgames** [comment]
if you can find any beta 5 servers online, you should check

**Comment by Folanlron** [comment]
Has been fixed via, https://github.com/Nomi-CEu/Nomi-CEu/pull/560
