### ISSUE TITLE
Sleeping in the void world doesn't change time of day

### ISSUE THREAD

**Issue by MatthiasMann** [Nomi-CEu/Nomi-CEu#862]
### Nomi CEu Version

1.7-beta-5c

### Launcher

Prism Launcher

### Environment

Singleplayer
gamerule doWeatherCycle false
gamerule keepInventory true

### Mode

Normal Mode

### What Happened

I placed a bed in the void world (the one reachable from the free cake you get at the start) and tried sleeping - the sleep animation starts, the screen darkens and then you are awake again but the time of day as displayed by the minimap has not advanced and it's still dark.

Tried it again just now at 13:10 and after sleeping it was 13:15 - so no change in time and still night.

### Expected Behavior

Time of day changes to early morning and it's light

### Reproduction Steps

1. go to the void world
2. place a bed
3. wait until night
4. sleep

**Comment by v3ect0rgames** [comment]
what about doDaylightCycle

**Comment by IntegerLimit** [comment]
Can Reproduce.
