### ISSUE TITLE
Tantalum duplication through capacitor recycling

### ISSUE THREAD

**Issue by fluffoo** [Nomi-CEu/Nomi-CEu#876]
### Nomi CEu Version

1.7-beta-5c

### Launcher

Prism

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

making tantalum capacitors in an assembler costs 1 tantalum dust, 1 manganese foil, and 144mb of polyethylene for 8 capacitors
8 tantalum capacitors recycle into 8 tantalum dust and 8 small piles of manganese dust

### Expected Behavior

tantalum capacitors shouldn't recycle into more materials than they cost to make

### Reproduction Steps

make then macerate tantalum capacitors

**Comment by IntegerLimit** [comment]
Can you see if this issue occurs on the latest nightly release?

**Comment by fluffoo** [comment]
I'm sorry but I have no clue how to get the latest nightly release, not very familiar with github personally

**Comment by IntegerLimit** [comment]
This is the link for nightly downloads. Download the 'client' zip, and then import into your favourite launcher.

https://nightly.link/Nomi-CEu/Nomi-CEu/workflows/testbuildpack/main
