### ISSUE TITLE
Day-Night cycle/ in-game clock ticking by 4 not by 1

### ISSUE THREAD

**Issue by Lefayae** [Nomi-CEu/Nomi-CEu#896]
### Nomi CEu Version

1.7-beta-6

### Launcher

Prism Launcher 8.4

### Configurations or Mods Changed

Added AE2 Fluid Crafting Rework Version: 2.6.4-r

### Environment

Forge Server
Loaded a world that worked fine from: 1.7.-beta-5c

### Mode

Normal Mode

### What Happened

The in-game clock is ticking by 4 not by 1. The day-night cycle seems to go by an increased rate.

### Expected Behavior

The day-night cycle goes by the standard rate.

**Comment by Lefayae** [comment]
Correction: The whole world ticks by 4 instead of 1

**Comment by CrossElectronics** [comment]
Can reproduce. Even if you set `doDaylightCycle false`, the skybox for Advanced Rocketry is still incorrect. This affects both OW & Void. Another user also reported this.

Although TPS is still 20 and the machines are behaving normally.

**Comment by Lefayae** [comment]
The value that the clock ticks by is not fix. In my forge server (2 of us played on it) it was 4. But in single player it was only 2
