### ISSUE TITLE
Minecraft crashes

### ISSUE THREAD

**Issue by FJSAGS** [Nomi-CEu/Nomi-CEu#899]
### Nomi CEu Version

1.7-beta-6

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added: Lazy AE2, AE2 Fluid Crafting

### Environment

Singleplayer.

### Mode

Normal Mode

### What Happened

Minecraft crashed because of advanced rocketry
![image](https://github.com/user-attachments/assets/1f8f2045-1a6c-4b18-b2a6-fd723d323e76)

### Expected Behavior

Minecraft not crashing

### Logs

https://mclo.gs/pgcbF9B

**Comment by NeoNC72** [comment]
this happend to me when flying from luna to void, i fixed it by reloading from a backup

**Comment by FJSAGS** [comment]
In my case it didnt

**Comment by IntegerLimit** [comment]
Most likely related to #896.
