### ISSUE TITLE
Cannot gain experience

### ISSUE THREAD

**Issue by G-Francio** [Nomi-CEu/Nomi-CEu#901]
### Nomi CEu Version

1.7-beta-6

### Launcher

Prism Launcher

### Configurations or Mods Changed

No changes

### Environment

Single player, 1.7b6

### Mode

Normal Mode

### What Happened

Was at level 104 after the XP change (levelling becomes very easy!) and had some experience stored in an experience tome. I clicked to store what I currently had (or to retrieve one level, I don't remember exactly. For a second my level jumped to ~38000, then it was reset to zero. The tome of experience was empty, and I could not gain any other level through normal means. 

\xp 3L works, \xp 3 does not.

### Expected Behavior

I would retrieve a single level :p

### Reproduction Steps

I think (best guess)

1 - store some experience (I think I had about 1500XP) in an experience tome.
2 - level to ~100 through normal means
3 - retrieve one level

**Comment by IntegerLimit** [comment]
Do you mean the Thermal Expansion Experience Tome?

**Comment by IntegerLimit** [comment]
Or if it not from Thermal, what mod is it from?

**Comment by G-Francio** [comment]
> Do you mean the TE Experience Tome

Yes, sorry. Not sure if it matters, enchanted with Holding IV and Soulbound
III

Op di 13 aug 2024 05:59 schreef Integer Limit ***@***.***>:
