### ISSUE TITLE
Farming Station and Fluxomagnet are broken

### ISSUE THREAD

**Issue by GavinFF-SS** [Nomi-CEu/Nomi-CEu#902]
### Nomi CEu Version

1.7-beta-6

### Launcher

Prism Launcher

### Configurations or Mods Changed

Running on CleanroomMC
Added AE2FC Rework 2.6.4-r

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

![2024-08-12_18 19 47](https://github.com/user-attachments/assets/95eba79e-4738-4e75-bb6f-3808b862a5a6)
![2024-08-12_18 11 02](https://github.com/user-attachments/assets/af66e86f-a43a-4a1d-b879-17190a245045)
The Fluxomagnet does not pick up items and the farming station does not chop anything down or harvest.
The particles for both of them are happening, but it isn't doing it.

### Expected Behavior

Expected the farming station/fluxomagnet to actually work.

### Reproduction Steps

1. Load up a world in 1.7-beta-6
2. Fluxomagnet and Farming Station are broken.

**Comment by IntegerLimit** [comment]
Most likely related to #896.
