### ISSUE TITLE
Different Recipes for Mixer and ABS Outputs (Nomi-Labs Alloys)

### ISSUE THREAD

**Issue by WhitePr** [Nomi-CEu/Nomi-CEu#912]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

lazy ae2 
ae2 fc

### Environment

Singleplayer

### Mode

Both Modes

### What Happened

The number of "Fluxed Electrum" made with "Mixer" and "Fluxed Electrum" made with "ABS" is inconsistent
![Screenshot from 2024-08-16 03-00-23](https://github.com/user-attachments/assets/b63f6d40-fcd6-4e93-a4b1-f74ecddb0288)
![Screenshot from 2024-08-16 03-00-32](https://github.com/user-attachments/assets/eea146ef-9d5e-4094-812f-92d379304646)

1152 / 144 = 8

### Expected Behavior

The production quantity should be the same

### Additional Information

https://github.com/Nomi-CEu/Nomi-CEu/issues/912#issuecomment-2292639259

**Comment by IntegerLimit** [comment]
Does this happen with any other alloys (energetic, vibrant, signalum, lumium or enderium)?

**Comment by WhitePr** [comment]
> Does this happen with any other alloys (energetic, vibrant, signalum, lumium or enderium)?

Yes, they are all incorrect; in the alloys of "Nomi Labs", as long as there are formulations using "ABS", they are all incorrect

Lumium:
    Mixer: 4
    ABS: 864 / 144 = 6

Enderium:
    Mixer: 4
    ABS: 1152 / 114 = 8

Signalum
    Mixer: 4
    ABS: 1152 / 144 = 8
    
Energetic (According to the Quest book, this should be correct.)
    Mixer: 2 
    ABS:  576 / 144 = 4

Vibrant (According to the Quest book, this should be correct.)
    Mixer: 1
    ABS: 288 / 144 = 2
