### ISSUE TITLE
Hexafluorosilicic Acid does not count as an acid

### ISSUE THREAD

**Issue by apia46** [Nomi-CEu/Nomi-CEu#922]
### Nomi CEu Version

1.7-beta-5c

### Launcher

Prism Launcher

### Configurations or Mods Changed

None

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

I can put hexafluorosilicic acid and dirty hexafluorosilicic acid in a universal cell despite them having acid in their names
![image](https://github.com/user-attachments/assets/1112d149-4506-4be7-969a-bd561f4774d3)

### Expected Behavior

Not that

### Additional Information

Probably a flag was not set or something idk this should be a simple fix

**Comment by IntegerLimit** [comment]
Yeah, very simple fix, should be fixed later today or tomorrow.

**Comment by IntegerLimit** [comment]
Will also add some temperatures to some other Labs' fluids while I'm at it.
