### ISSUE TITLE
After using the Canning Machine to fill "Call" in parallel in "PA / APA", a filled "Cell" will be output regardless of the amount of raw materials input.

### ISSUE THREAD

**Issue by WhitePr** [Nomi-CEu/Nomi-CEu#924]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

Lazy AE2
AE2FC

### Environment

Singleplayer
Nightly Hash:fcea369

### Mode

Both Modes

### What Happened

When using the 'Canning Machine' in the 'PA/APA' to fill 'Cell', after the first use of parallel refill (whether 16x or 32x or whatever), re-entering any number of ingredients will output only one filled 'Cell' without returning any other 'Empty Cell' and gas/fluid

### Expected Behavior

The output quantity of the finished product should be the same as the quantity of raw materials

### Reproduction Steps

1. Build a Canning Machine PA/APA
2. Input raw materials in quantities that can be processed at 64x or in parallel
3. Output 64 Full Cells or the number of raw materials you input
4. Again, input the raw material quantity that can be processed in 64x or parallel
5. Only one Full Cell is output but no raw materials are returned

[Screencast.webm](https://github.com/user-attachments/assets/5d887767-1b02-41c4-9e45-4dcd465d26e3)

**Comment by WhitePr** [comment]
"Elevation Unit" and "Coolant Unit" are not affected

**Comment by IntegerLimit** [comment]
Can you see if this issue occurs with GCYM Canner?

**Comment by WhitePr** [comment]
> GCYM Canner

Yes, GCYM Canner also had this problem

**Comment by IntegerLimit** [comment]
Ok, thank you!

**Comment by IntegerLimit** [comment]
Ok, I think I have found the issue, will test the fix later today. Should be fixed in a nightly build in around 2-3 hours!
