### ISSUE TITLE
"Groovy" error causes all recipes using "Empowerer" to fail

### ISSUE THREAD

**Issue by WhitePr** [Nomi-CEu/Nomi-CEu#929]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

Clean installation, no mods/configurations added/changed

### Environment

Singleplayer
Nightly:e28bd01

### Mode

Both Modes

### What Happened

"Groovy" error causes all recipes using "Empowerer" to fail
![Screenshot from 2024-08-21 15-31-38](https://github.com/user-attachments/assets/ca6d325e-e0d7-45e2-b704-43de16779116)

### Expected Behavior

Should not fail

### Logs

[groovy.log](https://github.com/user-attachments/files/16686955/groovy.log)

### Additional Information

It may have something to do with https://github.com/Nomi-CEu/Nomi-CEu/pull/927

**Comment by WhitePr** [comment]
To put it simply,  https://github.com/Nomi-CEu/Nomi-CEu/pull/927 forgot to add the setMark and getMark functions

**Comment by IntegerLimit** [comment]
Ah, it worked in my test instance because I'm using GrS 1.1.3. Fixed in a moment.
