### ISSUE TITLE
Sodium Persulfate Quest not registering

### ISSUE THREAD

**Issue by dcoolArne** [Nomi-CEu/Nomi-CEu#938]
### Nomi CEu Version

1.7-beta-6a

### Launcher

Prism Launcher

### Configurations or Mods Changed

Lazy Ae2 and AE2 Fluid Crafting Rework

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Quest not registering produced fluid

### Expected Behavior

Quest finishing

### Reproduction Steps

1. Produce Sodium Persulfate 
2. get it in the cell
3. nothing happens

**Comment by MatthiasMann** [comment]
Yeah, had the same in issue in another quest with the EIO tanks - maybe helpful to write that as a note in the first fluid quest?

**Comment by IntegerLimit** [comment]
Fixed in Labs (https://github.com/Nomi-CEu/Nomi-Labs/commit/cd00c8cf05b8f71e5b85c6154ce8fbfa596de6df), coming to nightly today.
