### ISSUE TITLE
Recipe for small pile of gallium arsenide dust is wrong

### ISSUE THREAD

**Issue by stokescomp** [Nomi-CEu/Nomi-CEu#945]
### Nomi CEu Version

1.6.1b

### Launcher

curseforge

### Configurations or Mods Changed

none

### Environment

single player for 1.6.1b lost city world

### Mode

Normal Mode

### What Happened

When crafting small pile of gallium arsenide dust in a crafting table it doesn't match the recipe from JEI. Plus adding it from JEI produces tiny piles instead. 
Here is what the recipe says to do.
![image](https://github.com/user-attachments/assets/71e0cc51-c8a5-428c-ab97-d3ad65378c39)

Here is what the recipe actually gives you in the crafting grid.
![image](https://github.com/user-attachments/assets/5a82e91a-5cf0-4bec-80e2-929b36adf423)

This is where you can make small piles but the recipe doesn't mention this recipe. I found this by trying all the 9 squares. Two of them can make the small piles buts its a hidden recipe.
![image](https://github.com/user-attachments/assets/d042accd-c1f0-495b-9731-b1d6d8167d98)

### Expected Behavior

I expected using the JEI recipe either with the plus sign or manually placing the gallium arsenide dust in the top middle square would produce small piles of gallium arsenide dust.

### Reproduction Steps

Look at the recipe for small piles of gallium arsenide dust and click the plus sign or use the recipe manually in a crafting table.
The recipe says to get tiny piles you need to place gallium arsenide dust in the top middle of crafting table. I tried all nine plaes and the only places that make the small piles are the top right corner and the right middle square of crafting table.
Clicking the plus sign also produces the tiny piles when it places it in the top middle squre of crafting table.

### Additional Information

The fix would be to change the recipe to match the game but using the top right corner of crafting table in the recipe.
Or make the crafting table make the correct thing when placing the ingredients in the same place as the recipe says to.

**Comment by IntegerLimit** [comment]
Fixed in 1.7-beta-5+.
