### ISSUE TITLE
Add a default keybind to Search Nearby Inventories

### ISSUE THREAD

**Issue by Doniazade** [Nomi-CEu/Nomi-CEu#954]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

None

### Environment

Singleplayer

### Mode

Normal Mode

### Related Problem

The current build lacks a default bind for Search Nearby Inventories, this is an important QoL feature, especially in the early game.

### Your Solution

Bind Search Nearby Inventories to F.

### How Will Your Solution Work

This does not conflict with the current binds because Search Nearby is only relevant with an inventory open and Swap Items In Hands is only relevant with it closed. Select Search Bar (Ctrl-F) also seems to work normally.

### Alternatives You've Considered

V is also an option that works.

### Additional Information

In a future QB pass I will make sure the player is aware of this feature, which is important to make pre-AE2 bearable.

**Comment by IntegerLimit** [comment]
Doesn't the keybind cause problems when searching in the ae2 terminal?

**Comment by IntegerLimit** [comment]
Completed with the introduction of FindMyItemsAndFluids.
