### ISSUE TITLE
Using ABS to make nomi-labs alloys uses more energy and time than using EBF.

### ISSUE THREAD

**Issue by WhitePr** [Nomi-CEu/Nomi-CEu#956]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

ae2fc
lazy ae2

### Environment

singleplay

### Mode

Both Modes

### What Happened

Using ABS to make nomi-labs alloys uses more energy and time than using EBF.

8,232,960 * 4 + 576,000(Mixer) = 33,507,840 < 37,048,320
53.6s * 4 + 15s(Mixer) = 229.4s < 241.2s

![Screenshot from 2024-08-26 13-08-21](https://github.com/user-attachments/assets/939f385c-8540-450b-bef4-263a53217a44)

![Screenshot from 2024-08-26 13-08-29](https://github.com/user-attachments/assets/593a81e6-4ef9-446f-ae3a-46c6fcee936e)

### Expected Behavior

They should be consistent

### Additional Information

Applicable to "Enderium", "Lumium", "signalum"
But the efficiency of "ABS" of "Fluxed Electrum" is higher than that of "EBF", and the efficiency is higher than 3/4

12,349,440 / ( 2,058,240 * 9 ) = 0.66666....

![Screenshot from 2024-08-26 13-21-37](https://github.com/user-attachments/assets/79d09c40-ffad-4291-8752-ce373d55b655)
![Screenshot from 2024-08-26 13-21-42](https://github.com/user-attachments/assets/216af625-e474-4726-85ba-a168b2922f62)

This is probably because only the recipe quantity was adjusted in https://github.com/Nomi-CEu/Nomi-CEu/pull/915 without adjusting other configurations.

**Comment by WhitePr** [comment]
The correct value:
    "signalum":
        Time: (46.9s * 4 + 15s(Mixer) ) * 0.75 = 151.95s = 3039Tick
        Energy: (7,203,840 * 4 + 576,000) * 0.75 = 22,043,520
    "Lumium":
        Time: (53.6s * 4 + 15s) * 0.75 = 172.05s = 3441Tick
        Energy: (8,232,960 * 4 + 576,000) * 0.75 = 25,130,880
    "Enderium":
        Time: (53.6s * 4 + 15)s * 0.75 = 172.05s = 3441Tick
        Energy: (32,931,840 * 4 + 576,000) * 0.75 = 99,227,520
    "Fluxed Electrum":
        Time: (53.6s * 9 + 50s) * 0.75 = 399.3s = 7986Tick
        Energy: (2,058,240 * 9 + 120,000) * 0.75 = 13,983,120

**Comment by IntegerLimit** [comment]
Thank you.

**Comment by IntegerLimit** [comment]
Note that the ABS recipe calculations, in nightly, actually ignore mixer durations. So, the values are slightly lower.
