### ISSUE TITLE
Multiple 4A Energy Hatches Don't Boost Multiblock Overclock

### ISSUE THREAD

**Issue by TangentDelta** [Nomi-CEu/Nomi-CEu#972]
### Nomi CEu Version

1.7

### Launcher

Prism Launcher

### Configurations or Mods Changed

Added AE2 Fluid Crafting
Added Lazy AE2
Added Mystcraft
Added DankNull

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

When two 4A energy hatches of any tier are added to a multiblock, the overclock is boosted as if only 4A is being fed into the machine while the recipe tier is boosted
![2024-08-28_18 37 15](https://github.com/user-attachments/assets/a0fd3771-b88f-4775-a31b-5773ba21beee)
![2024-08-28_18 37 20](https://github.com/user-attachments/assets/b5b4c2af-bfd9-4ab0-acee-99cc9e51c118)

If I mix-and-match with a 2A energy hatch and a 4A energy hatch, the overclock is boosted to 6A
![2024-08-28_18 37 30](https://github.com/user-attachments/assets/2c7d800c-1f46-47c0-9d4a-a90b08b33e1c)
![2024-08-28_18 37 35](https://github.com/user-attachments/assets/70b069e2-db7c-4a1d-b41f-aa95012ed858)

A pair of 16A energy hatches boost the overclock as expected to 32A
![2024-08-28_18 37 46](https://github.com/user-attachments/assets/3d55bd01-91db-4a2e-9279-2bb1b02e8053)
![2024-08-28_18 37 50](https://github.com/user-attachments/assets/949544ee-6d38-441e-9148-512a317f5385)

### Expected Behavior

A pair of 4A energy hatches should boost the multiblock's overclock tier to 8A.

**Comment by IntegerLimit** [comment]
Note, 16x hatches also seem to not be working. 32A of IV is 32 * 8192 = 262144, 131072 is 16A.

**Comment by IntegerLimit** [comment]
However, 2A hatches do seem to be working correctly.
