### ISSUE TITLE
The "Difficulty" of "HM" is locked to "Normal" and cannot be changed

### ISSUE THREAD

**Issue by WhitePr** [Nomi-CEu/Nomi-CEu#974]
### Nomi CEu Version

Nightly

### Launcher

Prism

### Configurations or Mods Changed

Clean installation, no mods/configurations added/changed

### Environment

Singleplayer

### Mode

Expert Mode

### What Happened

Re Title
![Screenshot from 2024-08-31 14-10-22](https://github.com/user-attachments/assets/99caa043-14d3-4e38-9906-f769169d6619)

### Expected Behavior

"Difficulty" should be locked to "Peaceful" instead of "Normal"

**Comment by IntegerLimit** [comment]
Oops, forgot to update labs config.
