### ISSUE TITLE
2 covers 1 pipe.

### ISSUE THREAD

**Issue by Krigoxar** [Nomi-CEu/Nomi-CEu#987]
### Nomi CEu Version

1.7a

### Launcher

Prism Launcher

### Configurations or Mods Changed

Freshly installed specialy for bug testing.

### Environment

SinglePlayer 

### Mode

Normal Mode

### What Happened

When puting two covers on one pipe(first goes item filter then conveyor), one of them disappearing.
![image](https://github.com/user-attachments/assets/70474785-8695-472f-b5e1-c0cd98078b57)
![image](https://github.com/user-attachments/assets/10327f2d-5896-4072-8015-bf0296efa0c3)

### Expected Behavior

When puting two covers on one pipe(first goes item filter then conveyor), none of them disappearing.

### Reproduction Steps

1. Place 3 Nickel item pipes(in my case)
2. Use wrench on midle pipes top
3. Place item filter cover on top
4. Place conveyor belt on other side

### Additional Information

Works on all versions past 1.7

**Comment by IntegerLimit** [comment]
What do you mean that this works on all versions past 1.7?

**Comment by Krigoxar** [comment]
its works on 1.7 and 1.7a

**Comment by IntegerLimit** [comment]
Does this happen on 1.6.1a?

**Comment by Krigoxar** [comment]
![image](https://github.com/user-attachments/assets/edbb7551-48cc-48e6-bef9-2ca69ae24310)
Working as intended.

**Comment by IntegerLimit** [comment]
Yes, sorry, this is reproducible. I believe the covers should still work, but just aren't rendering. Unsure of this however.

Will look into this in a few days when I have more spare time.

**Comment by IntegerLimit** [comment]
For now, just add the filter AFTER the conveyer.
