### ISSUE TITLE
Crafting without utilizing any item

### ISSUE THREAD

**Issue by Mattia3090** [Nomi-CEu/Nomi-CEu#991]
### Nomi CEu Version

1.6.1b

### Launcher

FTB Electron APP

### Environment

Singleplayer

### Mode

Normal Mode

### What Happened

Crafting objects without consuming the items

### Expected Behavior

Expected to craft the recipe and place the crafted item in a chest

### Reproduction Steps

1. Put a crafting recipe in an extended crafting table of the mod ExtendedCrafting: Nomifactory Edition
2. Put a hopper under the crafting connected to a chest
3. Take the craftable Item, with the items used in the recipe contained inside the Chest
4. it can be done even if the craftable item isn't visible in the slot when the hopper is doing it's job

**Comment by Folanlron** [comment]
This has already been fixed in the 1.7 series.

See https://github.com/Nomi-CEu/Nomi-CEu/pull/560
