### ISSUE TITLE
No Cleanroom loader and no compatibility

### ISSUE THREAD

**Issue by erialsan** [Nomi-CEu/Nomi-CEu#993]
### Nomi CEu Version

1.7a

### Launcher

Prism Launcher

### Configurations or Mods Changed

Use Cleanroom loader
And fugue,scalar

### Environment

Cleanroom Java22

### Mode

Normal Mode

### What Happened

Failed to start, seems to be due to Packmode

### Expected Behavior

To be activated according to Cleanroom's 99% Mod Compatibility

### Reproduction Steps

Use Cleanroom loader
And Java 22
Fix with Fugue and Scalar

### Logs

I deleted it, will provide it later.

### Additional Information

I reported it to the Cleanroom side, but they said I should report it here.

**Comment by erialsan** [comment]
log https://mclo.gs/u67mic6

**Comment by erialsan** [comment]
Apparently this is an inherent problem with recent Cleanroom builds!

**Comment by IntegerLimit** [comment]
This is not a problem with Cleanroom, rather Labs I believe. Will fix soon.

**Comment by lynxx131** [comment]
Upgraded to latest actions build of Nomi Labs and it works 🥳.

**Comment by erialsan** [comment]
IT IS WORK！
